name: dakanji_db_ui_search_example
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1
resolution: workspace

environment:
  sdk: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter

  util:
  dakanji_db_ui:
  dakanji_db_core:
  da_db_shared:
  css_inline_flutter:
  language_processing:
  
  get_it: ^9.2.0
  shared_preferences: ^2.5.4
  async: ^2.13.0
  csslib: ^1.0.2
  provider: ^6.1.5+1
  path_provider: ^2.1.5
  flutter_widget_from_html_core: ^0.17.0
  cupertino_icons: ^1.0.8
  path: ^1.9.1
  collection: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/dakanji.db