name: da_kanji_mobile
description: A cross platform app for mobile, desktop and web to help learn and use the Japanese language.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.4.0+28

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # all platforms supported
  shared_preferences: ^2.0.6
  url_launcher: ^6.0.7
  device_info_plus: ^2.0.1
  tutorial_coach_mark: ^1.0.0
  flutter_phoenix: ^1.0.0
  package_info_plus: ^1.0.3
  image: ^3.0.2
  flutter_markdown: ^0.6.2
  get_it: ^7.1.3
  provider: ^5.0.0
  universal_io: ^2.0.4
  awesome_dialog: ^2.1.0
  easy_localization: ^3.0.0
  flutter_layout_grid: ^1.0.3
  tuple: ^2.0.0

  # do NOT support all target platforms
  webviewx: ^0.2.1                 # android, iOS, web
  in_app_review: ^2.0.2            # android, iOS, MacOS, windows (limited)
  tflite_flutter: ^0.9.0           # android, iOS, Linux, MacOS, windows
  flutter_appavailability: ^0.0.21 # android, iOS
  uni_links: ^0.5.1                # android, iOS, web

  # packages which should only target specific platforms
  android_intent_plus: ^3.0.2      # android

  # utility 
  flutter_launcher_icons: ^0.9.2  # android, iOS, Linux, MacOS, windows
  flutter_native_splash: ^1.2.3   # android, iOS, web
  

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  # cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "media/icon_white.png"

# The following section is specific to Flutter.
flutter:
  
  fonts:
    - family: NotoSans
      fonts:
        - asset: fonts/Noto_Sans_JP/NotoSansJP-Black.otf
          weight: 900
        - asset: fonts/Noto_Sans_JP/NotoSansJP-Bold.otf
          weight: 700
        - asset: fonts/Noto_Sans_JP/NotoSansJP-Light.otf
          weight: 300
        - asset: fonts/Noto_Sans_JP/NotoSansJP-Medium.otf
          weight: 500
        - asset: fonts/Noto_Sans_JP/NotoSansJP-Regular.otf
          weight: 400
        - asset: fonts/Noto_Sans_JP/NotoSansJP-Thin.otf
          style: italic

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/CNN_single_char.tflite
    - assets/CNN_single_char_labels.txt
    - assets/kanji_drawing_aid_b.png
    - assets/kanji_drawing_aid_w.png

    - CHANGELOG.md
    - pubspec.yaml

    - media/icon.png
    - media/banner.png

    - assets/translations/

