
name: dakanji_db_workspace
publish_to: none
environment:
  sdk: 3.11.0-57.0.dev
  flutter: '>=3.10.0'

workspace:

  - apps/dakanji_db_ui_example
  - apps/dakanji_db_example

  - packages/dakanji_db_core
  - packages/dakanji_db_ui
  - packages/dakanji_db_shared
  - packages/dakanji_sqlite_extensions
  - packages/language_processing
