name: da_kanji_mobile
description: A cross platform app for mobile and desktop to help learn and use the Japanese language.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.1.0+31

environment:
  sdk: ">=2.16.0"
  flutter: ">=3.0.9"

dependencies:
  flutter:
    sdk: flutter
  
  # all platforms supported
  platform: 3.1.0
  shared_preferences: 2.0.13
  url_launcher: 6.1.2
  flutter_phoenix: 1.0.0
  image: 3.2.0
  flutter_markdown: 0.6.9+1
  get_it: 7.2.0
  provider: 6.0.3
  universal_io: 2.0.4
  awesome_dialog: 2.1.0
  easy_localization: 3.0.1
  flutter_layout_grid: 1.0.3
  tuple: 2.0.0
  lottie: 1.2.1
  liquid_swipe:
    path: ./plugins/liquid_swipe_flutter
  flutter_svg: 1.1.5
  onboarding_overlay : 3.0.0
  auto_size_text: 3.0.0
  keybinder: 1.0.1
  database_builder:
    path: ./plugins/DaKanji-Dictionary/database_builder
  flutter_staggered_animations: 1.1.1
  graphview: 1.1.1
  xml: 6.1.0
  objectbox: 1.6.2
  objectbox_flutter_libs: any
  kana_kit: 2.0.0
  multi_select_flutter: 4.1.2

  # do NOT support all target platforms
  webview_flutter: 3.0.0          # android, iOS
  in_app_review: 2.0.4            # android, iOS, MacOS, windows (limited)
  tflite_flutter:                 # android, iOS, Linux, MacOS, windows
    path: ./plugins/tflite_flutter_plugin
  flutter_appavailability:        # android, iOS
    path: ./plugins/flutter_appavailability
  kagome_dart: 
    path: ./plugins/kagome_dart
  uni_links: 0.5.1                # android, iOS, web

  # packages which should only target specific platforms
  android_intent_plus: 3.0.2      # android
  window_size:                     # desktop platforms
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: 03d957e

  # utility 
  flutter_launcher_icons: 0.9.2  # android, iOS, Linux, MacOS, windows
  flutter_native_splash: 2.2.9   # android, iOS, web

msix_config:
  display_name: DaKanji
  publisher: CN=EC6A3F44-67FB-44EF-B45B-1DACD55293B9
  publisher_display_name: DaAppLab
  identity_name: 61015DaAppLab.DaKanji
  logo_path: ./assets/images/icons/icon.png
  capabilities: internetClient
  execution-alias: DaKanji
  languages: en-us, de-de, ru-ru, ja-ja, zh-zh, it-it, fr-fr, es-es pl-pl
  

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  # cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  msix: 3.5.1
  
flutter_icons:
  android: "launcher_icon"
  ios: true
  macos: true
  windows: true 
  remove_alpha_ios: true
  image_path: "assets/images/icons/icon.png"

# The following section is specific to Flutter.
flutter:
  
  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/Noto_Sans_JP/NotoSansJP-Black.otf
          weight: 900
        - asset: assets/fonts/Noto_Sans_JP/NotoSansJP-Bold.otf
          weight: 700
        - asset: assets/fonts/Noto_Sans_JP/NotoSansJP-Light.otf
          weight: 300
        - asset: assets/fonts/Noto_Sans_JP/NotoSansJP-Medium.otf
          weight: 500
        - asset: assets/fonts/Noto_Sans_JP/NotoSansJP-Regular.otf
          weight: 400
        - asset: assets/fonts/Noto_Sans_JP/NotoSansJP-Thin.otf
          style: italic

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # DaKanji icons/images...
    - assets/images/icons/icon.png
    - assets/images/icons/banner.png
    # draw screen
    - assets/images/ui/kanji_drawing_aid.png
    # onboarding graphics
    - assets/images/onboarding/onboarding_1_1.png
    - assets/images/onboarding/onboarding_1_2.png
    - assets/images/onboarding/onboarding_2_1.png
    - assets/images/onboarding/onboarding_2_2.png
    - assets/animations/
    # icons
    - assets/fonts/icons/furigana_on.svg
    - assets/fonts/icons/furigana_off.svg
    - assets/fonts/icons/space_bar_on.svg
    - assets/fonts/icons/space_bar_off.svg
    - assets/fonts/icons/corner_resize.svg
    # tf lite models
    - assets/tflite_models/
    # dictionary
    - assets/dict/
    # misc
    - CHANGELOG.md
    - pubspec.yaml
    - CREDITS.md