name: dakanji_db
description: Scripts to populate DaKanji's database
repository: https://github.com/captaindario/dakanji-db
version: 4.0.0

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:
  path: 1.9.1
  drift: 2.21.0
  sqlite3: 2.4.7
  archive: 3.6.1
  tuple: 2.0.2
  euc: 1.0.6+8

dev_dependencies:
  drift_dev: 2.21.0
  build_runner: 2.4.13

  lints: 4.0.0
  test: 1.25.8

dependency_overrides:
  archive:
    git:
      url: https://github.com/brendan-duncan/archive