name: da_kanji_mobile
description: You are learning Japanese? Then you need to give "DaKanji" a try!

repository: https://github.com/captaindario/dakanji
issue_tracker: https://github.com/captaindario/dakanji/issues
funding:
  - https://github.com/sponsors/captaindario

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 3.3.0+77
beta: false

environment:
  sdk: ">=3.0.0"
  flutter: "3.16.3"

platforms:
  android:
  ios:
  linux:
  macos:
  windows:

dependencies:
  flutter:
    sdk: flutter
  
  # all platforms supported
  linked_scroll_controller: 0.2.0
  shared_preferences: 2.2.2
  url_launcher: 6.1.2
  flutter_phoenix: 1.0.0
  image: 4.0.17
  flutter_markdown: 0.6.13
  get_it: 7.6.4
  provider: 6.0.3
  universal_io: 2.2.2
  awesome_dialog: 3.1.0
  easy_localization: 3.0.2
  flutter_layout_grid: 2.0.5
  tuple: 2.0.1
  lottie: 1.2.1
  flutter_svg: 2.0.8
  onboarding_overlay : 3.1.0
  auto_size_text: 3.0.0
  feedback: 2.6.0
  flutter_staggered_animations: 1.1.1
  graphview: 1.1.1
  xml: 6.3.0
  reorderables: 0.5.0
  archive: 3.4.8
  device_info_plus: 9.0.3
  share_plus: 7.1.0
  file_picker: 5.3.3
  sqlite3: 2.1.0
  sqlite3_flutter_libs: 0.5.15
  json_annotation: 4.8.1
  flutter_spinkit: 5.1.0
  sentry_flutter: 7.13.2
  feedback_sentry: 2.4.0
  sentry: any
  dio: 5.0.1
  flutter_speed_dial: 7.0.0
  scrollable_positioned_list: 0.3.8
  pdf: 3.10.3
  rive: 0.11.17
  printing: 5.11.0
  path_parsing: any               # included in svg_flutter
  vector_graphics: any            # included in svg_flutter
  app_links: 3.5.0                # android, iOS, web, macos, windows (msix), linux

  media_kit: 1.1.10                              # Primary package.
  media_kit_video: 1.2.4                        # For video rendering.
  media_kit_libs_video: 1.0.4                   # Native video dependencies.
  flutter_widget_from_html_core: 0.14.9
  tflite_flutter: #0.10.4
    git:
      url: https://github.com/CaptainDario/flutter-tflite
  envied: 0.5.2
  envied_generator: 0.5.2
  async: 2.11.0
  path: 1.8.3
  http: 1.1.0
  collection: 1.18.0
  path_provider: 2.1.0
  yaml: 3.1.2
  quiver: 3.2.1
  flutter_riverpod: 2.4.0
  riverpod_annotation: 2.1.5
  another_flushbar: 1.12.30
  ambilytics: 1.0.4
  firebase_core: 2.24.2

  kana_kit:
    git:
      url: https://github.com/CaptainDario/kana_kit

  liquid_swipe:
    git:
      url: https://github.com/CaptainDario/DaKanji-Dependencies
      path: liquid_swipe_flutter
  database_builder:
    git:
      url: https://github.com/CaptainDario/DaKanji-Dictionary
      path: database_builder
      ref: v3.2.0
  
  # Not all platforms supported
  webview_flutter: 4.4.2                # android, iOS
  webview_flutter_wkwebview: any
  in_app_review: 2.0.4                  # android, iOS, MacOS, windows (limited)
  clipboard_watcher: 0.2.0              # android, iOS, macos, windows, linux

  #isar: android, iOS, macos, windows, linux
  isar: any # included in dakanji dictionary
  isar_flutter_libs: any # included in dakanji dictionary
  mecab_dart:                                   # android, iOS, macos, windows, linux
    git:
      url: https://github.com/CaptainDario/mecab_dart

  # packages that should only target specific platforms
  android_intent_plus: 3.0.2      # android
  window_manager: 0.3.4           # desktop
  #lutter_appavailability:        # android, iOS

  # utility 
  flutter_launcher_icons: 0.13.1  # android, iOS, Linux, MacOS, windows
  flutter_native_splash: 2.3.0   # android, iOS, web

dependency_overrides:
  url_protocol:
    git:
      url: https://github.com/LucasXu0/flutter_url_protocol.git
      commit: 77a8420

msix_config:
  display_name: DaKanji
  protocol_activation: dakanji
  app_uri_handler_hosts: dakanji.app, www.dakanji.app
  # package family name: 61015DaAppLab.DaKanji_t0074r350qa7p
  publisher: CN=EC6A3F44-67FB-44EF-B45B-1DACD55293B9
  publisher_display_name: DaAppLab
  identity_name: 61015DaAppLab.DaKanji
  logo_path: ./assets/images/dakanji/icon.png
  capabilities: internetClient
  execution-alias: DaKanji
  languages: en-us, de-de, ru-ru, ja-jp, zh-cn, it-it, fr-fr, es-es, pl-pl
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  custom_lint:
  riverpod_generator: ^2.3.2
  riverpod_lint: ^2.1.0
  msix: 3.16.6
  flutter_lints: ^2.0.3
  import_sorter: ^4.6.0
  json_serializable: 6.7.0
  build_runner: 2.4.4
  dependency_validator: 3.2.3
  isar_generator: any # included in dakanji dictionary
  
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path_ios: "assets/images/dakanji/icon_white.png"
  macos:
    generate: true
  windows:
    generate: true 
  
  image_path: "assets/images/dakanji/icon.png"


# The following section is specific to Flutter.
flutter:
  
  fonts:
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/Noto_Sans_JP/NotoSansJP-Black.ttf
          weight: 900
        - asset: assets/fonts/Noto_Sans_JP/NotoSansJP-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Noto_Sans_JP/NotoSansJP-Bold.ttf
          weight: 700
        - asset: assets/fonts/Noto_Sans_JP/NotoSansJP-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Noto_Sans_JP/NotoSansJP-Medium.ttf
          weight: 500
        - asset: assets/fonts/Noto_Sans_JP/NotoSansJP-Regular.ttf
          weight: 400
        - asset: assets/fonts/Noto_Sans_JP/NotoSansJP-Light.ttf
          weight: 300
        - asset: assets/fonts/Noto_Sans_JP/NotoSansJP-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Noto_Sans_JP/NotoSansJP-Thin.ttf
          weight: 100
    - family: Theater
      fonts:
        - asset: assets/fonts/theater/Theater_Bold.otf
          weight: 900
    - family: kouzan
      fonts:
        - asset: assets/fonts/kouzan/KouzanGyousho.otf
          weight: 900
    - family: DaKanjiIcons
      fonts:
        - asset: assets/icons/svg_to_font/fluttericon.com/fonts/DaKanjiIcons.ttf


  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # DaKanji icons/images...
    - assets/images/dakanji/icon.png
    - assets/images/dakanji/banner.png
    # draw screen
    - assets/images/ui/kanji_drawing_aid.png
    # dictionary screen
    - assets/dict/krad.zip
    - assets/dict/radk.zip
    # onboarding graphics
    - assets/images/onboarding/onboarding_1_1.vec
    - assets/images/onboarding/onboarding_1_2.vec
    - assets/images/onboarding/onboarding_2_1.vec
    - assets/images/onboarding/onboarding_2_2.vec
    - assets/images/onboarding/onboarding_3_1.vec
    - assets/images/onboarding/onboarding_3_2.vec
    - assets/images/onboarding/onboarding_4_1.vec
    - assets/images/onboarding/onboarding_4_2.vec

    - assets/animations/
    # kana mnemonics / sounds
    - assets/images/kana/individuals/
    - assets/audios/kana/individuals/
    # kanji drawing brush
    - assets/images/brush.png
    # icons
    - assets/icons/
    # misc
    - CHANGELOG.md
    - pubspec.yaml
    - CREDITS.md

    # large files
    # tf lite models
    - assets/tflite_models/
    # downloadable: mecab
    - assets/ipadic.zip
    # downloadable: dictionary
    - assets/dict/