name: dakanji_db
description: Scripts to populate DaKanji's database
repository: https://github.com/captaindario/dakanji-db
publish_to: none
version: 4.0.0

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:
  path: ^1.9.1
  drift: ^2.21.0
  sqlite3: ^2.4.7
  archive:
    git:
      url: https://github.com/brendan-duncan/archive
  tuple: ^2.0.2
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  universal_io: ^2.2.2
  mecab_for_dart:
    path: /Users/darioklepoch/dev/DaKanji/mecab_for_dart/

dev_dependencies:
  drift_dev: ^2.21.2
  build_runner: ^2.4.13
  import_sorter: ^4.6.0
  freezed: ^2.5.7
  lints: ^4.0.0
  test: ^1.25.8
  json_serializable: ^6.9.0

dependency_overrides:
  archive:
    git:
      url: https://github.com/brendan-duncan/archive