name: dakanji
version: 0.1.0
summary: A cross platform app to learn the Japanese language.
description: A cross platform app for mobile and desktop to help learn and use the Japanese language.

confinement: strict
base: core18
grade: stable

slots:
  dbus-dakanji: # adjust accordingly to your app name
    interface: dbus
    bus: session
    name: org.bar.dakanji # adjust accordingly to your app name and
    
apps:
  dakanji:
    command: dakanji
    extensions: [flutter-master] # Where "master" defines which Flutter channel to use for the build
    plugs:
    - network
    slots:
      - dbus-dakanji
parts:
  dakanji-app:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart # The main entry-point file of the application
