

/// Map where the key is a kana and the value is the matching mnemonic
Map<String, String> kanaMnemonics = {
  "あ" : "**A**ttention! Says the drill sergent",
  "ア" : "**E**ye of Horus",
  "い" : "**Ea**ster egg",
  "イ" : "**Ea**ves on a house",
  "う" : "**U**kulele",
  "ウ" : "**U**kulele",
  "え" : "**E**dge of the cliff is here",
  "エ" : "**E**mpire State Building",
  "お" : "Oak tree drops a leaf",
  "オ" : "**O**lympic torch",

  "は" : "**Hi**king boot",
  "ハ" : "**Ho**t lava",
  "ひ" : "**Hee**l",
  "ヒ" : "**Hee**l",
  "ふ" : "Mount **Fu**ji",
  "フ" : "**Foo**l's hat",
  "へ" : "**He**adband",
  "ヘ" : "**He**adband",
  "ほ" : "**Ho**tel room",
  "ホ" : "**Ho**ly cross",

  "か" : "**Co**d",
  "カ" : "**Co**d",
  "き" : "**Key**",
  "キ" : "**Key**",
  "く" : "**Cu**ckoo bird",
  "ク" : "**Coo**nskin cap",
  "け" : "**Ke**tchup bottle",
  "ケ" : "The letter '**K**'",
  "こ" : "**Co**mb",
  "コ" : "**Co**mb",

  "ま" : "**Mo**p and bucket",
  "マ" : "**Mo**ckingbird",
  "み" : "**Mea**n number is 21",
  "ミ" : "**Me**dian in th road",
  "む" : "**Moo**se chewing leaves",
  "ム" : "**Moo**n looks down from above",
  "め" : "**Me**dallion",
  "メ" : "**Me**tal knife",
  "も" : "**Mo**tor boat",
  "モ" : "**Mo**tor boat",

  "さ" : "**So**cks",
  "サ" : "**So**ck",
  "し" : "**Shee**p",
  "シ" : "**Shi**eld",
  "す" : "**Sou**p ladle in a pot",
  "ス" : "**Su**it and tie",
  "せ" : "**Se**curity guard",
  "セ" : "**Se**curity guard",
  "そ" : "**Sew** a stitch",
  "ソ" : "**Sew** a button",

  "や" : "**Ya**wl",
  "ヤ" : "**Ya**wl",
  "ゆ" : "**U**tensils for eating",
  "ユ" : "**U**-turn",
  "よ" : "**Yo**ga",
  "ヨ" : "**Yo**ga shorts",

  "た" : "**ta**",
  "タ" : "**Tomcat**",
  "ち" : "**Chee**p, **Chee**p, says the chick",
  "チ" : "**Chee**se wedge",
  "つ" : "**Tsu**nami wave",
  "ツ" : "**Tsu**nami wave. That's a big one!",
  "て" : "**Te**lescope",
  "テ" : "**Te**nt",
  "と" : "**To**aster",
  "ト" : "**To**piary",

  "ら" : "**Ro**d and reel",
  "ラ" : "**Ro**bber",
  "り" : "**Re**ach high",
  "リ" : "**Re**ach high",
  "る" : "**Roo**ster",
  "ル" : "**Rhu**barb",
  "れ" : "**Wre**nch",
  "レ" : "**Re**feree whistle",
  "ろ" : "I **wro**te the number '3'",
  "ロ" : "**Ro**ad sign",

  "な" : "**No**stril",
  "ナ" : "**Kn**ife",
  "に" : "**Knee**",
  "ニ" : "**Knee**",
  "ぬ" : "**Noo**dles and chopsticks",
  "ヌ" : "**New**born baby in a stroller",
  "ね" : "**Ne**xt train arrives at 12:00",
  "ネ" : "**Ne**ck brace",
  "の" : "**No** smoking",
  "ノ" : "**No** smoking",

  "わ" : "**Wa**llaby",
  "ワ" : "**Wa**termelon slice",
  "を" : "**Oh**! Water is too cold",
  "ヲ" : "**O**atmeal in a bowl",
  "ん" : "The letter '**n**'",
  "ン" : "E**n**velope",
};
