targets:
  $default:
    builders:
      drift_dev:
        options:
          sql:
            dialect: sqlite
            options:
              version: "3.44"
              modules:
                - fts5
                - json1
                - dbstat
                - spellfix1
              known_functions:
                compress: "blob null (blob null)"
                uncompress: "blob null (blob null)"