/// Flutter icons DaKanjiIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  DaKanjiIcons
///      fonts:
///       - asset: fonts/DaKanjiIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class DaKanjiIcons {
  DaKanjiIcons._();

  static const _kFontFam = 'DaKanjiIcons';
  static const String? _kFontPkg = null;

  static const IconData dojg = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData kanji_table = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData anki = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData kana_trainer = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData kanji_trainer = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData kana_table = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
