//based on conj.csv which was scraped from
//https://gitlab.com/yamagoya/jmdictdb/-/tree/master/jmdictdb/data

import 'conjo.dart';
import 'conj.dart';
import 'kwpos.dart';



// Convenience constants
const bool f = false;
const bool t = true;

/// 
List<Conjo> conjos = [
	Conjo(posIdToPosEnum[1]!, conjIdToConjEnum[1]!, f, f, 1, 1, 'い'),
	Conjo(posIdToPosEnum[1]!, conjIdToConjEnum[1]!, f, t, 1, 1, 'いです'),
	Conjo(posIdToPosEnum[1]!, conjIdToConjEnum[1]!, t, f, 1, 1, 'くない'),
	Conjo(posIdToPosEnum[1]!, conjIdToConjEnum[1]!, t, t, 1, 1, 'くないです'),
	Conjo(posIdToPosEnum[1]!, conjIdToConjEnum[1]!, t, t, 2, 1, 'くありません'),
	Conjo(posIdToPosEnum[1]!, conjIdToConjEnum[2]!, f, f, 1, 1, 'かった'),
	Conjo(posIdToPosEnum[1]!, conjIdToConjEnum[2]!, f, t, 1, 1, 'かったです'),
	Conjo(posIdToPosEnum[1]!, conjIdToConjEnum[2]!, t, f, 1, 1, 'くなかった'),
	Conjo(posIdToPosEnum[1]!, conjIdToConjEnum[2]!, t, t, 1, 1, 'くなかったです'),
	Conjo(posIdToPosEnum[1]!, conjIdToConjEnum[2]!, t, t, 2, 1, 'くありませんでした'),
	Conjo(posIdToPosEnum[1]!, conjIdToConjEnum[3]!, f, f, 1, 1, 'くて'),
	Conjo(posIdToPosEnum[1]!, conjIdToConjEnum[3]!, t, f, 1, 1, 'くなくて'),
	Conjo(posIdToPosEnum[1]!, conjIdToConjEnum[4]!, f, f, 1, 1, 'ければ'),
	Conjo(posIdToPosEnum[1]!, conjIdToConjEnum[4]!, t, f, 1, 1, 'くなければ'),
	Conjo(posIdToPosEnum[1]!, conjIdToConjEnum[7]!, f, f, 1, 1, 'くさせる'),
	Conjo(posIdToPosEnum[1]!, conjIdToConjEnum[9]!, f, f, 1, 1, 'かろう'),
	Conjo(posIdToPosEnum[1]!, conjIdToConjEnum[9]!, f, t, 1, 1, 'いでしょう'),
	Conjo(posIdToPosEnum[1]!, conjIdToConjEnum[11]!, f, f, 1, 1, 'かったら'),
	Conjo(posIdToPosEnum[1]!, conjIdToConjEnum[11]!, t, f, 1, 1, 'くなかったら'),
	Conjo(posIdToPosEnum[1]!, conjIdToConjEnum[12]!, f, f, 1, 1, 'かったり'),
	Conjo(posIdToPosEnum[2]!, conjIdToConjEnum[1]!, f, f, 1, 0, 'だ'),
	Conjo(posIdToPosEnum[7]!, conjIdToConjEnum[1]!, f, f, 1, 1, 'い'),
	Conjo(posIdToPosEnum[7]!, conjIdToConjEnum[1]!, f, t, 1, 1, 'いです'),
	Conjo(posIdToPosEnum[7]!, conjIdToConjEnum[1]!, t, f, 1, 1, 'くない', euphr: 'よ'),
	Conjo(posIdToPosEnum[7]!, conjIdToConjEnum[1]!, t, t, 1, 1, 'くないです', euphr: 'よ'),
	Conjo(posIdToPosEnum[7]!, conjIdToConjEnum[1]!, t, t, 2, 1, 'くありません', euphr: 'よ'),
	Conjo(posIdToPosEnum[7]!, conjIdToConjEnum[2]!, f, f, 1, 1, 'かった', euphr: 'よ'),
	Conjo(posIdToPosEnum[7]!, conjIdToConjEnum[2]!, f, t, 1, 1, 'かったです', euphr: 'よ'),
	Conjo(posIdToPosEnum[7]!, conjIdToConjEnum[2]!, t, f, 1, 1, 'くなかった', euphr: 'よ'),
	Conjo(posIdToPosEnum[7]!, conjIdToConjEnum[2]!, t, t, 1, 1, 'くなかったです', euphr: 'よ'),
	Conjo(posIdToPosEnum[7]!, conjIdToConjEnum[2]!, t, t, 2, 1, 'くありませんでした', euphr: 'よ'),
	Conjo(posIdToPosEnum[7]!, conjIdToConjEnum[3]!, f, f, 1, 1, 'くて', euphr: 'よ'),
	Conjo(posIdToPosEnum[7]!, conjIdToConjEnum[3]!, t, f, 1, 1, 'くなくて', euphr: 'よ'),
	Conjo(posIdToPosEnum[7]!, conjIdToConjEnum[4]!, f, f, 1, 1, 'ければ', euphr: 'よ'),
	Conjo(posIdToPosEnum[7]!, conjIdToConjEnum[4]!, t, f, 1, 1, 'くなければ', euphr: 'よ'),
	Conjo(posIdToPosEnum[7]!, conjIdToConjEnum[7]!, f, f, 1, 1, 'くさせる', euphr: 'よ'),
	Conjo(posIdToPosEnum[7]!, conjIdToConjEnum[9]!, f, f, 1, 1, 'かろう', euphr: 'よ'),
	Conjo(posIdToPosEnum[7]!, conjIdToConjEnum[9]!, f, t, 1, 1, 'いでしょう'),
	Conjo(posIdToPosEnum[7]!, conjIdToConjEnum[11]!, f, f, 1, 1, 'かったら', euphr: 'よ'),
	Conjo(posIdToPosEnum[7]!, conjIdToConjEnum[11]!, t, f, 1, 1, 'くなかったら', euphr: 'よ'),
	Conjo(posIdToPosEnum[7]!, conjIdToConjEnum[12]!, f, f, 1, 1, 'かったり', euphr: 'よ'),
	Conjo(posIdToPosEnum[15]!, conjIdToConjEnum[1]!, f, f, 1, 1, 'だ'),
	Conjo(posIdToPosEnum[15]!, conjIdToConjEnum[1]!, f, t, 1, 1, 'です'),
	Conjo(posIdToPosEnum[15]!, conjIdToConjEnum[1]!, t, f, 1, 1, 'ではない'),
	Conjo(posIdToPosEnum[15]!, conjIdToConjEnum[1]!, t, t, 1, 1, 'ではありません'),
	Conjo(posIdToPosEnum[15]!, conjIdToConjEnum[1]!, t, t, 2, 1, 'ではないです'),
	Conjo(posIdToPosEnum[15]!, conjIdToConjEnum[2]!, f, f, 1, 1, 'だった'),
	Conjo(posIdToPosEnum[15]!, conjIdToConjEnum[2]!, f, t, 1, 1, 'でした'),
	Conjo(posIdToPosEnum[15]!, conjIdToConjEnum[2]!, t, f, 1, 1, 'ではなかった'),
	Conjo(posIdToPosEnum[15]!, conjIdToConjEnum[2]!, t, t, 1, 1, 'ではありませんでした'),
	Conjo(posIdToPosEnum[15]!, conjIdToConjEnum[3]!, f, f, 1, 1, 'で'),
	Conjo(posIdToPosEnum[15]!, conjIdToConjEnum[3]!, f, t, 1, 1, 'でありまして'),
	Conjo(posIdToPosEnum[15]!, conjIdToConjEnum[3]!, t, f, 1, 1, 'ではなくて'),
	Conjo(posIdToPosEnum[15]!, conjIdToConjEnum[4]!, f, f, 1, 1, 'なら'),
	Conjo(posIdToPosEnum[15]!, conjIdToConjEnum[4]!, f, f, 2, 1, 'ならば'),
	Conjo(posIdToPosEnum[15]!, conjIdToConjEnum[4]!, f, f, 3, 1, 'であれば'),
	Conjo(posIdToPosEnum[15]!, conjIdToConjEnum[9]!, f, f, 1, 1, 'だろう'),
	Conjo(posIdToPosEnum[15]!, conjIdToConjEnum[9]!, f, t, 1, 1, 'でしょう'),
	Conjo(posIdToPosEnum[15]!, conjIdToConjEnum[10]!, f, f, 1, 1, 'であれ'),
	Conjo(posIdToPosEnum[15]!, conjIdToConjEnum[11]!, f, f, 1, 1, 'だったら'),
	Conjo(posIdToPosEnum[15]!, conjIdToConjEnum[11]!, f, t, 1, 1, 'でしたら'),
	Conjo(posIdToPosEnum[15]!, conjIdToConjEnum[11]!, t, f, 1, 1, 'ではなかったら'),
	Conjo(posIdToPosEnum[15]!, conjIdToConjEnum[11]!, t, t, 1, 1, 'ではありませんでしたら'),
	Conjo(posIdToPosEnum[15]!, conjIdToConjEnum[12]!, f, f, 1, 1, 'だったり'),
	Conjo(posIdToPosEnum[17]!, conjIdToConjEnum[1]!, f, f, 1, 0, 'だ'),
	Conjo(posIdToPosEnum[28]!, conjIdToConjEnum[1]!, f, f, 1, 1, 'る'),
	Conjo(posIdToPosEnum[28]!, conjIdToConjEnum[1]!, f, t, 1, 1, 'ます'),
	Conjo(posIdToPosEnum[28]!, conjIdToConjEnum[1]!, t, f, 1, 1, 'ない'),
	Conjo(posIdToPosEnum[28]!, conjIdToConjEnum[1]!, t, t, 1, 1, 'ません'),
	Conjo(posIdToPosEnum[28]!, conjIdToConjEnum[2]!, f, f, 1, 1, 'た'),
	Conjo(posIdToPosEnum[28]!, conjIdToConjEnum[2]!, f, t, 1, 1, 'ました'),
	Conjo(posIdToPosEnum[28]!, conjIdToConjEnum[2]!, t, f, 1, 1, 'なかった'),
	Conjo(posIdToPosEnum[28]!, conjIdToConjEnum[2]!, t, t, 1, 1, 'ませんでした'),
	Conjo(posIdToPosEnum[28]!, conjIdToConjEnum[3]!, f, f, 1, 1, 'て'),
	Conjo(posIdToPosEnum[28]!, conjIdToConjEnum[3]!, f, t, 1, 1, 'まして'),
	Conjo(posIdToPosEnum[28]!, conjIdToConjEnum[3]!, t, f, 1, 1, 'なくて'),
	Conjo(posIdToPosEnum[28]!, conjIdToConjEnum[3]!, t, f, 2, 1, 'ないで'),
	Conjo(posIdToPosEnum[28]!, conjIdToConjEnum[3]!, t, t, 1, 1, 'ませんで'),
	Conjo(posIdToPosEnum[28]!, conjIdToConjEnum[4]!, f, f, 1, 1, 'れば'),
	Conjo(posIdToPosEnum[28]!, conjIdToConjEnum[4]!, f, t, 1, 1, 'ますなら'),
	Conjo(posIdToPosEnum[28]!, conjIdToConjEnum[4]!, f, t, 2, 1, 'ますならば'),
	Conjo(posIdToPosEnum[28]!, conjIdToConjEnum[4]!, t, f, 1, 1, 'なければ'),
	Conjo(posIdToPosEnum[28]!, conjIdToConjEnum[4]!, t, t, 1, 1, 'ませんなら'),
	Conjo(posIdToPosEnum[28]!, conjIdToConjEnum[4]!, t, t, 2, 1, 'ませんならば'),
	Conjo(posIdToPosEnum[28]!, conjIdToConjEnum[5]!, f, f, 1, 1, 'られる'),
	Conjo(posIdToPosEnum[28]!, conjIdToConjEnum[5]!, f, f, 2, 1, 'れる'),
	Conjo(posIdToPosEnum[28]!, conjIdToConjEnum[5]!, f, t, 1, 1, 'られます'),
	Conjo(posIdToPosEnum[28]!, conjIdToConjEnum[5]!, f, t, 2, 1, 'れます'),
	Conjo(posIdToPosEnum[28]!, conjIdToConjEnum[5]!, t, f, 1, 1, 'られない'),
	Conjo(posIdToPosEnum[28]!, conjIdToConjEnum[5]!, t, f, 2, 1, 'れない'),
	Conjo(posIdToPosEnum[28]!, conjIdToConjEnum[5]!, t, t, 1, 1, 'られません'),
	Conjo(posIdToPosEnum[28]!, conjIdToConjEnum[5]!, t, t, 2, 1, 'れません'),
	Conjo(posIdToPosEnum[28]!, conjIdToConjEnum[6]!, f, f, 1, 1, 'られる'),
	Conjo(posIdToPosEnum[28]!, conjIdToConjEnum[6]!, f, t, 1, 1, 'られます'),
	Conjo(posIdToPosEnum[28]!, conjIdToConjEnum[6]!, t, f, 1, 1, 'られない'),
	Conjo(posIdToPosEnum[28]!, conjIdToConjEnum[6]!, t, t, 1, 1, 'られません'),
	Conjo(posIdToPosEnum[28]!, conjIdToConjEnum[7]!, f, f, 1, 1, 'させる'),
	Conjo(posIdToPosEnum[28]!, conjIdToConjEnum[7]!, f, f, 2, 1, 'さす'),
	Conjo(posIdToPosEnum[28]!, conjIdToConjEnum[7]!, f, t, 1, 1, 'させます'),
	Conjo(posIdToPosEnum[28]!, conjIdToConjEnum[7]!, f, t, 2, 1, 'さします'),
	Conjo(posIdToPosEnum[28]!, conjIdToConjEnum[7]!, t, f, 1, 1, 'させない'),
	Conjo(posIdToPosEnum[28]!, conjIdToConjEnum[7]!, t, f, 2, 1, 'ささない'),
	Conjo(posIdToPosEnum[28]!, conjIdToConjEnum[7]!, t, t, 1, 1, 'させません'),
	Conjo(posIdToPosEnum[28]!, conjIdToConjEnum[7]!, t, t, 2, 1, 'さしません'),
	Conjo(posIdToPosEnum[28]!, conjIdToConjEnum[8]!, f, f, 1, 1, 'させられる'),
	Conjo(posIdToPosEnum[28]!, conjIdToConjEnum[8]!, f, t, 1, 1, 'させられます'),
	Conjo(posIdToPosEnum[28]!, conjIdToConjEnum[8]!, t, f, 1, 1, 'させられない'),
	Conjo(posIdToPosEnum[28]!, conjIdToConjEnum[8]!, t, t, 1, 1, 'させられません'),
	Conjo(posIdToPosEnum[28]!, conjIdToConjEnum[9]!, f, f, 1, 1, 'よう'),
	Conjo(posIdToPosEnum[28]!, conjIdToConjEnum[9]!, f, t, 1, 1, 'ましょう'),
	Conjo(posIdToPosEnum[28]!, conjIdToConjEnum[9]!, t, f, 1, 1, 'まい'),
	Conjo(posIdToPosEnum[28]!, conjIdToConjEnum[9]!, t, t, 1, 1, 'ますまい'),
	Conjo(posIdToPosEnum[28]!, conjIdToConjEnum[10]!, f, f, 1, 1, 'ろ'),
	Conjo(posIdToPosEnum[28]!, conjIdToConjEnum[10]!, f, t, 1, 1, 'なさい'),
	Conjo(posIdToPosEnum[28]!, conjIdToConjEnum[10]!, t, f, 1, 1, 'るな'),
	Conjo(posIdToPosEnum[28]!, conjIdToConjEnum[10]!, t, t, 1, 1, 'なさるな'),
	Conjo(posIdToPosEnum[28]!, conjIdToConjEnum[11]!, f, f, 1, 1, 'たら'),
	Conjo(posIdToPosEnum[28]!, conjIdToConjEnum[11]!, f, t, 1, 1, 'ましたら'),
	Conjo(posIdToPosEnum[28]!, conjIdToConjEnum[11]!, t, f, 1, 1, 'なかったら'),
	Conjo(posIdToPosEnum[28]!, conjIdToConjEnum[11]!, t, t, 1, 1, 'ませんでしたら'),
	Conjo(posIdToPosEnum[28]!, conjIdToConjEnum[12]!, f, f, 1, 1, 'たり'),
	Conjo(posIdToPosEnum[28]!, conjIdToConjEnum[12]!, f, t, 1, 1, 'ましたり'),
	Conjo(posIdToPosEnum[28]!, conjIdToConjEnum[12]!, t, f, 1, 1, 'なかったり'),
	Conjo(posIdToPosEnum[28]!, conjIdToConjEnum[12]!, t, t, 1, 1, 'ませんでしたり'),
	Conjo(posIdToPosEnum[28]!, conjIdToConjEnum[13]!, f, f, 1, 1, '""'),
	Conjo(posIdToPosEnum[29]!, conjIdToConjEnum[1]!, f, f, 1, 1, 'る'),
	Conjo(posIdToPosEnum[29]!, conjIdToConjEnum[1]!, f, t, 1, 1, 'ます'),
	Conjo(posIdToPosEnum[29]!, conjIdToConjEnum[1]!, t, f, 1, 1, 'ない'),
	Conjo(posIdToPosEnum[29]!, conjIdToConjEnum[1]!, t, t, 1, 1, 'ません'),
	Conjo(posIdToPosEnum[29]!, conjIdToConjEnum[2]!, f, f, 1, 1, 'た'),
	Conjo(posIdToPosEnum[29]!, conjIdToConjEnum[2]!, f, t, 1, 1, 'ました'),
	Conjo(posIdToPosEnum[29]!, conjIdToConjEnum[2]!, t, f, 1, 1, 'なかった'),
	Conjo(posIdToPosEnum[29]!, conjIdToConjEnum[2]!, t, t, 1, 1, 'ませんでした'),
	Conjo(posIdToPosEnum[29]!, conjIdToConjEnum[3]!, f, f, 1, 1, 'て'),
	Conjo(posIdToPosEnum[29]!, conjIdToConjEnum[3]!, f, t, 1, 1, 'まして'),
	Conjo(posIdToPosEnum[29]!, conjIdToConjEnum[3]!, t, f, 1, 1, 'なくて'),
	Conjo(posIdToPosEnum[29]!, conjIdToConjEnum[3]!, t, f, 2, 1, 'ないで'),
	Conjo(posIdToPosEnum[29]!, conjIdToConjEnum[3]!, t, t, 1, 1, 'ませんで'),
	Conjo(posIdToPosEnum[29]!, conjIdToConjEnum[4]!, f, f, 1, 1, 'れば'),
	Conjo(posIdToPosEnum[29]!, conjIdToConjEnum[4]!, f, t, 1, 1, 'ますなら'),
	Conjo(posIdToPosEnum[29]!, conjIdToConjEnum[4]!, f, t, 2, 1, 'ますならば'),
	Conjo(posIdToPosEnum[29]!, conjIdToConjEnum[4]!, t, f, 1, 1, 'なければ'),
	Conjo(posIdToPosEnum[29]!, conjIdToConjEnum[4]!, t, t, 1, 1, 'ませんなら'),
	Conjo(posIdToPosEnum[29]!, conjIdToConjEnum[4]!, t, t, 2, 1, 'ませんならば'),
	Conjo(posIdToPosEnum[29]!, conjIdToConjEnum[5]!, f, f, 1, 1, 'られる'),
	Conjo(posIdToPosEnum[29]!, conjIdToConjEnum[5]!, f, f, 2, 1, 'れる'),
	Conjo(posIdToPosEnum[29]!, conjIdToConjEnum[5]!, f, t, 1, 1, 'られます'),
	Conjo(posIdToPosEnum[29]!, conjIdToConjEnum[5]!, f, t, 2, 1, 'れます'),
	Conjo(posIdToPosEnum[29]!, conjIdToConjEnum[5]!, t, f, 1, 1, 'られない'),
	Conjo(posIdToPosEnum[29]!, conjIdToConjEnum[5]!, t, f, 2, 1, 'れない'),
	Conjo(posIdToPosEnum[29]!, conjIdToConjEnum[5]!, t, t, 1, 1, 'られません'),
	Conjo(posIdToPosEnum[29]!, conjIdToConjEnum[5]!, t, t, 2, 1, 'れません'),
	Conjo(posIdToPosEnum[29]!, conjIdToConjEnum[6]!, f, f, 1, 1, 'られる'),
	Conjo(posIdToPosEnum[29]!, conjIdToConjEnum[6]!, f, t, 1, 1, 'られます'),
	Conjo(posIdToPosEnum[29]!, conjIdToConjEnum[6]!, t, f, 1, 1, 'られない'),
	Conjo(posIdToPosEnum[29]!, conjIdToConjEnum[6]!, t, t, 1, 1, 'られません'),
	Conjo(posIdToPosEnum[29]!, conjIdToConjEnum[7]!, f, f, 1, 1, 'させる'),
	Conjo(posIdToPosEnum[29]!, conjIdToConjEnum[7]!, f, f, 2, 1, 'さす'),
	Conjo(posIdToPosEnum[29]!, conjIdToConjEnum[7]!, f, t, 1, 1, 'させます'),
	Conjo(posIdToPosEnum[29]!, conjIdToConjEnum[7]!, f, t, 2, 1, 'さします'),
	Conjo(posIdToPosEnum[29]!, conjIdToConjEnum[7]!, t, f, 1, 1, 'させない'),
	Conjo(posIdToPosEnum[29]!, conjIdToConjEnum[7]!, t, f, 2, 1, 'ささない'),
	Conjo(posIdToPosEnum[29]!, conjIdToConjEnum[7]!, t, t, 1, 1, 'させません'),
	Conjo(posIdToPosEnum[29]!, conjIdToConjEnum[7]!, t, t, 2, 1, 'さしません'),
	Conjo(posIdToPosEnum[29]!, conjIdToConjEnum[8]!, f, f, 1, 1, 'させられる'),
	Conjo(posIdToPosEnum[29]!, conjIdToConjEnum[8]!, f, t, 1, 1, 'させられます'),
	Conjo(posIdToPosEnum[29]!, conjIdToConjEnum[8]!, t, f, 1, 1, 'させられない'),
	Conjo(posIdToPosEnum[29]!, conjIdToConjEnum[8]!, t, t, 1, 1, 'させられません'),
	Conjo(posIdToPosEnum[29]!, conjIdToConjEnum[9]!, f, f, 1, 1, 'よう'),
	Conjo(posIdToPosEnum[29]!, conjIdToConjEnum[9]!, f, t, 1, 1, 'ましょう'),
	Conjo(posIdToPosEnum[29]!, conjIdToConjEnum[9]!, t, f, 1, 1, 'まい'),
	Conjo(posIdToPosEnum[29]!, conjIdToConjEnum[9]!, t, t, 1, 1, 'ますまい'),
	Conjo(posIdToPosEnum[29]!, conjIdToConjEnum[10]!, f, f, 1, 1, '""'),
	Conjo(posIdToPosEnum[29]!, conjIdToConjEnum[10]!, f, t, 1, 1, 'なさい'),
	Conjo(posIdToPosEnum[29]!, conjIdToConjEnum[10]!, t, f, 1, 1, 'るな'),
	Conjo(posIdToPosEnum[29]!, conjIdToConjEnum[10]!, t, t, 1, 1, 'なさるな'),
	Conjo(posIdToPosEnum[29]!, conjIdToConjEnum[11]!, f, f, 1, 1, 'たら'),
	Conjo(posIdToPosEnum[29]!, conjIdToConjEnum[11]!, f, t, 1, 1, 'ましたら'),
	Conjo(posIdToPosEnum[29]!, conjIdToConjEnum[11]!, t, f, 1, 1, 'なかったら'),
	Conjo(posIdToPosEnum[29]!, conjIdToConjEnum[11]!, t, t, 1, 1, 'ませんでしたら'),
	Conjo(posIdToPosEnum[29]!, conjIdToConjEnum[12]!, f, f, 1, 1, 'たり'),
	Conjo(posIdToPosEnum[29]!, conjIdToConjEnum[12]!, f, t, 1, 1, 'ましたり'),
	Conjo(posIdToPosEnum[29]!, conjIdToConjEnum[12]!, t, f, 1, 1, 'なかったり'),
	Conjo(posIdToPosEnum[29]!, conjIdToConjEnum[12]!, t, t, 1, 1, 'ませんでしたり'),
	Conjo(posIdToPosEnum[29]!, conjIdToConjEnum[13]!, f, f, 1, 1, '""'),
	Conjo(posIdToPosEnum[30]!, conjIdToConjEnum[1]!, f, f, 1, 1, 'る'),
	Conjo(posIdToPosEnum[30]!, conjIdToConjEnum[1]!, f, t, 1, 1, 'います'),
	Conjo(posIdToPosEnum[30]!, conjIdToConjEnum[1]!, t, f, 1, 1, 'らない'),
	Conjo(posIdToPosEnum[30]!, conjIdToConjEnum[1]!, t, t, 1, 1, 'いません'),
	Conjo(posIdToPosEnum[30]!, conjIdToConjEnum[2]!, f, f, 1, 1, 'った'),
	Conjo(posIdToPosEnum[30]!, conjIdToConjEnum[2]!, f, t, 1, 1, 'いました'),
	Conjo(posIdToPosEnum[30]!, conjIdToConjEnum[2]!, t, f, 1, 1, 'らなかった'),
	Conjo(posIdToPosEnum[30]!, conjIdToConjEnum[2]!, t, t, 1, 1, 'いませんでした'),
	Conjo(posIdToPosEnum[30]!, conjIdToConjEnum[3]!, f, f, 1, 1, 'って'),
	Conjo(posIdToPosEnum[30]!, conjIdToConjEnum[3]!, f, t, 1, 1, 'いまして'),
	Conjo(posIdToPosEnum[30]!, conjIdToConjEnum[3]!, t, f, 1, 1, 'らなくて'),
	Conjo(posIdToPosEnum[30]!, conjIdToConjEnum[3]!, t, f, 2, 1, 'らないで'),
	Conjo(posIdToPosEnum[30]!, conjIdToConjEnum[3]!, t, t, 1, 1, 'いませんで'),
	Conjo(posIdToPosEnum[30]!, conjIdToConjEnum[4]!, f, f, 1, 1, 'れば'),
	Conjo(posIdToPosEnum[30]!, conjIdToConjEnum[4]!, f, t, 1, 1, 'いますなら'),
	Conjo(posIdToPosEnum[30]!, conjIdToConjEnum[4]!, f, t, 2, 1, 'いますならば'),
	Conjo(posIdToPosEnum[30]!, conjIdToConjEnum[4]!, t, f, 1, 1, 'らなければ'),
	Conjo(posIdToPosEnum[30]!, conjIdToConjEnum[4]!, t, t, 1, 1, 'いませんなら'),
	Conjo(posIdToPosEnum[30]!, conjIdToConjEnum[4]!, t, t, 2, 1, 'いませんならば'),
	Conjo(posIdToPosEnum[30]!, conjIdToConjEnum[5]!, f, f, 1, 1, 'れる'),
	Conjo(posIdToPosEnum[30]!, conjIdToConjEnum[5]!, f, t, 1, 1, 'れます'),
	Conjo(posIdToPosEnum[30]!, conjIdToConjEnum[5]!, t, f, 1, 1, 'れない'),
	Conjo(posIdToPosEnum[30]!, conjIdToConjEnum[5]!, t, t, 1, 1, 'れません'),
	Conjo(posIdToPosEnum[30]!, conjIdToConjEnum[6]!, f, f, 1, 1, 'られる'),
	Conjo(posIdToPosEnum[30]!, conjIdToConjEnum[6]!, f, t, 1, 1, 'られます'),
	Conjo(posIdToPosEnum[30]!, conjIdToConjEnum[6]!, t, f, 1, 1, 'られない'),
	Conjo(posIdToPosEnum[30]!, conjIdToConjEnum[6]!, t, t, 1, 1, 'られません'),
	Conjo(posIdToPosEnum[30]!, conjIdToConjEnum[7]!, f, f, 1, 1, 'らせる'),
	Conjo(posIdToPosEnum[30]!, conjIdToConjEnum[7]!, f, f, 2, 1, 'らす'),
	Conjo(posIdToPosEnum[30]!, conjIdToConjEnum[7]!, f, t, 1, 1, 'らせます'),
	Conjo(posIdToPosEnum[30]!, conjIdToConjEnum[7]!, f, t, 2, 1, 'らします'),
	Conjo(posIdToPosEnum[30]!, conjIdToConjEnum[7]!, t, f, 1, 1, 'らせない'),
	Conjo(posIdToPosEnum[30]!, conjIdToConjEnum[7]!, t, f, 2, 1, 'らさない'),
	Conjo(posIdToPosEnum[30]!, conjIdToConjEnum[7]!, t, t, 1, 1, 'らせません'),
	Conjo(posIdToPosEnum[30]!, conjIdToConjEnum[7]!, t, t, 2, 1, 'らしません'),
	Conjo(posIdToPosEnum[30]!, conjIdToConjEnum[8]!, f, f, 1, 1, 'らせられる'),
	Conjo(posIdToPosEnum[30]!, conjIdToConjEnum[8]!, f, f, 2, 1, 'らされる'),
	Conjo(posIdToPosEnum[30]!, conjIdToConjEnum[8]!, f, t, 1, 1, 'らせられます'),
	Conjo(posIdToPosEnum[30]!, conjIdToConjEnum[8]!, f, t, 2, 1, 'らされます'),
	Conjo(posIdToPosEnum[30]!, conjIdToConjEnum[8]!, t, f, 1, 1, 'らせられない'),
	Conjo(posIdToPosEnum[30]!, conjIdToConjEnum[8]!, t, f, 2, 1, 'らされない'),
	Conjo(posIdToPosEnum[30]!, conjIdToConjEnum[8]!, t, t, 1, 1, 'らせられません'),
	Conjo(posIdToPosEnum[30]!, conjIdToConjEnum[8]!, t, t, 2, 1, 'らされません'),
	Conjo(posIdToPosEnum[30]!, conjIdToConjEnum[9]!, f, f, 1, 1, 'ろう'),
	Conjo(posIdToPosEnum[30]!, conjIdToConjEnum[9]!, f, t, 1, 1, 'いましょう'),
	Conjo(posIdToPosEnum[30]!, conjIdToConjEnum[9]!, t, f, 1, 1, 'るまい'),
	Conjo(posIdToPosEnum[30]!, conjIdToConjEnum[9]!, t, t, 1, 1, 'いませんまい'),
	Conjo(posIdToPosEnum[30]!, conjIdToConjEnum[10]!, f, f, 1, 1, 'い'),
	Conjo(posIdToPosEnum[30]!, conjIdToConjEnum[10]!, f, t, 1, 1, 'いなさい'),
	Conjo(posIdToPosEnum[30]!, conjIdToConjEnum[10]!, t, f, 1, 1, 'るな'),
	Conjo(posIdToPosEnum[30]!, conjIdToConjEnum[10]!, t, t, 1, 1, 'いなさるな'),
	Conjo(posIdToPosEnum[30]!, conjIdToConjEnum[11]!, f, f, 1, 1, 'ったら'),
	Conjo(posIdToPosEnum[30]!, conjIdToConjEnum[11]!, f, t, 1, 1, 'いましたら'),
	Conjo(posIdToPosEnum[30]!, conjIdToConjEnum[11]!, t, f, 1, 1, 'らなかったら'),
	Conjo(posIdToPosEnum[30]!, conjIdToConjEnum[11]!, t, t, 1, 1, 'いませんでしたら'),
	Conjo(posIdToPosEnum[30]!, conjIdToConjEnum[12]!, f, f, 1, 1, 'ったり'),
	Conjo(posIdToPosEnum[30]!, conjIdToConjEnum[12]!, f, t, 1, 1, 'いましたり'),
	Conjo(posIdToPosEnum[30]!, conjIdToConjEnum[12]!, t, f, 1, 1, 'らなかったり'),
	Conjo(posIdToPosEnum[30]!, conjIdToConjEnum[12]!, t, t, 1, 1, 'いませんでしたり'),
	Conjo(posIdToPosEnum[30]!, conjIdToConjEnum[13]!, f, f, 1, 1, 'い'),
	Conjo(posIdToPosEnum[31]!, conjIdToConjEnum[1]!, f, f, 1, 1, 'ぶ'),
	Conjo(posIdToPosEnum[31]!, conjIdToConjEnum[1]!, f, t, 1, 1, 'びます'),
	Conjo(posIdToPosEnum[31]!, conjIdToConjEnum[1]!, t, f, 1, 1, 'ばない'),
	Conjo(posIdToPosEnum[31]!, conjIdToConjEnum[1]!, t, t, 1, 1, 'びません'),
	Conjo(posIdToPosEnum[31]!, conjIdToConjEnum[2]!, f, f, 1, 1, 'んだ'),
	Conjo(posIdToPosEnum[31]!, conjIdToConjEnum[2]!, f, t, 1, 1, 'びました'),
	Conjo(posIdToPosEnum[31]!, conjIdToConjEnum[2]!, t, f, 1, 1, 'ばなかった'),
	Conjo(posIdToPosEnum[31]!, conjIdToConjEnum[2]!, t, t, 1, 1, 'びませんでした'),
	Conjo(posIdToPosEnum[31]!, conjIdToConjEnum[3]!, f, f, 1, 1, 'んで'),
	Conjo(posIdToPosEnum[31]!, conjIdToConjEnum[3]!, f, t, 1, 1, 'びまして'),
	Conjo(posIdToPosEnum[31]!, conjIdToConjEnum[3]!, t, f, 1, 1, 'ばなくて'),
	Conjo(posIdToPosEnum[31]!, conjIdToConjEnum[3]!, t, f, 2, 1, 'ばないで'),
	Conjo(posIdToPosEnum[31]!, conjIdToConjEnum[3]!, t, t, 1, 1, 'びませんで'),
	Conjo(posIdToPosEnum[31]!, conjIdToConjEnum[4]!, f, f, 1, 1, 'べば'),
	Conjo(posIdToPosEnum[31]!, conjIdToConjEnum[4]!, f, t, 1, 1, 'びますなら'),
	Conjo(posIdToPosEnum[31]!, conjIdToConjEnum[4]!, f, t, 2, 1, 'びますならば'),
	Conjo(posIdToPosEnum[31]!, conjIdToConjEnum[4]!, t, f, 1, 1, 'ばなければ'),
	Conjo(posIdToPosEnum[31]!, conjIdToConjEnum[4]!, t, t, 1, 1, 'びませんなら'),
	Conjo(posIdToPosEnum[31]!, conjIdToConjEnum[4]!, t, t, 2, 1, 'びませんならば'),
	Conjo(posIdToPosEnum[31]!, conjIdToConjEnum[5]!, f, f, 1, 1, 'べる'),
	Conjo(posIdToPosEnum[31]!, conjIdToConjEnum[5]!, f, t, 1, 1, 'べます'),
	Conjo(posIdToPosEnum[31]!, conjIdToConjEnum[5]!, t, f, 1, 1, 'べない'),
	Conjo(posIdToPosEnum[31]!, conjIdToConjEnum[5]!, t, t, 1, 1, 'べません'),
	Conjo(posIdToPosEnum[31]!, conjIdToConjEnum[6]!, f, f, 1, 1, 'ばれる'),
	Conjo(posIdToPosEnum[31]!, conjIdToConjEnum[6]!, f, t, 1, 1, 'ばれます'),
	Conjo(posIdToPosEnum[31]!, conjIdToConjEnum[6]!, t, f, 1, 1, 'ばれない'),
	Conjo(posIdToPosEnum[31]!, conjIdToConjEnum[6]!, t, t, 1, 1, 'ばれません'),
	Conjo(posIdToPosEnum[31]!, conjIdToConjEnum[7]!, f, f, 1, 1, 'ばせる'),
	Conjo(posIdToPosEnum[31]!, conjIdToConjEnum[7]!, f, f, 2, 1, 'ばす'),
	Conjo(posIdToPosEnum[31]!, conjIdToConjEnum[7]!, f, t, 1, 1, 'ばせます'),
	Conjo(posIdToPosEnum[31]!, conjIdToConjEnum[7]!, f, t, 2, 1, 'ばします'),
	Conjo(posIdToPosEnum[31]!, conjIdToConjEnum[7]!, t, f, 1, 1, 'ばせない'),
	Conjo(posIdToPosEnum[31]!, conjIdToConjEnum[7]!, t, f, 2, 1, 'ばさない'),
	Conjo(posIdToPosEnum[31]!, conjIdToConjEnum[7]!, t, t, 1, 1, 'ばせません'),
	Conjo(posIdToPosEnum[31]!, conjIdToConjEnum[7]!, t, t, 2, 1, 'ばしません'),
	Conjo(posIdToPosEnum[31]!, conjIdToConjEnum[8]!, f, f, 1, 1, 'ばせられる'),
	Conjo(posIdToPosEnum[31]!, conjIdToConjEnum[8]!, f, f, 2, 1, 'ばされる'),
	Conjo(posIdToPosEnum[31]!, conjIdToConjEnum[8]!, f, t, 1, 1, 'ばせられます'),
	Conjo(posIdToPosEnum[31]!, conjIdToConjEnum[8]!, f, t, 2, 1, 'ばされます'),
	Conjo(posIdToPosEnum[31]!, conjIdToConjEnum[8]!, t, f, 1, 1, 'ばせられない'),
	Conjo(posIdToPosEnum[31]!, conjIdToConjEnum[8]!, t, f, 2, 1, 'ばされない'),
	Conjo(posIdToPosEnum[31]!, conjIdToConjEnum[8]!, t, t, 1, 1, 'ばせられません'),
	Conjo(posIdToPosEnum[31]!, conjIdToConjEnum[8]!, t, t, 2, 1, 'ばされません'),
	Conjo(posIdToPosEnum[31]!, conjIdToConjEnum[9]!, f, f, 1, 1, 'ぼう'),
	Conjo(posIdToPosEnum[31]!, conjIdToConjEnum[9]!, f, t, 1, 1, 'びましょう'),
	Conjo(posIdToPosEnum[31]!, conjIdToConjEnum[9]!, t, f, 1, 1, 'ぶまい'),
	Conjo(posIdToPosEnum[31]!, conjIdToConjEnum[9]!, t, t, 1, 1, 'びませんまい'),
	Conjo(posIdToPosEnum[31]!, conjIdToConjEnum[10]!, f, f, 1, 1, 'べ'),
	Conjo(posIdToPosEnum[31]!, conjIdToConjEnum[10]!, f, t, 1, 1, 'びなさい'),
	Conjo(posIdToPosEnum[31]!, conjIdToConjEnum[10]!, t, f, 1, 1, 'ぶな'),
	Conjo(posIdToPosEnum[31]!, conjIdToConjEnum[10]!, t, t, 1, 1, 'びなさるな'),
	Conjo(posIdToPosEnum[31]!, conjIdToConjEnum[11]!, f, f, 1, 1, 'んだら'),
	Conjo(posIdToPosEnum[31]!, conjIdToConjEnum[11]!, f, t, 1, 1, 'びましたら'),
	Conjo(posIdToPosEnum[31]!, conjIdToConjEnum[11]!, t, f, 1, 1, 'ばなかったら'),
	Conjo(posIdToPosEnum[31]!, conjIdToConjEnum[11]!, t, t, 1, 1, 'びませんでしたら'),
	Conjo(posIdToPosEnum[31]!, conjIdToConjEnum[12]!, f, f, 1, 1, 'んだり'),
	Conjo(posIdToPosEnum[31]!, conjIdToConjEnum[12]!, f, t, 1, 1, 'びましたり'),
	Conjo(posIdToPosEnum[31]!, conjIdToConjEnum[12]!, t, f, 1, 1, 'ばなかったり'),
	Conjo(posIdToPosEnum[31]!, conjIdToConjEnum[12]!, t, t, 1, 1, 'びませんでしたり'),
	Conjo(posIdToPosEnum[31]!, conjIdToConjEnum[13]!, f, f, 1, 1, 'び'),
	Conjo(posIdToPosEnum[32]!, conjIdToConjEnum[1]!, f, f, 1, 1, 'ぐ'),
	Conjo(posIdToPosEnum[32]!, conjIdToConjEnum[1]!, f, t, 1, 1, 'ぎます'),
	Conjo(posIdToPosEnum[32]!, conjIdToConjEnum[1]!, t, f, 1, 1, 'がない'),
	Conjo(posIdToPosEnum[32]!, conjIdToConjEnum[1]!, t, t, 1, 1, 'ぎません'),
	Conjo(posIdToPosEnum[32]!, conjIdToConjEnum[2]!, f, f, 1, 1, 'いだ'),
	Conjo(posIdToPosEnum[32]!, conjIdToConjEnum[2]!, f, t, 1, 1, 'ぎました'),
	Conjo(posIdToPosEnum[32]!, conjIdToConjEnum[2]!, t, f, 1, 1, 'がなかった'),
	Conjo(posIdToPosEnum[32]!, conjIdToConjEnum[2]!, t, t, 1, 1, 'ぎませんでした'),
	Conjo(posIdToPosEnum[32]!, conjIdToConjEnum[3]!, f, f, 1, 1, 'いで'),
	Conjo(posIdToPosEnum[32]!, conjIdToConjEnum[3]!, f, t, 1, 1, 'ぎまして'),
	Conjo(posIdToPosEnum[32]!, conjIdToConjEnum[3]!, t, f, 1, 1, 'がなくて'),
	Conjo(posIdToPosEnum[32]!, conjIdToConjEnum[3]!, t, f, 2, 1, 'がないで'),
	Conjo(posIdToPosEnum[32]!, conjIdToConjEnum[3]!, t, t, 1, 1, 'ぎませんで'),
	Conjo(posIdToPosEnum[32]!, conjIdToConjEnum[4]!, f, f, 1, 1, 'げば'),
	Conjo(posIdToPosEnum[32]!, conjIdToConjEnum[4]!, f, t, 1, 1, 'ぎますなら'),
	Conjo(posIdToPosEnum[32]!, conjIdToConjEnum[4]!, f, t, 2, 1, 'ぎますならば'),
	Conjo(posIdToPosEnum[32]!, conjIdToConjEnum[4]!, t, f, 1, 1, 'がなければ'),
	Conjo(posIdToPosEnum[32]!, conjIdToConjEnum[4]!, t, t, 1, 1, 'ぎませんなら'),
	Conjo(posIdToPosEnum[32]!, conjIdToConjEnum[4]!, t, t, 2, 1, 'ぎませんならば'),
	Conjo(posIdToPosEnum[32]!, conjIdToConjEnum[5]!, f, f, 1, 1, 'げる'),
	Conjo(posIdToPosEnum[32]!, conjIdToConjEnum[5]!, f, t, 1, 1, 'げます'),
	Conjo(posIdToPosEnum[32]!, conjIdToConjEnum[5]!, t, f, 1, 1, 'げない'),
	Conjo(posIdToPosEnum[32]!, conjIdToConjEnum[5]!, t, t, 1, 1, 'げません'),
	Conjo(posIdToPosEnum[32]!, conjIdToConjEnum[6]!, f, f, 1, 1, 'がれる'),
	Conjo(posIdToPosEnum[32]!, conjIdToConjEnum[6]!, f, t, 1, 1, 'がれます'),
	Conjo(posIdToPosEnum[32]!, conjIdToConjEnum[6]!, t, f, 1, 1, 'がれない'),
	Conjo(posIdToPosEnum[32]!, conjIdToConjEnum[6]!, t, t, 1, 1, 'がれません'),
	Conjo(posIdToPosEnum[32]!, conjIdToConjEnum[7]!, f, f, 1, 1, 'がせる'),
	Conjo(posIdToPosEnum[32]!, conjIdToConjEnum[7]!, f, f, 2, 1, 'がす'),
	Conjo(posIdToPosEnum[32]!, conjIdToConjEnum[7]!, f, t, 1, 1, 'がせます'),
	Conjo(posIdToPosEnum[32]!, conjIdToConjEnum[7]!, f, t, 2, 1, 'がします'),
	Conjo(posIdToPosEnum[32]!, conjIdToConjEnum[7]!, t, f, 1, 1, 'がせない'),
	Conjo(posIdToPosEnum[32]!, conjIdToConjEnum[7]!, t, f, 2, 1, 'がさない'),
	Conjo(posIdToPosEnum[32]!, conjIdToConjEnum[7]!, t, t, 1, 1, 'がせません'),
	Conjo(posIdToPosEnum[32]!, conjIdToConjEnum[7]!, t, t, 2, 1, 'がしません'),
	Conjo(posIdToPosEnum[32]!, conjIdToConjEnum[8]!, f, f, 1, 1, 'がせられる'),
	Conjo(posIdToPosEnum[32]!, conjIdToConjEnum[8]!, f, f, 2, 1, 'がされる'),
	Conjo(posIdToPosEnum[32]!, conjIdToConjEnum[8]!, f, t, 1, 1, 'がせられます'),
	Conjo(posIdToPosEnum[32]!, conjIdToConjEnum[8]!, f, t, 2, 1, 'がされます'),
	Conjo(posIdToPosEnum[32]!, conjIdToConjEnum[8]!, t, f, 1, 1, 'がせられない'),
	Conjo(posIdToPosEnum[32]!, conjIdToConjEnum[8]!, t, f, 2, 1, 'がされない'),
	Conjo(posIdToPosEnum[32]!, conjIdToConjEnum[8]!, t, t, 1, 1, 'がせられません'),
	Conjo(posIdToPosEnum[32]!, conjIdToConjEnum[8]!, t, t, 2, 1, 'がされません'),
	Conjo(posIdToPosEnum[32]!, conjIdToConjEnum[9]!, f, f, 1, 1, 'ごう'),
	Conjo(posIdToPosEnum[32]!, conjIdToConjEnum[9]!, f, t, 1, 1, 'ぎましょう'),
	Conjo(posIdToPosEnum[32]!, conjIdToConjEnum[9]!, t, f, 1, 1, 'ぐまい'),
	Conjo(posIdToPosEnum[32]!, conjIdToConjEnum[9]!, t, t, 1, 1, 'ぎませんまい'),
	Conjo(posIdToPosEnum[32]!, conjIdToConjEnum[10]!, f, f, 1, 1, 'げ'),
	Conjo(posIdToPosEnum[32]!, conjIdToConjEnum[10]!, f, t, 1, 1, 'ぎなさい'),
	Conjo(posIdToPosEnum[32]!, conjIdToConjEnum[10]!, t, f, 1, 1, 'ぐな'),
	Conjo(posIdToPosEnum[32]!, conjIdToConjEnum[10]!, t, t, 1, 1, 'ぎなさるな'),
	Conjo(posIdToPosEnum[32]!, conjIdToConjEnum[11]!, f, f, 1, 1, 'いだら'),
	Conjo(posIdToPosEnum[32]!, conjIdToConjEnum[11]!, f, t, 1, 1, 'ぎましたら'),
	Conjo(posIdToPosEnum[32]!, conjIdToConjEnum[11]!, t, f, 1, 1, 'がなかったら'),
	Conjo(posIdToPosEnum[32]!, conjIdToConjEnum[11]!, t, t, 1, 1, 'ぎませんでしたら'),
	Conjo(posIdToPosEnum[32]!, conjIdToConjEnum[12]!, f, f, 1, 1, 'いだり'),
	Conjo(posIdToPosEnum[32]!, conjIdToConjEnum[12]!, f, t, 1, 1, 'ぎましたり'),
	Conjo(posIdToPosEnum[32]!, conjIdToConjEnum[12]!, t, f, 1, 1, 'がなかったり'),
	Conjo(posIdToPosEnum[32]!, conjIdToConjEnum[12]!, t, t, 1, 1, 'ぎませんでしたり'),
	Conjo(posIdToPosEnum[32]!, conjIdToConjEnum[13]!, f, f, 1, 1, 'ぎ'),
	Conjo(posIdToPosEnum[33]!, conjIdToConjEnum[1]!, f, f, 1, 1, 'く'),
	Conjo(posIdToPosEnum[33]!, conjIdToConjEnum[1]!, f, t, 1, 1, 'きます'),
	Conjo(posIdToPosEnum[33]!, conjIdToConjEnum[1]!, t, f, 1, 1, 'かない'),
	Conjo(posIdToPosEnum[33]!, conjIdToConjEnum[1]!, t, t, 1, 1, 'きません'),
	Conjo(posIdToPosEnum[33]!, conjIdToConjEnum[2]!, f, f, 1, 1, 'いた'),
	Conjo(posIdToPosEnum[33]!, conjIdToConjEnum[2]!, f, t, 1, 1, 'きました'),
	Conjo(posIdToPosEnum[33]!, conjIdToConjEnum[2]!, t, f, 1, 1, 'かなかった'),
	Conjo(posIdToPosEnum[33]!, conjIdToConjEnum[2]!, t, t, 1, 1, 'きませんでした'),
	Conjo(posIdToPosEnum[33]!, conjIdToConjEnum[3]!, f, f, 1, 1, 'いて'),
	Conjo(posIdToPosEnum[33]!, conjIdToConjEnum[3]!, f, t, 1, 1, 'きまして'),
	Conjo(posIdToPosEnum[33]!, conjIdToConjEnum[3]!, t, f, 1, 1, 'かなくて'),
	Conjo(posIdToPosEnum[33]!, conjIdToConjEnum[3]!, t, f, 2, 1, 'かないで'),
	Conjo(posIdToPosEnum[33]!, conjIdToConjEnum[3]!, t, t, 1, 1, 'きませんで'),
	Conjo(posIdToPosEnum[33]!, conjIdToConjEnum[4]!, f, f, 1, 1, 'けば'),
	Conjo(posIdToPosEnum[33]!, conjIdToConjEnum[4]!, f, t, 1, 1, 'きますなら'),
	Conjo(posIdToPosEnum[33]!, conjIdToConjEnum[4]!, f, t, 2, 1, 'きますならば'),
	Conjo(posIdToPosEnum[33]!, conjIdToConjEnum[4]!, t, f, 1, 1, 'かなければ'),
	Conjo(posIdToPosEnum[33]!, conjIdToConjEnum[4]!, t, t, 1, 1, 'きませんなら'),
	Conjo(posIdToPosEnum[33]!, conjIdToConjEnum[4]!, t, t, 2, 1, 'きませんならば'),
	Conjo(posIdToPosEnum[33]!, conjIdToConjEnum[5]!, f, f, 1, 1, 'ける'),
	Conjo(posIdToPosEnum[33]!, conjIdToConjEnum[5]!, f, t, 1, 1, 'けます'),
	Conjo(posIdToPosEnum[33]!, conjIdToConjEnum[5]!, t, f, 1, 1, 'けない'),
	Conjo(posIdToPosEnum[33]!, conjIdToConjEnum[5]!, t, t, 1, 1, 'けません'),
	Conjo(posIdToPosEnum[33]!, conjIdToConjEnum[6]!, f, f, 1, 1, 'かれる'),
	Conjo(posIdToPosEnum[33]!, conjIdToConjEnum[6]!, f, t, 1, 1, 'かれます'),
	Conjo(posIdToPosEnum[33]!, conjIdToConjEnum[6]!, t, f, 1, 1, 'かれない'),
	Conjo(posIdToPosEnum[33]!, conjIdToConjEnum[6]!, t, t, 1, 1, 'かれません'),
	Conjo(posIdToPosEnum[33]!, conjIdToConjEnum[7]!, f, f, 1, 1, 'かせる'),
	Conjo(posIdToPosEnum[33]!, conjIdToConjEnum[7]!, f, f, 2, 1, 'かす'),
	Conjo(posIdToPosEnum[33]!, conjIdToConjEnum[7]!, f, t, 1, 1, 'かせます'),
	Conjo(posIdToPosEnum[33]!, conjIdToConjEnum[7]!, f, t, 2, 1, 'かします'),
	Conjo(posIdToPosEnum[33]!, conjIdToConjEnum[7]!, t, f, 1, 1, 'かせない'),
	Conjo(posIdToPosEnum[33]!, conjIdToConjEnum[7]!, t, f, 2, 1, 'かさない'),
	Conjo(posIdToPosEnum[33]!, conjIdToConjEnum[7]!, t, t, 1, 1, 'かせません'),
	Conjo(posIdToPosEnum[33]!, conjIdToConjEnum[7]!, t, t, 2, 1, 'かしません'),
	Conjo(posIdToPosEnum[33]!, conjIdToConjEnum[8]!, f, f, 1, 1, 'かせられる'),
	Conjo(posIdToPosEnum[33]!, conjIdToConjEnum[8]!, f, f, 2, 1, 'かされる'),
	Conjo(posIdToPosEnum[33]!, conjIdToConjEnum[8]!, f, t, 1, 1, 'かせられます'),
	Conjo(posIdToPosEnum[33]!, conjIdToConjEnum[8]!, f, t, 2, 1, 'かされます'),
	Conjo(posIdToPosEnum[33]!, conjIdToConjEnum[8]!, t, f, 1, 1, 'かせられない'),
	Conjo(posIdToPosEnum[33]!, conjIdToConjEnum[8]!, t, f, 2, 1, 'かされない'),
	Conjo(posIdToPosEnum[33]!, conjIdToConjEnum[8]!, t, t, 1, 1, 'かせられません'),
	Conjo(posIdToPosEnum[33]!, conjIdToConjEnum[8]!, t, t, 2, 1, 'かされません'),
	Conjo(posIdToPosEnum[33]!, conjIdToConjEnum[9]!, f, f, 1, 1, 'こう'),
	Conjo(posIdToPosEnum[33]!, conjIdToConjEnum[9]!, f, t, 1, 1, 'きましょう'),
	Conjo(posIdToPosEnum[33]!, conjIdToConjEnum[9]!, t, f, 1, 1, 'くまい'),
	Conjo(posIdToPosEnum[33]!, conjIdToConjEnum[9]!, t, t, 1, 1, 'きませんまい'),
	Conjo(posIdToPosEnum[33]!, conjIdToConjEnum[10]!, f, f, 1, 1, 'け'),
	Conjo(posIdToPosEnum[33]!, conjIdToConjEnum[10]!, f, t, 1, 1, 'きなさい'),
	Conjo(posIdToPosEnum[33]!, conjIdToConjEnum[10]!, t, f, 1, 1, 'くな'),
	Conjo(posIdToPosEnum[33]!, conjIdToConjEnum[10]!, t, t, 1, 1, 'きなさるな'),
	Conjo(posIdToPosEnum[33]!, conjIdToConjEnum[11]!, f, f, 1, 1, 'いたら'),
	Conjo(posIdToPosEnum[33]!, conjIdToConjEnum[11]!, f, t, 1, 1, 'きましたら'),
	Conjo(posIdToPosEnum[33]!, conjIdToConjEnum[11]!, t, f, 1, 1, 'かなかったら'),
	Conjo(posIdToPosEnum[33]!, conjIdToConjEnum[11]!, t, t, 1, 1, 'きませんでしたら'),
	Conjo(posIdToPosEnum[33]!, conjIdToConjEnum[12]!, f, f, 1, 1, 'いたり'),
	Conjo(posIdToPosEnum[33]!, conjIdToConjEnum[12]!, f, t, 1, 1, 'きましたり'),
	Conjo(posIdToPosEnum[33]!, conjIdToConjEnum[12]!, t, f, 1, 1, 'かなかったり'),
	Conjo(posIdToPosEnum[33]!, conjIdToConjEnum[12]!, t, t, 1, 1, 'きませんでしたり'),
	Conjo(posIdToPosEnum[33]!, conjIdToConjEnum[13]!, f, f, 1, 1, 'き'),
	Conjo(posIdToPosEnum[34]!, conjIdToConjEnum[1]!, f, f, 1, 1, 'く'),
	Conjo(posIdToPosEnum[34]!, conjIdToConjEnum[1]!, f, t, 1, 1, 'きます'),
	Conjo(posIdToPosEnum[34]!, conjIdToConjEnum[1]!, t, f, 1, 1, 'かない'),
	Conjo(posIdToPosEnum[34]!, conjIdToConjEnum[1]!, t, t, 1, 1, 'きません'),
	Conjo(posIdToPosEnum[34]!, conjIdToConjEnum[2]!, f, f, 1, 1, 'った'),
	Conjo(posIdToPosEnum[34]!, conjIdToConjEnum[2]!, f, t, 1, 1, 'きました'),
	Conjo(posIdToPosEnum[34]!, conjIdToConjEnum[2]!, t, f, 1, 1, 'かなかった'),
	Conjo(posIdToPosEnum[34]!, conjIdToConjEnum[2]!, t, t, 1, 1, 'きませんでした'),
	Conjo(posIdToPosEnum[34]!, conjIdToConjEnum[3]!, f, f, 1, 1, 'って'),
	Conjo(posIdToPosEnum[34]!, conjIdToConjEnum[3]!, f, t, 1, 1, 'きまして'),
	Conjo(posIdToPosEnum[34]!, conjIdToConjEnum[3]!, t, f, 1, 1, 'かなくて'),
	Conjo(posIdToPosEnum[34]!, conjIdToConjEnum[3]!, t, f, 2, 1, 'かないで'),
	Conjo(posIdToPosEnum[34]!, conjIdToConjEnum[3]!, t, t, 1, 1, 'きませんで'),
	Conjo(posIdToPosEnum[34]!, conjIdToConjEnum[4]!, f, f, 1, 1, 'けば'),
	Conjo(posIdToPosEnum[34]!, conjIdToConjEnum[4]!, f, t, 1, 1, 'きますなら'),
	Conjo(posIdToPosEnum[34]!, conjIdToConjEnum[4]!, f, t, 2, 1, 'きますならば'),
	Conjo(posIdToPosEnum[34]!, conjIdToConjEnum[4]!, t, f, 1, 1, 'かなければ'),
	Conjo(posIdToPosEnum[34]!, conjIdToConjEnum[4]!, t, t, 1, 1, 'きませんなら'),
	Conjo(posIdToPosEnum[34]!, conjIdToConjEnum[4]!, t, t, 2, 1, 'きませんならば'),
	Conjo(posIdToPosEnum[34]!, conjIdToConjEnum[5]!, f, f, 1, 1, 'ける'),
	Conjo(posIdToPosEnum[34]!, conjIdToConjEnum[5]!, f, t, 1, 1, 'けます'),
	Conjo(posIdToPosEnum[34]!, conjIdToConjEnum[5]!, t, f, 1, 1, 'けない'),
	Conjo(posIdToPosEnum[34]!, conjIdToConjEnum[5]!, t, t, 1, 1, 'けません'),
	Conjo(posIdToPosEnum[34]!, conjIdToConjEnum[6]!, f, f, 1, 1, 'かれる'),
	Conjo(posIdToPosEnum[34]!, conjIdToConjEnum[6]!, f, t, 1, 1, 'かれます'),
	Conjo(posIdToPosEnum[34]!, conjIdToConjEnum[6]!, t, f, 1, 1, 'かれない'),
	Conjo(posIdToPosEnum[34]!, conjIdToConjEnum[6]!, t, t, 1, 1, 'かれません'),
	Conjo(posIdToPosEnum[34]!, conjIdToConjEnum[7]!, f, f, 1, 1, 'かせる'),
	Conjo(posIdToPosEnum[34]!, conjIdToConjEnum[7]!, f, f, 2, 1, 'かす'),
	Conjo(posIdToPosEnum[34]!, conjIdToConjEnum[7]!, f, t, 1, 1, 'かせます'),
	Conjo(posIdToPosEnum[34]!, conjIdToConjEnum[7]!, f, t, 2, 1, 'かします'),
	Conjo(posIdToPosEnum[34]!, conjIdToConjEnum[7]!, t, f, 1, 1, 'かせない'),
	Conjo(posIdToPosEnum[34]!, conjIdToConjEnum[7]!, t, f, 2, 1, 'かさない'),
	Conjo(posIdToPosEnum[34]!, conjIdToConjEnum[7]!, t, t, 1, 1, 'かせません'),
	Conjo(posIdToPosEnum[34]!, conjIdToConjEnum[7]!, t, t, 2, 1, 'かしません'),
	Conjo(posIdToPosEnum[34]!, conjIdToConjEnum[8]!, f, f, 1, 1, 'かせられる'),
	Conjo(posIdToPosEnum[34]!, conjIdToConjEnum[8]!, f, f, 2, 1, 'かされる'),
	Conjo(posIdToPosEnum[34]!, conjIdToConjEnum[8]!, f, t, 1, 1, 'かせられます'),
	Conjo(posIdToPosEnum[34]!, conjIdToConjEnum[8]!, f, t, 2, 1, 'かされます'),
	Conjo(posIdToPosEnum[34]!, conjIdToConjEnum[8]!, t, f, 1, 1, 'かせられない'),
	Conjo(posIdToPosEnum[34]!, conjIdToConjEnum[8]!, t, f, 2, 1, 'かされない'),
	Conjo(posIdToPosEnum[34]!, conjIdToConjEnum[8]!, t, t, 1, 1, 'かせられません'),
	Conjo(posIdToPosEnum[34]!, conjIdToConjEnum[8]!, t, t, 2, 1, 'かされません'),
	Conjo(posIdToPosEnum[34]!, conjIdToConjEnum[9]!, f, f, 1, 1, 'こう'),
	Conjo(posIdToPosEnum[34]!, conjIdToConjEnum[9]!, f, t, 1, 1, 'きましょう'),
	Conjo(posIdToPosEnum[34]!, conjIdToConjEnum[9]!, t, f, 1, 1, 'くまい'),
	Conjo(posIdToPosEnum[34]!, conjIdToConjEnum[9]!, t, t, 1, 1, 'きませんまい'),
	Conjo(posIdToPosEnum[34]!, conjIdToConjEnum[10]!, f, f, 1, 1, 'け'),
	Conjo(posIdToPosEnum[34]!, conjIdToConjEnum[10]!, f, t, 1, 1, 'きなさい'),
	Conjo(posIdToPosEnum[34]!, conjIdToConjEnum[10]!, t, f, 1, 1, 'くな'),
	Conjo(posIdToPosEnum[34]!, conjIdToConjEnum[10]!, t, t, 1, 1, 'きなさるな'),
	Conjo(posIdToPosEnum[34]!, conjIdToConjEnum[11]!, f, f, 1, 1, 'ったら'),
	Conjo(posIdToPosEnum[34]!, conjIdToConjEnum[11]!, f, t, 1, 1, 'きましたら'),
	Conjo(posIdToPosEnum[34]!, conjIdToConjEnum[11]!, t, f, 1, 1, 'かなかったら'),
	Conjo(posIdToPosEnum[34]!, conjIdToConjEnum[11]!, t, t, 1, 1, 'きませんでしたら'),
	Conjo(posIdToPosEnum[34]!, conjIdToConjEnum[12]!, f, f, 1, 1, 'ったり'),
	Conjo(posIdToPosEnum[34]!, conjIdToConjEnum[12]!, f, t, 1, 1, 'きましたり'),
	Conjo(posIdToPosEnum[34]!, conjIdToConjEnum[12]!, t, f, 1, 1, 'かなかったり'),
	Conjo(posIdToPosEnum[34]!, conjIdToConjEnum[12]!, t, t, 1, 1, 'きませんでしたり'),
	Conjo(posIdToPosEnum[34]!, conjIdToConjEnum[13]!, f, f, 1, 1, 'き'),
	Conjo(posIdToPosEnum[35]!, conjIdToConjEnum[1]!, f, f, 1, 1, 'む'),
	Conjo(posIdToPosEnum[35]!, conjIdToConjEnum[1]!, f, t, 1, 1, 'みます'),
	Conjo(posIdToPosEnum[35]!, conjIdToConjEnum[1]!, t, f, 1, 1, 'まない'),
	Conjo(posIdToPosEnum[35]!, conjIdToConjEnum[1]!, t, t, 1, 1, 'みません'),
	Conjo(posIdToPosEnum[35]!, conjIdToConjEnum[2]!, f, f, 1, 1, 'んだ'),
	Conjo(posIdToPosEnum[35]!, conjIdToConjEnum[2]!, f, t, 1, 1, 'みました'),
	Conjo(posIdToPosEnum[35]!, conjIdToConjEnum[2]!, t, f, 1, 1, 'まなかった'),
	Conjo(posIdToPosEnum[35]!, conjIdToConjEnum[2]!, t, t, 1, 1, 'みませんでした'),
	Conjo(posIdToPosEnum[35]!, conjIdToConjEnum[3]!, f, f, 1, 1, 'んで'),
	Conjo(posIdToPosEnum[35]!, conjIdToConjEnum[3]!, f, t, 1, 1, 'みまして'),
	Conjo(posIdToPosEnum[35]!, conjIdToConjEnum[3]!, t, f, 1, 1, 'まなくて'),
	Conjo(posIdToPosEnum[35]!, conjIdToConjEnum[3]!, t, f, 2, 1, 'まないで'),
	Conjo(posIdToPosEnum[35]!, conjIdToConjEnum[3]!, t, t, 1, 1, 'みませんで'),
	Conjo(posIdToPosEnum[35]!, conjIdToConjEnum[4]!, f, f, 1, 1, 'めば'),
	Conjo(posIdToPosEnum[35]!, conjIdToConjEnum[4]!, f, t, 1, 1, 'みますなら'),
	Conjo(posIdToPosEnum[35]!, conjIdToConjEnum[4]!, f, t, 2, 1, 'みますならば'),
	Conjo(posIdToPosEnum[35]!, conjIdToConjEnum[4]!, t, f, 1, 1, 'まなければ'),
	Conjo(posIdToPosEnum[35]!, conjIdToConjEnum[4]!, t, t, 1, 1, 'みませんなら'),
	Conjo(posIdToPosEnum[35]!, conjIdToConjEnum[4]!, t, t, 2, 1, 'みませんならば'),
	Conjo(posIdToPosEnum[35]!, conjIdToConjEnum[5]!, f, f, 1, 1, 'める'),
	Conjo(posIdToPosEnum[35]!, conjIdToConjEnum[5]!, f, t, 1, 1, 'めます'),
	Conjo(posIdToPosEnum[35]!, conjIdToConjEnum[5]!, t, f, 1, 1, 'めない'),
	Conjo(posIdToPosEnum[35]!, conjIdToConjEnum[5]!, t, t, 1, 1, 'めません'),
	Conjo(posIdToPosEnum[35]!, conjIdToConjEnum[6]!, f, f, 1, 1, 'まれる'),
	Conjo(posIdToPosEnum[35]!, conjIdToConjEnum[6]!, f, t, 1, 1, 'まれます'),
	Conjo(posIdToPosEnum[35]!, conjIdToConjEnum[6]!, t, f, 1, 1, 'まれない'),
	Conjo(posIdToPosEnum[35]!, conjIdToConjEnum[6]!, t, t, 1, 1, 'まれません'),
	Conjo(posIdToPosEnum[35]!, conjIdToConjEnum[7]!, f, f, 1, 1, 'ませる'),
	Conjo(posIdToPosEnum[35]!, conjIdToConjEnum[7]!, f, f, 2, 1, 'ます'),
	Conjo(posIdToPosEnum[35]!, conjIdToConjEnum[7]!, f, t, 1, 1, 'ませます'),
	Conjo(posIdToPosEnum[35]!, conjIdToConjEnum[7]!, f, t, 2, 1, 'まします'),
	Conjo(posIdToPosEnum[35]!, conjIdToConjEnum[7]!, t, f, 1, 1, 'ませない'),
	Conjo(posIdToPosEnum[35]!, conjIdToConjEnum[7]!, t, f, 2, 1, 'まさない'),
	Conjo(posIdToPosEnum[35]!, conjIdToConjEnum[7]!, t, t, 1, 1, 'ませません'),
	Conjo(posIdToPosEnum[35]!, conjIdToConjEnum[7]!, t, t, 2, 1, 'ましません'),
	Conjo(posIdToPosEnum[35]!, conjIdToConjEnum[8]!, f, f, 1, 1, 'ませられる'),
	Conjo(posIdToPosEnum[35]!, conjIdToConjEnum[8]!, f, f, 2, 1, 'まされる'),
	Conjo(posIdToPosEnum[35]!, conjIdToConjEnum[8]!, f, t, 1, 1, 'ませられます'),
	Conjo(posIdToPosEnum[35]!, conjIdToConjEnum[8]!, f, t, 2, 1, 'まされます'),
	Conjo(posIdToPosEnum[35]!, conjIdToConjEnum[8]!, t, f, 1, 1, 'ませられない'),
	Conjo(posIdToPosEnum[35]!, conjIdToConjEnum[8]!, t, f, 2, 1, 'まされない'),
	Conjo(posIdToPosEnum[35]!, conjIdToConjEnum[8]!, t, t, 1, 1, 'ませられません'),
	Conjo(posIdToPosEnum[35]!, conjIdToConjEnum[8]!, t, t, 2, 1, 'まされません'),
	Conjo(posIdToPosEnum[35]!, conjIdToConjEnum[9]!, f, f, 1, 1, 'もう'),
	Conjo(posIdToPosEnum[35]!, conjIdToConjEnum[9]!, f, t, 1, 1, 'みましょう'),
	Conjo(posIdToPosEnum[35]!, conjIdToConjEnum[9]!, t, f, 1, 1, 'むまい'),
	Conjo(posIdToPosEnum[35]!, conjIdToConjEnum[9]!, t, t, 1, 1, 'みませんまい'),
	Conjo(posIdToPosEnum[35]!, conjIdToConjEnum[10]!, f, f, 1, 1, 'め'),
	Conjo(posIdToPosEnum[35]!, conjIdToConjEnum[10]!, f, t, 1, 1, 'みなさい'),
	Conjo(posIdToPosEnum[35]!, conjIdToConjEnum[10]!, t, f, 1, 1, 'むな'),
	Conjo(posIdToPosEnum[35]!, conjIdToConjEnum[10]!, t, t, 1, 1, 'みなさるな'),
	Conjo(posIdToPosEnum[35]!, conjIdToConjEnum[11]!, f, f, 1, 1, 'んだら'),
	Conjo(posIdToPosEnum[35]!, conjIdToConjEnum[11]!, f, t, 1, 1, 'みましたら'),
	Conjo(posIdToPosEnum[35]!, conjIdToConjEnum[11]!, t, f, 1, 1, 'まなかったら'),
	Conjo(posIdToPosEnum[35]!, conjIdToConjEnum[11]!, t, t, 1, 1, 'みませんでしたら'),
	Conjo(posIdToPosEnum[35]!, conjIdToConjEnum[12]!, f, f, 1, 1, 'んだり'),
	Conjo(posIdToPosEnum[35]!, conjIdToConjEnum[12]!, f, t, 1, 1, 'みましたり'),
	Conjo(posIdToPosEnum[35]!, conjIdToConjEnum[12]!, t, f, 1, 1, 'まなかったり'),
	Conjo(posIdToPosEnum[35]!, conjIdToConjEnum[12]!, t, t, 1, 1, 'みませんでしたり'),
	Conjo(posIdToPosEnum[35]!, conjIdToConjEnum[13]!, f, f, 1, 1, 'み'),
	Conjo(posIdToPosEnum[36]!, conjIdToConjEnum[1]!, f, f, 1, 1, 'ぬ'),
	Conjo(posIdToPosEnum[36]!, conjIdToConjEnum[1]!, f, t, 1, 1, 'にます'),
	Conjo(posIdToPosEnum[36]!, conjIdToConjEnum[1]!, t, f, 1, 1, 'なない'),
	Conjo(posIdToPosEnum[36]!, conjIdToConjEnum[1]!, t, t, 1, 1, 'にません'),
	Conjo(posIdToPosEnum[36]!, conjIdToConjEnum[2]!, f, f, 1, 1, 'んだ'),
	Conjo(posIdToPosEnum[36]!, conjIdToConjEnum[2]!, f, t, 1, 1, 'にました'),
	Conjo(posIdToPosEnum[36]!, conjIdToConjEnum[2]!, t, f, 1, 1, 'ななかった'),
	Conjo(posIdToPosEnum[36]!, conjIdToConjEnum[2]!, t, t, 1, 1, 'にませんでした'),
	Conjo(posIdToPosEnum[36]!, conjIdToConjEnum[3]!, f, f, 1, 1, 'んで'),
	Conjo(posIdToPosEnum[36]!, conjIdToConjEnum[3]!, f, t, 1, 1, 'にまして'),
	Conjo(posIdToPosEnum[36]!, conjIdToConjEnum[3]!, t, f, 1, 1, 'ななくて'),
	Conjo(posIdToPosEnum[36]!, conjIdToConjEnum[3]!, t, f, 2, 1, 'なないで'),
	Conjo(posIdToPosEnum[36]!, conjIdToConjEnum[3]!, t, t, 1, 1, 'にませんで'),
	Conjo(posIdToPosEnum[36]!, conjIdToConjEnum[4]!, f, f, 1, 1, 'ねば'),
	Conjo(posIdToPosEnum[36]!, conjIdToConjEnum[4]!, f, t, 1, 1, 'にますなら'),
	Conjo(posIdToPosEnum[36]!, conjIdToConjEnum[4]!, f, t, 2, 1, 'にますならば'),
	Conjo(posIdToPosEnum[36]!, conjIdToConjEnum[4]!, t, f, 1, 1, 'ななければ'),
	Conjo(posIdToPosEnum[36]!, conjIdToConjEnum[4]!, t, t, 1, 1, 'にませんなら'),
	Conjo(posIdToPosEnum[36]!, conjIdToConjEnum[4]!, t, t, 2, 1, 'にませんならば'),
	Conjo(posIdToPosEnum[36]!, conjIdToConjEnum[5]!, f, f, 1, 1, 'ねる'),
	Conjo(posIdToPosEnum[36]!, conjIdToConjEnum[5]!, f, t, 1, 1, 'ねます'),
	Conjo(posIdToPosEnum[36]!, conjIdToConjEnum[5]!, t, f, 1, 1, 'ねない'),
	Conjo(posIdToPosEnum[36]!, conjIdToConjEnum[5]!, t, t, 1, 1, 'ねません'),
	Conjo(posIdToPosEnum[36]!, conjIdToConjEnum[6]!, f, f, 1, 1, 'なれる'),
	Conjo(posIdToPosEnum[36]!, conjIdToConjEnum[6]!, f, t, 1, 1, 'なれます'),
	Conjo(posIdToPosEnum[36]!, conjIdToConjEnum[6]!, t, f, 1, 1, 'なれない'),
	Conjo(posIdToPosEnum[36]!, conjIdToConjEnum[6]!, t, t, 1, 1, 'なれません'),
	Conjo(posIdToPosEnum[36]!, conjIdToConjEnum[7]!, f, f, 1, 1, 'なせる'),
	Conjo(posIdToPosEnum[36]!, conjIdToConjEnum[7]!, f, f, 2, 1, 'なす'),
	Conjo(posIdToPosEnum[36]!, conjIdToConjEnum[7]!, f, t, 1, 1, 'なせます'),
	Conjo(posIdToPosEnum[36]!, conjIdToConjEnum[7]!, f, t, 2, 1, 'なします'),
	Conjo(posIdToPosEnum[36]!, conjIdToConjEnum[7]!, t, f, 1, 1, 'なせない'),
	Conjo(posIdToPosEnum[36]!, conjIdToConjEnum[7]!, t, f, 2, 1, 'なさない'),
	Conjo(posIdToPosEnum[36]!, conjIdToConjEnum[7]!, t, t, 1, 1, 'なせません'),
	Conjo(posIdToPosEnum[36]!, conjIdToConjEnum[7]!, t, t, 2, 1, 'なしません'),
	Conjo(posIdToPosEnum[36]!, conjIdToConjEnum[8]!, f, f, 1, 1, 'なせられる'),
	Conjo(posIdToPosEnum[36]!, conjIdToConjEnum[8]!, f, f, 2, 1, 'なされる'),
	Conjo(posIdToPosEnum[36]!, conjIdToConjEnum[8]!, f, t, 1, 1, 'なせられます'),
	Conjo(posIdToPosEnum[36]!, conjIdToConjEnum[8]!, f, t, 2, 1, 'なされます'),
	Conjo(posIdToPosEnum[36]!, conjIdToConjEnum[8]!, t, f, 1, 1, 'なせられない'),
	Conjo(posIdToPosEnum[36]!, conjIdToConjEnum[8]!, t, f, 2, 1, 'なされない'),
	Conjo(posIdToPosEnum[36]!, conjIdToConjEnum[8]!, t, t, 1, 1, 'なせられません'),
	Conjo(posIdToPosEnum[36]!, conjIdToConjEnum[8]!, t, t, 2, 1, 'なされません'),
	Conjo(posIdToPosEnum[36]!, conjIdToConjEnum[9]!, f, f, 1, 1, 'のう'),
	Conjo(posIdToPosEnum[36]!, conjIdToConjEnum[9]!, f, t, 1, 1, 'にましょう'),
	Conjo(posIdToPosEnum[36]!, conjIdToConjEnum[9]!, t, f, 1, 1, 'ぬまい'),
	Conjo(posIdToPosEnum[36]!, conjIdToConjEnum[9]!, t, t, 1, 1, 'にませんまい'),
	Conjo(posIdToPosEnum[36]!, conjIdToConjEnum[10]!, f, f, 1, 1, 'ね'),
	Conjo(posIdToPosEnum[36]!, conjIdToConjEnum[10]!, f, t, 1, 1, 'になさい'),
	Conjo(posIdToPosEnum[36]!, conjIdToConjEnum[10]!, t, f, 1, 1, 'ぬな'),
	Conjo(posIdToPosEnum[36]!, conjIdToConjEnum[10]!, t, t, 1, 1, 'になさるな'),
	Conjo(posIdToPosEnum[36]!, conjIdToConjEnum[11]!, f, f, 1, 1, 'んだら'),
	Conjo(posIdToPosEnum[36]!, conjIdToConjEnum[11]!, f, t, 1, 1, 'にましたら'),
	Conjo(posIdToPosEnum[36]!, conjIdToConjEnum[11]!, t, f, 1, 1, 'ななかったら'),
	Conjo(posIdToPosEnum[36]!, conjIdToConjEnum[11]!, t, t, 1, 1, 'にませんでしたら'),
	Conjo(posIdToPosEnum[36]!, conjIdToConjEnum[12]!, f, f, 1, 1, 'んだり'),
	Conjo(posIdToPosEnum[36]!, conjIdToConjEnum[12]!, f, t, 1, 1, 'にましたり'),
	Conjo(posIdToPosEnum[36]!, conjIdToConjEnum[12]!, t, f, 1, 1, 'ななかったり'),
	Conjo(posIdToPosEnum[36]!, conjIdToConjEnum[12]!, t, t, 1, 1, 'にませんでしたり'),
	Conjo(posIdToPosEnum[36]!, conjIdToConjEnum[13]!, f, f, 1, 1, 'に'),
	Conjo(posIdToPosEnum[37]!, conjIdToConjEnum[1]!, f, f, 1, 1, 'る'),
	Conjo(posIdToPosEnum[37]!, conjIdToConjEnum[1]!, f, t, 1, 1, 'ります'),
	Conjo(posIdToPosEnum[37]!, conjIdToConjEnum[1]!, t, f, 1, 1, 'らない'),
	Conjo(posIdToPosEnum[37]!, conjIdToConjEnum[1]!, t, t, 1, 1, 'りません'),
	Conjo(posIdToPosEnum[37]!, conjIdToConjEnum[2]!, f, f, 1, 1, 'った'),
	Conjo(posIdToPosEnum[37]!, conjIdToConjEnum[2]!, f, t, 1, 1, 'りました'),
	Conjo(posIdToPosEnum[37]!, conjIdToConjEnum[2]!, t, f, 1, 1, 'らなかった'),
	Conjo(posIdToPosEnum[37]!, conjIdToConjEnum[2]!, t, t, 1, 1, 'りませんでした'),
	Conjo(posIdToPosEnum[37]!, conjIdToConjEnum[3]!, f, f, 1, 1, 'って'),
	Conjo(posIdToPosEnum[37]!, conjIdToConjEnum[3]!, f, t, 1, 1, 'りまして'),
	Conjo(posIdToPosEnum[37]!, conjIdToConjEnum[3]!, t, f, 1, 1, 'らなくて'),
	Conjo(posIdToPosEnum[37]!, conjIdToConjEnum[3]!, t, f, 2, 1, 'らないで'),
	Conjo(posIdToPosEnum[37]!, conjIdToConjEnum[3]!, t, t, 1, 1, 'りませんで'),
	Conjo(posIdToPosEnum[37]!, conjIdToConjEnum[4]!, f, f, 1, 1, 'れば'),
	Conjo(posIdToPosEnum[37]!, conjIdToConjEnum[4]!, f, t, 1, 1, 'りますなら'),
	Conjo(posIdToPosEnum[37]!, conjIdToConjEnum[4]!, f, t, 2, 1, 'りますならば'),
	Conjo(posIdToPosEnum[37]!, conjIdToConjEnum[4]!, t, f, 1, 1, 'らなければ'),
	Conjo(posIdToPosEnum[37]!, conjIdToConjEnum[4]!, t, t, 1, 1, 'りませんなら'),
	Conjo(posIdToPosEnum[37]!, conjIdToConjEnum[4]!, t, t, 2, 1, 'りませんならば'),
	Conjo(posIdToPosEnum[37]!, conjIdToConjEnum[5]!, f, f, 1, 1, 'れる'),
	Conjo(posIdToPosEnum[37]!, conjIdToConjEnum[5]!, f, t, 1, 1, 'れます'),
	Conjo(posIdToPosEnum[37]!, conjIdToConjEnum[5]!, t, f, 1, 1, 'れない'),
	Conjo(posIdToPosEnum[37]!, conjIdToConjEnum[5]!, t, t, 1, 1, 'れません'),
	Conjo(posIdToPosEnum[37]!, conjIdToConjEnum[6]!, f, f, 1, 1, 'られる'),
	Conjo(posIdToPosEnum[37]!, conjIdToConjEnum[6]!, f, t, 1, 1, 'られます'),
	Conjo(posIdToPosEnum[37]!, conjIdToConjEnum[6]!, t, f, 1, 1, 'られない'),
	Conjo(posIdToPosEnum[37]!, conjIdToConjEnum[6]!, t, t, 1, 1, 'られません'),
	Conjo(posIdToPosEnum[37]!, conjIdToConjEnum[7]!, f, f, 1, 1, 'らせる'),
	Conjo(posIdToPosEnum[37]!, conjIdToConjEnum[7]!, f, f, 2, 1, 'らす'),
	Conjo(posIdToPosEnum[37]!, conjIdToConjEnum[7]!, f, t, 1, 1, 'らせます'),
	Conjo(posIdToPosEnum[37]!, conjIdToConjEnum[7]!, f, t, 2, 1, 'らします'),
	Conjo(posIdToPosEnum[37]!, conjIdToConjEnum[7]!, t, f, 1, 1, 'らせない'),
	Conjo(posIdToPosEnum[37]!, conjIdToConjEnum[7]!, t, f, 2, 1, 'らさない'),
	Conjo(posIdToPosEnum[37]!, conjIdToConjEnum[7]!, t, t, 1, 1, 'らせません'),
	Conjo(posIdToPosEnum[37]!, conjIdToConjEnum[7]!, t, t, 2, 1, 'らしません'),
	Conjo(posIdToPosEnum[37]!, conjIdToConjEnum[8]!, f, f, 1, 1, 'らせられる'),
	Conjo(posIdToPosEnum[37]!, conjIdToConjEnum[8]!, f, f, 2, 1, 'らされる'),
	Conjo(posIdToPosEnum[37]!, conjIdToConjEnum[8]!, f, t, 1, 1, 'らせられます'),
	Conjo(posIdToPosEnum[37]!, conjIdToConjEnum[8]!, f, t, 2, 1, 'らされます'),
	Conjo(posIdToPosEnum[37]!, conjIdToConjEnum[8]!, t, f, 1, 1, 'らせられない'),
	Conjo(posIdToPosEnum[37]!, conjIdToConjEnum[8]!, t, f, 2, 1, 'らされない'),
	Conjo(posIdToPosEnum[37]!, conjIdToConjEnum[8]!, t, t, 1, 1, 'らせられません'),
	Conjo(posIdToPosEnum[37]!, conjIdToConjEnum[8]!, t, t, 2, 1, 'らされません'),
	Conjo(posIdToPosEnum[37]!, conjIdToConjEnum[9]!, f, f, 1, 1, 'ろう'),
	Conjo(posIdToPosEnum[37]!, conjIdToConjEnum[9]!, f, t, 1, 1, 'りましょう'),
	Conjo(posIdToPosEnum[37]!, conjIdToConjEnum[9]!, t, f, 1, 1, 'るまい'),
	Conjo(posIdToPosEnum[37]!, conjIdToConjEnum[9]!, t, t, 1, 1, 'りませんまい'),
	Conjo(posIdToPosEnum[37]!, conjIdToConjEnum[10]!, f, f, 1, 1, 'れ'),
	Conjo(posIdToPosEnum[37]!, conjIdToConjEnum[10]!, f, t, 1, 1, 'りなさい'),
	Conjo(posIdToPosEnum[37]!, conjIdToConjEnum[10]!, t, f, 1, 1, 'るな'),
	Conjo(posIdToPosEnum[37]!, conjIdToConjEnum[10]!, t, t, 1, 1, 'りなさるな'),
	Conjo(posIdToPosEnum[37]!, conjIdToConjEnum[11]!, f, f, 1, 1, 'ったら'),
	Conjo(posIdToPosEnum[37]!, conjIdToConjEnum[11]!, f, t, 1, 1, 'りましたら'),
	Conjo(posIdToPosEnum[37]!, conjIdToConjEnum[11]!, t, f, 1, 1, 'らなかったら'),
	Conjo(posIdToPosEnum[37]!, conjIdToConjEnum[11]!, t, t, 1, 1, 'りませんでしたら'),
	Conjo(posIdToPosEnum[37]!, conjIdToConjEnum[12]!, f, f, 1, 1, 'ったり'),
	Conjo(posIdToPosEnum[37]!, conjIdToConjEnum[12]!, f, t, 1, 1, 'りましたり'),
	Conjo(posIdToPosEnum[37]!, conjIdToConjEnum[12]!, t, f, 1, 1, 'らなかったり'),
	Conjo(posIdToPosEnum[37]!, conjIdToConjEnum[12]!, t, t, 1, 1, 'りませんでしたり'),
	Conjo(posIdToPosEnum[37]!, conjIdToConjEnum[13]!, f, f, 1, 1, 'り'),
	Conjo(posIdToPosEnum[38]!, conjIdToConjEnum[1]!, f, f, 1, 1, 'る'),
	Conjo(posIdToPosEnum[38]!, conjIdToConjEnum[1]!, f, t, 1, 1, 'ります'),
	Conjo(posIdToPosEnum[38]!, conjIdToConjEnum[1]!, t, f, 1, 2, 'ない'),
	Conjo(posIdToPosEnum[38]!, conjIdToConjEnum[1]!, t, t, 1, 1, 'りません'),
	Conjo(posIdToPosEnum[38]!, conjIdToConjEnum[2]!, f, f, 1, 1, 'った'),
	Conjo(posIdToPosEnum[38]!, conjIdToConjEnum[2]!, f, t, 1, 1, 'りました'),
	Conjo(posIdToPosEnum[38]!, conjIdToConjEnum[2]!, t, f, 1, 2, 'なかった'),
	Conjo(posIdToPosEnum[38]!, conjIdToConjEnum[2]!, t, t, 1, 1, 'りませんでした'),
	Conjo(posIdToPosEnum[38]!, conjIdToConjEnum[3]!, f, f, 1, 1, 'って'),
	Conjo(posIdToPosEnum[38]!, conjIdToConjEnum[3]!, f, t, 1, 1, 'りまして'),
	Conjo(posIdToPosEnum[38]!, conjIdToConjEnum[3]!, t, f, 1, 2, 'なくて'),
	Conjo(posIdToPosEnum[38]!, conjIdToConjEnum[3]!, t, f, 2, 2, 'ないで'),
	Conjo(posIdToPosEnum[38]!, conjIdToConjEnum[3]!, t, t, 1, 1, 'りませんで'),
	Conjo(posIdToPosEnum[38]!, conjIdToConjEnum[4]!, f, f, 1, 1, 'れば'),
	Conjo(posIdToPosEnum[38]!, conjIdToConjEnum[4]!, f, t, 1, 1, 'りますなら'),
	Conjo(posIdToPosEnum[38]!, conjIdToConjEnum[4]!, f, t, 2, 1, 'りますならば'),
	Conjo(posIdToPosEnum[38]!, conjIdToConjEnum[4]!, t, f, 1, 2, 'なければ'),
	Conjo(posIdToPosEnum[38]!, conjIdToConjEnum[4]!, t, t, 1, 1, 'りませんなら'),
	Conjo(posIdToPosEnum[38]!, conjIdToConjEnum[4]!, t, t, 2, 1, 'りませんならば'),
	Conjo(posIdToPosEnum[38]!, conjIdToConjEnum[5]!, f, f, 1, 1, 'れる'),
	Conjo(posIdToPosEnum[38]!, conjIdToConjEnum[5]!, f, t, 1, 1, 'れます'),
	Conjo(posIdToPosEnum[38]!, conjIdToConjEnum[5]!, t, f, 1, 1, 'れない'),
	Conjo(posIdToPosEnum[38]!, conjIdToConjEnum[5]!, t, t, 1, 1, 'れません'),
	Conjo(posIdToPosEnum[38]!, conjIdToConjEnum[6]!, f, f, 1, 1, 'られる'),
	Conjo(posIdToPosEnum[38]!, conjIdToConjEnum[6]!, f, t, 1, 1, 'られます'),
	Conjo(posIdToPosEnum[38]!, conjIdToConjEnum[6]!, t, f, 1, 1, 'られない'),
	Conjo(posIdToPosEnum[38]!, conjIdToConjEnum[6]!, t, t, 1, 1, 'られません'),
	Conjo(posIdToPosEnum[38]!, conjIdToConjEnum[7]!, f, f, 1, 1, 'らせる'),
	Conjo(posIdToPosEnum[38]!, conjIdToConjEnum[7]!, f, f, 2, 1, 'らす'),
	Conjo(posIdToPosEnum[38]!, conjIdToConjEnum[7]!, f, t, 1, 1, 'らせます'),
	Conjo(posIdToPosEnum[38]!, conjIdToConjEnum[7]!, f, t, 2, 1, 'らします'),
	Conjo(posIdToPosEnum[38]!, conjIdToConjEnum[7]!, t, f, 1, 1, 'らせない'),
	Conjo(posIdToPosEnum[38]!, conjIdToConjEnum[7]!, t, f, 2, 1, 'らさない'),
	Conjo(posIdToPosEnum[38]!, conjIdToConjEnum[7]!, t, t, 1, 1, 'らせません'),
	Conjo(posIdToPosEnum[38]!, conjIdToConjEnum[7]!, t, t, 2, 1, 'らしません'),
	Conjo(posIdToPosEnum[38]!, conjIdToConjEnum[8]!, f, f, 1, 1, 'らせられる'),
	Conjo(posIdToPosEnum[38]!, conjIdToConjEnum[8]!, f, f, 2, 1, 'らされる'),
	Conjo(posIdToPosEnum[38]!, conjIdToConjEnum[8]!, f, t, 1, 1, 'らせられます'),
	Conjo(posIdToPosEnum[38]!, conjIdToConjEnum[8]!, f, t, 2, 1, 'らされます'),
	Conjo(posIdToPosEnum[38]!, conjIdToConjEnum[8]!, t, f, 1, 1, 'らせられない'),
	Conjo(posIdToPosEnum[38]!, conjIdToConjEnum[8]!, t, f, 2, 1, 'らされない'),
	Conjo(posIdToPosEnum[38]!, conjIdToConjEnum[8]!, t, t, 1, 1, 'らせられません'),
	Conjo(posIdToPosEnum[38]!, conjIdToConjEnum[8]!, t, t, 2, 1, 'らされません'),
	Conjo(posIdToPosEnum[38]!, conjIdToConjEnum[9]!, f, f, 1, 1, 'ろう'),
	Conjo(posIdToPosEnum[38]!, conjIdToConjEnum[9]!, f, t, 1, 1, 'りましょう'),
	Conjo(posIdToPosEnum[38]!, conjIdToConjEnum[9]!, t, f, 1, 1, 'るまい'),
	Conjo(posIdToPosEnum[38]!, conjIdToConjEnum[9]!, t, t, 1, 1, 'りませんまい'),
	Conjo(posIdToPosEnum[38]!, conjIdToConjEnum[10]!, f, f, 1, 1, 'れ'),
	Conjo(posIdToPosEnum[38]!, conjIdToConjEnum[10]!, f, t, 1, 1, 'りなさい'),
	Conjo(posIdToPosEnum[38]!, conjIdToConjEnum[10]!, t, f, 1, 1, 'るな'),
	Conjo(posIdToPosEnum[38]!, conjIdToConjEnum[10]!, t, t, 1, 1, 'りなさるな'),
	Conjo(posIdToPosEnum[38]!, conjIdToConjEnum[11]!, f, f, 1, 1, 'ったら'),
	Conjo(posIdToPosEnum[38]!, conjIdToConjEnum[11]!, f, t, 1, 1, 'りましたら'),
	Conjo(posIdToPosEnum[38]!, conjIdToConjEnum[11]!, t, f, 1, 2, 'なかったら'),
	Conjo(posIdToPosEnum[38]!, conjIdToConjEnum[11]!, t, t, 1, 1, 'りませんでしたら'),
	Conjo(posIdToPosEnum[38]!, conjIdToConjEnum[12]!, f, f, 1, 1, 'ったり'),
	Conjo(posIdToPosEnum[38]!, conjIdToConjEnum[12]!, f, t, 1, 1, 'りましたり'),
	Conjo(posIdToPosEnum[38]!, conjIdToConjEnum[12]!, t, f, 1, 2, 'なかったり'),
	Conjo(posIdToPosEnum[38]!, conjIdToConjEnum[12]!, t, t, 1, 1, 'りませんでしたり'),
	Conjo(posIdToPosEnum[38]!, conjIdToConjEnum[13]!, f, f, 1, 1, 'り'),
	Conjo(posIdToPosEnum[39]!, conjIdToConjEnum[1]!, f, f, 1, 1, 'す'),
	Conjo(posIdToPosEnum[39]!, conjIdToConjEnum[1]!, f, t, 1, 1, 'します'),
	Conjo(posIdToPosEnum[39]!, conjIdToConjEnum[1]!, t, f, 1, 1, 'さない'),
	Conjo(posIdToPosEnum[39]!, conjIdToConjEnum[1]!, t, t, 1, 1, 'しません'),
	Conjo(posIdToPosEnum[39]!, conjIdToConjEnum[2]!, f, f, 1, 1, 'した'),
	Conjo(posIdToPosEnum[39]!, conjIdToConjEnum[2]!, f, t, 1, 1, 'しました'),
	Conjo(posIdToPosEnum[39]!, conjIdToConjEnum[2]!, t, f, 1, 1, 'さなかった'),
	Conjo(posIdToPosEnum[39]!, conjIdToConjEnum[2]!, t, t, 1, 1, 'しませんでした'),
	Conjo(posIdToPosEnum[39]!, conjIdToConjEnum[3]!, f, f, 1, 1, 'して'),
	Conjo(posIdToPosEnum[39]!, conjIdToConjEnum[3]!, f, t, 1, 1, 'しまして'),
	Conjo(posIdToPosEnum[39]!, conjIdToConjEnum[3]!, t, f, 1, 1, 'さなくて'),
	Conjo(posIdToPosEnum[39]!, conjIdToConjEnum[3]!, t, f, 2, 1, 'さないで'),
	Conjo(posIdToPosEnum[39]!, conjIdToConjEnum[3]!, t, t, 1, 1, 'しませんで'),
	Conjo(posIdToPosEnum[39]!, conjIdToConjEnum[4]!, f, f, 1, 1, 'せば'),
	Conjo(posIdToPosEnum[39]!, conjIdToConjEnum[4]!, f, t, 1, 1, 'しますなら'),
	Conjo(posIdToPosEnum[39]!, conjIdToConjEnum[4]!, f, t, 2, 1, 'しますならば'),
	Conjo(posIdToPosEnum[39]!, conjIdToConjEnum[4]!, t, f, 1, 1, 'さなければ'),
	Conjo(posIdToPosEnum[39]!, conjIdToConjEnum[4]!, t, t, 1, 1, 'しませんなら'),
	Conjo(posIdToPosEnum[39]!, conjIdToConjEnum[4]!, t, t, 2, 1, 'しませんならば'),
	Conjo(posIdToPosEnum[39]!, conjIdToConjEnum[5]!, f, f, 1, 1, 'せる'),
	Conjo(posIdToPosEnum[39]!, conjIdToConjEnum[5]!, f, t, 1, 1, 'せます'),
	Conjo(posIdToPosEnum[39]!, conjIdToConjEnum[5]!, t, f, 1, 1, 'せない'),
	Conjo(posIdToPosEnum[39]!, conjIdToConjEnum[5]!, t, t, 1, 1, 'せません'),
	Conjo(posIdToPosEnum[39]!, conjIdToConjEnum[6]!, f, f, 1, 1, 'される'),
	Conjo(posIdToPosEnum[39]!, conjIdToConjEnum[6]!, f, t, 1, 1, 'されます'),
	Conjo(posIdToPosEnum[39]!, conjIdToConjEnum[6]!, t, f, 1, 1, 'されない'),
	Conjo(posIdToPosEnum[39]!, conjIdToConjEnum[6]!, t, t, 1, 1, 'されません'),
	Conjo(posIdToPosEnum[39]!, conjIdToConjEnum[7]!, f, f, 1, 1, 'させる'),
	Conjo(posIdToPosEnum[39]!, conjIdToConjEnum[7]!, f, f, 2, 1, 'さす'),
	Conjo(posIdToPosEnum[39]!, conjIdToConjEnum[7]!, f, t, 1, 1, 'させます'),
	Conjo(posIdToPosEnum[39]!, conjIdToConjEnum[7]!, f, t, 2, 1, 'さします'),
	Conjo(posIdToPosEnum[39]!, conjIdToConjEnum[7]!, t, f, 1, 1, 'させない'),
	Conjo(posIdToPosEnum[39]!, conjIdToConjEnum[7]!, t, f, 2, 1, 'ささない'),
	Conjo(posIdToPosEnum[39]!, conjIdToConjEnum[7]!, t, t, 1, 1, 'させません'),
	Conjo(posIdToPosEnum[39]!, conjIdToConjEnum[7]!, t, t, 2, 1, 'さしません'),
	Conjo(posIdToPosEnum[39]!, conjIdToConjEnum[8]!, f, f, 1, 1, 'させられる'),
	Conjo(posIdToPosEnum[39]!, conjIdToConjEnum[8]!, f, t, 1, 1, 'させられます'),
	Conjo(posIdToPosEnum[39]!, conjIdToConjEnum[8]!, t, f, 1, 1, 'させられない'),
	Conjo(posIdToPosEnum[39]!, conjIdToConjEnum[8]!, t, t, 1, 1, 'させられません'),
	Conjo(posIdToPosEnum[39]!, conjIdToConjEnum[9]!, f, f, 1, 1, 'そう'),
	Conjo(posIdToPosEnum[39]!, conjIdToConjEnum[9]!, f, t, 1, 1, 'しましょう'),
	Conjo(posIdToPosEnum[39]!, conjIdToConjEnum[9]!, t, f, 1, 1, 'すまい'),
	Conjo(posIdToPosEnum[39]!, conjIdToConjEnum[9]!, t, t, 1, 1, 'しませんまい'),
	Conjo(posIdToPosEnum[39]!, conjIdToConjEnum[10]!, f, f, 1, 1, 'せ'),
	Conjo(posIdToPosEnum[39]!, conjIdToConjEnum[10]!, f, t, 1, 1, 'しなさい'),
	Conjo(posIdToPosEnum[39]!, conjIdToConjEnum[10]!, t, f, 1, 1, 'すな'),
	Conjo(posIdToPosEnum[39]!, conjIdToConjEnum[10]!, t, t, 1, 1, 'しなさるな'),
	Conjo(posIdToPosEnum[39]!, conjIdToConjEnum[11]!, f, f, 1, 1, 'したら'),
	Conjo(posIdToPosEnum[39]!, conjIdToConjEnum[11]!, f, t, 1, 1, 'しましたら'),
	Conjo(posIdToPosEnum[39]!, conjIdToConjEnum[11]!, t, f, 1, 1, 'さなかったら'),
	Conjo(posIdToPosEnum[39]!, conjIdToConjEnum[11]!, t, t, 1, 1, 'しませんでしたら'),
	Conjo(posIdToPosEnum[39]!, conjIdToConjEnum[12]!, f, f, 1, 1, 'したり'),
	Conjo(posIdToPosEnum[39]!, conjIdToConjEnum[12]!, f, t, 1, 1, 'しましたり'),
	Conjo(posIdToPosEnum[39]!, conjIdToConjEnum[12]!, t, f, 1, 1, 'さなかったり'),
	Conjo(posIdToPosEnum[39]!, conjIdToConjEnum[12]!, t, t, 1, 1, 'しませんでしたり'),
	Conjo(posIdToPosEnum[39]!, conjIdToConjEnum[13]!, f, f, 1, 1, 'し'),
	Conjo(posIdToPosEnum[40]!, conjIdToConjEnum[1]!, f, f, 1, 1, 'つ'),
	Conjo(posIdToPosEnum[40]!, conjIdToConjEnum[1]!, f, t, 1, 1, 'ちます'),
	Conjo(posIdToPosEnum[40]!, conjIdToConjEnum[1]!, t, f, 1, 1, 'たない'),
	Conjo(posIdToPosEnum[40]!, conjIdToConjEnum[1]!, t, t, 1, 1, 'ちません'),
	Conjo(posIdToPosEnum[40]!, conjIdToConjEnum[2]!, f, f, 1, 1, 'った'),
	Conjo(posIdToPosEnum[40]!, conjIdToConjEnum[2]!, f, t, 1, 1, 'ちました'),
	Conjo(posIdToPosEnum[40]!, conjIdToConjEnum[2]!, t, f, 1, 1, 'たなかった'),
	Conjo(posIdToPosEnum[40]!, conjIdToConjEnum[2]!, t, t, 1, 1, 'ちませんでした'),
	Conjo(posIdToPosEnum[40]!, conjIdToConjEnum[3]!, f, f, 1, 1, 'って'),
	Conjo(posIdToPosEnum[40]!, conjIdToConjEnum[3]!, f, t, 1, 1, 'ちまして'),
	Conjo(posIdToPosEnum[40]!, conjIdToConjEnum[3]!, t, f, 1, 1, 'たなくて'),
	Conjo(posIdToPosEnum[40]!, conjIdToConjEnum[3]!, t, f, 2, 1, 'たないで'),
	Conjo(posIdToPosEnum[40]!, conjIdToConjEnum[3]!, t, t, 1, 1, 'ちませんで'),
	Conjo(posIdToPosEnum[40]!, conjIdToConjEnum[4]!, f, f, 1, 1, 'てば'),
	Conjo(posIdToPosEnum[40]!, conjIdToConjEnum[4]!, f, t, 1, 1, 'ちますなら'),
	Conjo(posIdToPosEnum[40]!, conjIdToConjEnum[4]!, f, t, 2, 1, 'ちますならば'),
	Conjo(posIdToPosEnum[40]!, conjIdToConjEnum[4]!, t, f, 1, 1, 'たなければ'),
	Conjo(posIdToPosEnum[40]!, conjIdToConjEnum[4]!, t, t, 1, 1, 'ちませんなら'),
	Conjo(posIdToPosEnum[40]!, conjIdToConjEnum[4]!, t, t, 2, 1, 'ちませんならば'),
	Conjo(posIdToPosEnum[40]!, conjIdToConjEnum[5]!, f, f, 1, 1, 'てる'),
	Conjo(posIdToPosEnum[40]!, conjIdToConjEnum[5]!, f, t, 1, 1, 'てます'),
	Conjo(posIdToPosEnum[40]!, conjIdToConjEnum[5]!, t, f, 1, 1, 'てない'),
	Conjo(posIdToPosEnum[40]!, conjIdToConjEnum[5]!, t, t, 1, 1, 'てません'),
	Conjo(posIdToPosEnum[40]!, conjIdToConjEnum[6]!, f, f, 1, 1, 'たれる'),
	Conjo(posIdToPosEnum[40]!, conjIdToConjEnum[6]!, f, t, 1, 1, 'たれます'),
	Conjo(posIdToPosEnum[40]!, conjIdToConjEnum[6]!, t, f, 1, 1, 'たれない'),
	Conjo(posIdToPosEnum[40]!, conjIdToConjEnum[6]!, t, t, 1, 1, 'たれません'),
	Conjo(posIdToPosEnum[40]!, conjIdToConjEnum[7]!, f, f, 1, 1, 'たせる'),
	Conjo(posIdToPosEnum[40]!, conjIdToConjEnum[7]!, f, f, 2, 1, 'たす'),
	Conjo(posIdToPosEnum[40]!, conjIdToConjEnum[7]!, f, t, 1, 1, 'たせます'),
	Conjo(posIdToPosEnum[40]!, conjIdToConjEnum[7]!, f, t, 2, 1, 'たします'),
	Conjo(posIdToPosEnum[40]!, conjIdToConjEnum[7]!, t, f, 1, 1, 'たせない'),
	Conjo(posIdToPosEnum[40]!, conjIdToConjEnum[7]!, t, f, 2, 1, 'たさない'),
	Conjo(posIdToPosEnum[40]!, conjIdToConjEnum[7]!, t, t, 1, 1, 'たせません'),
	Conjo(posIdToPosEnum[40]!, conjIdToConjEnum[7]!, t, t, 2, 1, 'たしません'),
	Conjo(posIdToPosEnum[40]!, conjIdToConjEnum[8]!, f, f, 1, 1, 'たせられる'),
	Conjo(posIdToPosEnum[40]!, conjIdToConjEnum[8]!, f, f, 2, 1, 'たされる'),
	Conjo(posIdToPosEnum[40]!, conjIdToConjEnum[8]!, f, t, 1, 1, 'たせられます'),
	Conjo(posIdToPosEnum[40]!, conjIdToConjEnum[8]!, f, t, 2, 1, 'たされます'),
	Conjo(posIdToPosEnum[40]!, conjIdToConjEnum[8]!, t, f, 1, 1, 'たせられない'),
	Conjo(posIdToPosEnum[40]!, conjIdToConjEnum[8]!, t, f, 2, 1, 'たされない'),
	Conjo(posIdToPosEnum[40]!, conjIdToConjEnum[8]!, t, t, 1, 1, 'たせられません'),
	Conjo(posIdToPosEnum[40]!, conjIdToConjEnum[8]!, t, t, 2, 1, 'たされません'),
	Conjo(posIdToPosEnum[40]!, conjIdToConjEnum[9]!, f, f, 1, 1, 'とう'),
	Conjo(posIdToPosEnum[40]!, conjIdToConjEnum[9]!, f, t, 1, 1, 'ちましょう'),
	Conjo(posIdToPosEnum[40]!, conjIdToConjEnum[9]!, t, f, 1, 1, 'つまい'),
	Conjo(posIdToPosEnum[40]!, conjIdToConjEnum[9]!, t, t, 1, 1, 'ちませんまい'),
	Conjo(posIdToPosEnum[40]!, conjIdToConjEnum[10]!, f, f, 1, 1, 'て'),
	Conjo(posIdToPosEnum[40]!, conjIdToConjEnum[10]!, f, t, 1, 1, 'ちなさい'),
	Conjo(posIdToPosEnum[40]!, conjIdToConjEnum[10]!, t, f, 1, 1, 'つな'),
	Conjo(posIdToPosEnum[40]!, conjIdToConjEnum[10]!, t, t, 1, 1, 'ちなさるな'),
	Conjo(posIdToPosEnum[40]!, conjIdToConjEnum[11]!, f, f, 1, 1, 'ったら'),
	Conjo(posIdToPosEnum[40]!, conjIdToConjEnum[11]!, f, t, 1, 1, 'ちまったら'),
	Conjo(posIdToPosEnum[40]!, conjIdToConjEnum[11]!, t, f, 1, 1, 'たなかったら'),
	Conjo(posIdToPosEnum[40]!, conjIdToConjEnum[11]!, t, t, 1, 1, 'ちませんでしたら'),
	Conjo(posIdToPosEnum[40]!, conjIdToConjEnum[12]!, f, f, 1, 1, 'ったり'),
	Conjo(posIdToPosEnum[40]!, conjIdToConjEnum[12]!, f, t, 1, 1, 'ちましたり'),
	Conjo(posIdToPosEnum[40]!, conjIdToConjEnum[12]!, t, f, 1, 1, 'たなかったり'),
	Conjo(posIdToPosEnum[40]!, conjIdToConjEnum[12]!, t, t, 1, 1, 'ちませんでしたり'),
	Conjo(posIdToPosEnum[40]!, conjIdToConjEnum[13]!, f, f, 1, 1, 'ち'),
	Conjo(posIdToPosEnum[41]!, conjIdToConjEnum[1]!, f, f, 1, 1, 'う'),
	Conjo(posIdToPosEnum[41]!, conjIdToConjEnum[1]!, f, t, 1, 1, 'います'),
	Conjo(posIdToPosEnum[41]!, conjIdToConjEnum[1]!, t, f, 1, 1, 'わない'),
	Conjo(posIdToPosEnum[41]!, conjIdToConjEnum[1]!, t, t, 1, 1, 'いません'),
	Conjo(posIdToPosEnum[41]!, conjIdToConjEnum[2]!, f, f, 1, 1, 'った'),
	Conjo(posIdToPosEnum[41]!, conjIdToConjEnum[2]!, f, t, 1, 1, 'いました'),
	Conjo(posIdToPosEnum[41]!, conjIdToConjEnum[2]!, t, f, 1, 1, 'わなかった'),
	Conjo(posIdToPosEnum[41]!, conjIdToConjEnum[2]!, t, t, 1, 1, 'いませんでした'),
	Conjo(posIdToPosEnum[41]!, conjIdToConjEnum[3]!, f, f, 1, 1, 'って'),
	Conjo(posIdToPosEnum[41]!, conjIdToConjEnum[3]!, f, t, 1, 1, 'いまして'),
	Conjo(posIdToPosEnum[41]!, conjIdToConjEnum[3]!, t, f, 1, 1, 'わなくて'),
	Conjo(posIdToPosEnum[41]!, conjIdToConjEnum[3]!, t, f, 2, 1, 'わないで'),
	Conjo(posIdToPosEnum[41]!, conjIdToConjEnum[3]!, t, t, 1, 1, 'いませんで'),
	Conjo(posIdToPosEnum[41]!, conjIdToConjEnum[4]!, f, f, 1, 1, 'えば'),
	Conjo(posIdToPosEnum[41]!, conjIdToConjEnum[4]!, f, t, 1, 1, 'いますなら'),
	Conjo(posIdToPosEnum[41]!, conjIdToConjEnum[4]!, f, t, 2, 1, 'いますならば'),
	Conjo(posIdToPosEnum[41]!, conjIdToConjEnum[4]!, t, f, 1, 1, 'わなければ'),
	Conjo(posIdToPosEnum[41]!, conjIdToConjEnum[4]!, t, t, 1, 1, 'いませんなら'),
	Conjo(posIdToPosEnum[41]!, conjIdToConjEnum[4]!, t, t, 2, 1, 'いませんならば'),
	Conjo(posIdToPosEnum[41]!, conjIdToConjEnum[5]!, f, f, 1, 1, 'える'),
	Conjo(posIdToPosEnum[41]!, conjIdToConjEnum[5]!, f, t, 1, 1, 'えます'),
	Conjo(posIdToPosEnum[41]!, conjIdToConjEnum[5]!, t, f, 1, 1, 'えない'),
	Conjo(posIdToPosEnum[41]!, conjIdToConjEnum[5]!, t, t, 1, 1, 'えません'),
	Conjo(posIdToPosEnum[41]!, conjIdToConjEnum[6]!, f, f, 1, 1, 'われる'),
	Conjo(posIdToPosEnum[41]!, conjIdToConjEnum[6]!, f, t, 1, 1, 'われます'),
	Conjo(posIdToPosEnum[41]!, conjIdToConjEnum[6]!, t, f, 1, 1, 'われない'),
	Conjo(posIdToPosEnum[41]!, conjIdToConjEnum[6]!, t, t, 1, 1, 'われません'),
	Conjo(posIdToPosEnum[41]!, conjIdToConjEnum[7]!, f, f, 1, 1, 'わせる'),
	Conjo(posIdToPosEnum[41]!, conjIdToConjEnum[7]!, f, f, 2, 1, 'わす'),
	Conjo(posIdToPosEnum[41]!, conjIdToConjEnum[7]!, f, t, 1, 1, 'わせます'),
	Conjo(posIdToPosEnum[41]!, conjIdToConjEnum[7]!, f, t, 2, 1, 'わします'),
	Conjo(posIdToPosEnum[41]!, conjIdToConjEnum[7]!, t, f, 1, 1, 'わせない'),
	Conjo(posIdToPosEnum[41]!, conjIdToConjEnum[7]!, t, f, 2, 1, 'わさない'),
	Conjo(posIdToPosEnum[41]!, conjIdToConjEnum[7]!, t, t, 1, 1, 'わせません'),
	Conjo(posIdToPosEnum[41]!, conjIdToConjEnum[7]!, t, t, 2, 1, 'わしません'),
	Conjo(posIdToPosEnum[41]!, conjIdToConjEnum[8]!, f, f, 1, 1, 'わせられる'),
	Conjo(posIdToPosEnum[41]!, conjIdToConjEnum[8]!, f, f, 2, 1, 'わされる'),
	Conjo(posIdToPosEnum[41]!, conjIdToConjEnum[8]!, f, t, 1, 1, 'わせられます'),
	Conjo(posIdToPosEnum[41]!, conjIdToConjEnum[8]!, f, t, 2, 1, 'わされます'),
	Conjo(posIdToPosEnum[41]!, conjIdToConjEnum[8]!, t, f, 1, 1, 'わせられない'),
	Conjo(posIdToPosEnum[41]!, conjIdToConjEnum[8]!, t, f, 2, 1, 'わされない'),
	Conjo(posIdToPosEnum[41]!, conjIdToConjEnum[8]!, t, t, 1, 1, 'わせられません'),
	Conjo(posIdToPosEnum[41]!, conjIdToConjEnum[8]!, t, t, 2, 1, 'わされません'),
	Conjo(posIdToPosEnum[41]!, conjIdToConjEnum[9]!, f, f, 1, 1, 'おう'),
	Conjo(posIdToPosEnum[41]!, conjIdToConjEnum[9]!, f, t, 1, 1, 'いましょう'),
	Conjo(posIdToPosEnum[41]!, conjIdToConjEnum[9]!, t, f, 1, 1, 'うまい'),
	Conjo(posIdToPosEnum[41]!, conjIdToConjEnum[9]!, t, t, 1, 1, 'いませんまい'),
	Conjo(posIdToPosEnum[41]!, conjIdToConjEnum[10]!, f, f, 1, 1, 'え'),
	Conjo(posIdToPosEnum[41]!, conjIdToConjEnum[10]!, f, t, 1, 1, 'いなさい'),
	Conjo(posIdToPosEnum[41]!, conjIdToConjEnum[10]!, t, f, 1, 1, 'うな'),
	Conjo(posIdToPosEnum[41]!, conjIdToConjEnum[10]!, t, t, 1, 1, 'いなさるな'),
	Conjo(posIdToPosEnum[41]!, conjIdToConjEnum[11]!, f, f, 1, 1, 'ったら'),
	Conjo(posIdToPosEnum[41]!, conjIdToConjEnum[11]!, f, t, 1, 1, 'いましたら'),
	Conjo(posIdToPosEnum[41]!, conjIdToConjEnum[11]!, t, f, 1, 1, 'わかったら'),
	Conjo(posIdToPosEnum[41]!, conjIdToConjEnum[11]!, t, t, 1, 1, 'いませんでしたら'),
	Conjo(posIdToPosEnum[41]!, conjIdToConjEnum[12]!, f, f, 1, 1, 'ったり'),
	Conjo(posIdToPosEnum[41]!, conjIdToConjEnum[12]!, f, t, 1, 1, 'いましたり'),
	Conjo(posIdToPosEnum[41]!, conjIdToConjEnum[12]!, t, f, 1, 1, 'わなかったり'),
	Conjo(posIdToPosEnum[41]!, conjIdToConjEnum[12]!, t, t, 1, 1, 'いませんでしたり'),
	Conjo(posIdToPosEnum[41]!, conjIdToConjEnum[13]!, f, f, 1, 1, 'い'),
	Conjo(posIdToPosEnum[42]!, conjIdToConjEnum[1]!, f, f, 1, 1, 'う'),
	Conjo(posIdToPosEnum[42]!, conjIdToConjEnum[1]!, f, t, 1, 1, 'います'),
	Conjo(posIdToPosEnum[42]!, conjIdToConjEnum[1]!, t, f, 1, 1, 'わない'),
	Conjo(posIdToPosEnum[42]!, conjIdToConjEnum[1]!, t, t, 1, 1, 'いません'),
	Conjo(posIdToPosEnum[42]!, conjIdToConjEnum[2]!, f, f, 1, 1, 'うた'),
	Conjo(posIdToPosEnum[42]!, conjIdToConjEnum[2]!, f, t, 1, 1, 'いました'),
	Conjo(posIdToPosEnum[42]!, conjIdToConjEnum[2]!, t, f, 1, 1, 'わなかった'),
	Conjo(posIdToPosEnum[42]!, conjIdToConjEnum[2]!, t, t, 1, 1, 'いませんでした'),
	Conjo(posIdToPosEnum[42]!, conjIdToConjEnum[3]!, f, f, 1, 1, 'うて'),
	Conjo(posIdToPosEnum[42]!, conjIdToConjEnum[3]!, f, t, 1, 1, 'いまして'),
	Conjo(posIdToPosEnum[42]!, conjIdToConjEnum[3]!, t, f, 1, 1, 'わなくて'),
	Conjo(posIdToPosEnum[42]!, conjIdToConjEnum[3]!, t, f, 2, 1, 'わないで'),
	Conjo(posIdToPosEnum[42]!, conjIdToConjEnum[3]!, t, t, 1, 1, 'いませんで'),
	Conjo(posIdToPosEnum[42]!, conjIdToConjEnum[4]!, f, f, 1, 1, 'えば'),
	Conjo(posIdToPosEnum[42]!, conjIdToConjEnum[4]!, f, t, 1, 1, 'いますなら'),
	Conjo(posIdToPosEnum[42]!, conjIdToConjEnum[4]!, f, t, 2, 1, 'いますならば'),
	Conjo(posIdToPosEnum[42]!, conjIdToConjEnum[4]!, t, f, 1, 1, 'わなければ'),
	Conjo(posIdToPosEnum[42]!, conjIdToConjEnum[4]!, t, t, 1, 1, 'いませんなら'),
	Conjo(posIdToPosEnum[42]!, conjIdToConjEnum[4]!, t, t, 2, 1, 'いませんならば'),
	Conjo(posIdToPosEnum[42]!, conjIdToConjEnum[5]!, f, f, 1, 1, 'える'),
	Conjo(posIdToPosEnum[42]!, conjIdToConjEnum[5]!, f, t, 1, 1, 'えます'),
	Conjo(posIdToPosEnum[42]!, conjIdToConjEnum[5]!, t, f, 1, 1, 'えない'),
	Conjo(posIdToPosEnum[42]!, conjIdToConjEnum[5]!, t, t, 1, 1, 'えません'),
	Conjo(posIdToPosEnum[42]!, conjIdToConjEnum[6]!, f, f, 1, 1, 'われる'),
	Conjo(posIdToPosEnum[42]!, conjIdToConjEnum[6]!, f, t, 1, 1, 'われます'),
	Conjo(posIdToPosEnum[42]!, conjIdToConjEnum[6]!, t, f, 1, 1, 'われない'),
	Conjo(posIdToPosEnum[42]!, conjIdToConjEnum[6]!, t, t, 1, 1, 'われません'),
	Conjo(posIdToPosEnum[42]!, conjIdToConjEnum[7]!, f, f, 1, 1, 'わせる'),
	Conjo(posIdToPosEnum[42]!, conjIdToConjEnum[7]!, f, f, 2, 1, 'わす'),
	Conjo(posIdToPosEnum[42]!, conjIdToConjEnum[7]!, f, t, 1, 1, 'わせます'),
	Conjo(posIdToPosEnum[42]!, conjIdToConjEnum[7]!, f, t, 2, 1, 'わします'),
	Conjo(posIdToPosEnum[42]!, conjIdToConjEnum[7]!, t, f, 1, 1, 'わせない'),
	Conjo(posIdToPosEnum[42]!, conjIdToConjEnum[7]!, t, f, 2, 1, 'わさない'),
	Conjo(posIdToPosEnum[42]!, conjIdToConjEnum[7]!, t, t, 1, 1, 'わせません'),
	Conjo(posIdToPosEnum[42]!, conjIdToConjEnum[7]!, t, t, 2, 1, 'わしません'),
	Conjo(posIdToPosEnum[42]!, conjIdToConjEnum[8]!, f, f, 1, 1, 'わせられる'),
	Conjo(posIdToPosEnum[42]!, conjIdToConjEnum[8]!, f, f, 2, 1, 'わされる'),
	Conjo(posIdToPosEnum[42]!, conjIdToConjEnum[8]!, f, t, 1, 1, 'わせられます'),
	Conjo(posIdToPosEnum[42]!, conjIdToConjEnum[8]!, f, t, 2, 1, 'わされます'),
	Conjo(posIdToPosEnum[42]!, conjIdToConjEnum[8]!, t, f, 1, 1, 'わせられない'),
	Conjo(posIdToPosEnum[42]!, conjIdToConjEnum[8]!, t, f, 2, 1, 'わされない'),
	Conjo(posIdToPosEnum[42]!, conjIdToConjEnum[8]!, t, t, 1, 1, 'わせられません'),
	Conjo(posIdToPosEnum[42]!, conjIdToConjEnum[8]!, t, t, 2, 1, 'わされません'),
	Conjo(posIdToPosEnum[42]!, conjIdToConjEnum[9]!, f, f, 1, 1, 'おう'),
	Conjo(posIdToPosEnum[42]!, conjIdToConjEnum[9]!, f, t, 1, 1, 'いましょう'),
	Conjo(posIdToPosEnum[42]!, conjIdToConjEnum[9]!, t, f, 1, 1, 'うまい'),
	Conjo(posIdToPosEnum[42]!, conjIdToConjEnum[9]!, t, t, 1, 1, 'いませんまい'),
	Conjo(posIdToPosEnum[42]!, conjIdToConjEnum[10]!, f, f, 1, 1, 'え'),
	Conjo(posIdToPosEnum[42]!, conjIdToConjEnum[10]!, f, t, 1, 1, 'いなさい'),
	Conjo(posIdToPosEnum[42]!, conjIdToConjEnum[10]!, t, f, 1, 1, 'うな'),
	Conjo(posIdToPosEnum[42]!, conjIdToConjEnum[10]!, t, t, 1, 1, 'いなさるな'),
	Conjo(posIdToPosEnum[42]!, conjIdToConjEnum[11]!, f, f, 1, 1, 'うたら'),
	Conjo(posIdToPosEnum[42]!, conjIdToConjEnum[11]!, f, t, 1, 1, 'いましたら'),
	Conjo(posIdToPosEnum[42]!, conjIdToConjEnum[11]!, t, f, 1, 1, 'わなかったら'),
	Conjo(posIdToPosEnum[42]!, conjIdToConjEnum[11]!, t, t, 1, 1, 'いませんでしたら'),
	Conjo(posIdToPosEnum[42]!, conjIdToConjEnum[12]!, f, f, 1, 1, 'うたり'),
	Conjo(posIdToPosEnum[42]!, conjIdToConjEnum[12]!, f, t, 1, 1, 'いましたり'),
	Conjo(posIdToPosEnum[42]!, conjIdToConjEnum[12]!, t, f, 1, 1, 'わなかったり'),
	Conjo(posIdToPosEnum[42]!, conjIdToConjEnum[12]!, t, t, 1, 1, 'いませんでしたり'),
	Conjo(posIdToPosEnum[42]!, conjIdToConjEnum[13]!, f, f, 1, 1, 'い'),
	Conjo(posIdToPosEnum[45]!, conjIdToConjEnum[1]!, f, f, 1, 1, 'る', euphr: 'く'),
	Conjo(posIdToPosEnum[45]!, conjIdToConjEnum[1]!, f, t, 1, 1, 'ます', euphr: 'き'),
	Conjo(posIdToPosEnum[45]!, conjIdToConjEnum[1]!, t, f, 1, 1, 'ない', euphr: 'こ'),
	Conjo(posIdToPosEnum[45]!, conjIdToConjEnum[1]!, t, t, 1, 1, 'ません', euphr: 'き'),
	Conjo(posIdToPosEnum[45]!, conjIdToConjEnum[2]!, f, f, 1, 1, 'た', euphr: 'き'),
	Conjo(posIdToPosEnum[45]!, conjIdToConjEnum[2]!, f, t, 1, 1, 'ました', euphr: 'き'),
	Conjo(posIdToPosEnum[45]!, conjIdToConjEnum[2]!, t, f, 1, 1, 'なかった', euphr: 'こ'),
	Conjo(posIdToPosEnum[45]!, conjIdToConjEnum[2]!, t, t, 1, 1, 'ませんでした', euphr: 'き'),
	Conjo(posIdToPosEnum[45]!, conjIdToConjEnum[3]!, f, f, 1, 1, 'て', euphr: 'き'),
	Conjo(posIdToPosEnum[45]!, conjIdToConjEnum[3]!, f, t, 1, 1, 'まして', euphr: 'き'),
	Conjo(posIdToPosEnum[45]!, conjIdToConjEnum[3]!, t, f, 1, 1, 'なくて', euphr: 'こ'),
	Conjo(posIdToPosEnum[45]!, conjIdToConjEnum[3]!, t, f, 2, 1, 'ないで', euphr: 'こ'),
	Conjo(posIdToPosEnum[45]!, conjIdToConjEnum[3]!, t, t, 1, 1, 'ませんで', euphr: 'き'),
	Conjo(posIdToPosEnum[45]!, conjIdToConjEnum[4]!, f, f, 1, 1, 'れば', euphr: 'く'),
	Conjo(posIdToPosEnum[45]!, conjIdToConjEnum[4]!, f, t, 1, 1, 'ますなら', euphr: 'く'),
	Conjo(posIdToPosEnum[45]!, conjIdToConjEnum[4]!, f, t, 2, 1, 'ますならば', euphr: 'く'),
	Conjo(posIdToPosEnum[45]!, conjIdToConjEnum[4]!, t, f, 1, 1, 'なければ', euphr: 'く'),
	Conjo(posIdToPosEnum[45]!, conjIdToConjEnum[4]!, t, t, 1, 1, 'ませんなら', euphr: 'く'),
	Conjo(posIdToPosEnum[45]!, conjIdToConjEnum[4]!, t, t, 2, 1, 'ませんならば', euphr: 'く'),
	Conjo(posIdToPosEnum[45]!, conjIdToConjEnum[5]!, f, f, 1, 1, 'られる', euphr: 'こ'),
	Conjo(posIdToPosEnum[45]!, conjIdToConjEnum[5]!, f, f, 2, 1, 'れる', euphr: 'こ'),
	Conjo(posIdToPosEnum[45]!, conjIdToConjEnum[5]!, f, t, 1, 1, 'られます', euphr: 'こ'),
	Conjo(posIdToPosEnum[45]!, conjIdToConjEnum[5]!, f, t, 2, 1, 'れます', euphr: 'こ'),
	Conjo(posIdToPosEnum[45]!, conjIdToConjEnum[5]!, t, f, 1, 1, 'られない', euphr: 'こ'),
	Conjo(posIdToPosEnum[45]!, conjIdToConjEnum[5]!, t, f, 2, 1, 'れない', euphr: 'こ'),
	Conjo(posIdToPosEnum[45]!, conjIdToConjEnum[5]!, t, t, 1, 1, 'られません', euphr: 'こ'),
	Conjo(posIdToPosEnum[45]!, conjIdToConjEnum[5]!, t, t, 2, 1, 'れません', euphr: 'こ'),
	Conjo(posIdToPosEnum[45]!, conjIdToConjEnum[6]!, f, f, 1, 1, 'られる', euphr: 'こ'),
	Conjo(posIdToPosEnum[45]!, conjIdToConjEnum[6]!, f, t, 1, 1, 'られます', euphr: 'こ'),
	Conjo(posIdToPosEnum[45]!, conjIdToConjEnum[6]!, t, f, 1, 1, 'られない', euphr: 'こ'),
	Conjo(posIdToPosEnum[45]!, conjIdToConjEnum[6]!, t, t, 1, 1, 'られません', euphr: 'こ'),
	Conjo(posIdToPosEnum[45]!, conjIdToConjEnum[7]!, f, f, 1, 1, 'させる', euphr: 'こ'),
	Conjo(posIdToPosEnum[45]!, conjIdToConjEnum[7]!, f, f, 2, 1, 'さす', euphr: 'こ'),
	Conjo(posIdToPosEnum[45]!, conjIdToConjEnum[7]!, f, t, 1, 1, 'させます', euphr: 'こ'),
	Conjo(posIdToPosEnum[45]!, conjIdToConjEnum[7]!, f, t, 2, 1, 'さします', euphr: 'こ'),
	Conjo(posIdToPosEnum[45]!, conjIdToConjEnum[7]!, t, f, 1, 1, 'させない', euphr: 'こ'),
	Conjo(posIdToPosEnum[45]!, conjIdToConjEnum[7]!, t, f, 2, 1, 'ささない', euphr: 'こ'),
	Conjo(posIdToPosEnum[45]!, conjIdToConjEnum[7]!, t, t, 1, 1, 'させません', euphr: 'こ'),
	Conjo(posIdToPosEnum[45]!, conjIdToConjEnum[7]!, t, t, 2, 1, 'さしません', euphr: 'こ'),
	Conjo(posIdToPosEnum[45]!, conjIdToConjEnum[8]!, f, f, 1, 1, 'させられる', euphr: 'こ'),
	Conjo(posIdToPosEnum[45]!, conjIdToConjEnum[8]!, f, t, 1, 1, 'させられます', euphr: 'こ'),
	Conjo(posIdToPosEnum[45]!, conjIdToConjEnum[8]!, t, f, 1, 1, 'させられない', euphr: 'こ'),
	Conjo(posIdToPosEnum[45]!, conjIdToConjEnum[8]!, t, t, 1, 1, 'させられません', euphr: 'こ'),
	Conjo(posIdToPosEnum[45]!, conjIdToConjEnum[9]!, f, f, 1, 1, 'よう', euphr: 'こ'),
	Conjo(posIdToPosEnum[45]!, conjIdToConjEnum[9]!, f, t, 1, 1, 'ましょう', euphr: 'き'),
	Conjo(posIdToPosEnum[45]!, conjIdToConjEnum[9]!, t, f, 1, 1, 'まい', euphr: 'こ'),
	Conjo(posIdToPosEnum[45]!, conjIdToConjEnum[9]!, t, t, 1, 1, 'ますまい', euphr: 'き'),
	Conjo(posIdToPosEnum[45]!, conjIdToConjEnum[10]!, f, f, 1, 1, 'い', euphr: 'こ'),
	Conjo(posIdToPosEnum[45]!, conjIdToConjEnum[10]!, f, t, 1, 1, 'なさい', euphr: 'こ'),
	Conjo(posIdToPosEnum[45]!, conjIdToConjEnum[10]!, t, f, 1, 1, 'るな', euphr: 'く'),
	Conjo(posIdToPosEnum[45]!, conjIdToConjEnum[10]!, t, t, 1, 1, 'なさるな', euphr: 'こ'),
	Conjo(posIdToPosEnum[45]!, conjIdToConjEnum[11]!, f, f, 1, 1, 'たら', euphr: 'き'),
	Conjo(posIdToPosEnum[45]!, conjIdToConjEnum[11]!, f, t, 1, 1, 'ましたら', euphr: 'き'),
	Conjo(posIdToPosEnum[45]!, conjIdToConjEnum[11]!, t, f, 1, 1, 'なかったら', euphr: 'こ'),
	Conjo(posIdToPosEnum[45]!, conjIdToConjEnum[11]!, t, t, 1, 1, 'ませんでしたら', euphr: 'き'),
	Conjo(posIdToPosEnum[45]!, conjIdToConjEnum[12]!, f, f, 1, 1, 'たり', euphr: 'き'),
	Conjo(posIdToPosEnum[45]!, conjIdToConjEnum[12]!, f, t, 1, 1, 'ましたり', euphr: 'き'),
	Conjo(posIdToPosEnum[45]!, conjIdToConjEnum[12]!, t, f, 1, 1, 'なかったり', euphr: 'こ'),
	Conjo(posIdToPosEnum[45]!, conjIdToConjEnum[12]!, t, t, 1, 1, 'ませんでしたり', euphr: 'き'),
	Conjo(posIdToPosEnum[45]!, conjIdToConjEnum[13]!, f, f, 1, 1, '""', euphr: 'き'),
	Conjo(posIdToPosEnum[46]!, conjIdToConjEnum[1]!, f, f, 1, 0, 'する'),
	Conjo(posIdToPosEnum[47]!, conjIdToConjEnum[1]!, f, f, 1, 1, 'る', euphr: 'す'),
	Conjo(posIdToPosEnum[47]!, conjIdToConjEnum[1]!, f, t, 1, 1, 'ます', euphr: 'し'),
	Conjo(posIdToPosEnum[47]!, conjIdToConjEnum[1]!, t, f, 1, 1, 'ない', euphr: 'さ'),
	Conjo(posIdToPosEnum[47]!, conjIdToConjEnum[1]!, t, t, 1, 1, 'ません', euphr: 'し'),
	Conjo(posIdToPosEnum[47]!, conjIdToConjEnum[2]!, f, f, 1, 1, 'た', euphr: 'し'),
	Conjo(posIdToPosEnum[47]!, conjIdToConjEnum[2]!, f, t, 1, 1, 'ました', euphr: 'し'),
	Conjo(posIdToPosEnum[47]!, conjIdToConjEnum[2]!, t, f, 1, 1, 'なかった', euphr: 'さ'),
	Conjo(posIdToPosEnum[47]!, conjIdToConjEnum[2]!, t, t, 1, 1, 'ませんでした', euphr: 'し'),
	Conjo(posIdToPosEnum[47]!, conjIdToConjEnum[3]!, f, f, 1, 1, 'て', euphr: 'し'),
	Conjo(posIdToPosEnum[47]!, conjIdToConjEnum[3]!, f, t, 1, 1, 'まして', euphr: 'し'),
	Conjo(posIdToPosEnum[47]!, conjIdToConjEnum[3]!, t, f, 1, 1, 'なくて', euphr: 'さ'),
	Conjo(posIdToPosEnum[47]!, conjIdToConjEnum[3]!, t, f, 2, 1, 'ないで', euphr: 'し'),
	Conjo(posIdToPosEnum[47]!, conjIdToConjEnum[3]!, t, t, 1, 1, 'ませんで', euphr: 'し'),
	Conjo(posIdToPosEnum[47]!, conjIdToConjEnum[4]!, f, f, 1, 1, 'れば', euphr: 'す'),
	Conjo(posIdToPosEnum[47]!, conjIdToConjEnum[4]!, f, t, 1, 1, 'ますなら', euphr: 'し'),
	Conjo(posIdToPosEnum[47]!, conjIdToConjEnum[4]!, f, t, 2, 1, 'ますなれば', euphr: 'し'),
	Conjo(posIdToPosEnum[47]!, conjIdToConjEnum[4]!, t, f, 1, 1, 'なければ', euphr: 'さ'),
	Conjo(posIdToPosEnum[47]!, conjIdToConjEnum[4]!, t, t, 1, 1, 'ませんなら', euphr: 'し'),
	Conjo(posIdToPosEnum[47]!, conjIdToConjEnum[4]!, t, t, 2, 1, 'ませんならば', euphr: 'し'),
	Conjo(posIdToPosEnum[47]!, conjIdToConjEnum[5]!, f, f, 1, 1, 'る', euphr: 'しえ'),
	Conjo(posIdToPosEnum[47]!, conjIdToConjEnum[5]!, f, f, 2, 1, 'る', euphr: 'しう'),
	Conjo(posIdToPosEnum[47]!, conjIdToConjEnum[5]!, f, t, 1, 1, 'ます', euphr: 'しえ'),
	Conjo(posIdToPosEnum[47]!, conjIdToConjEnum[5]!, t, f, 1, 1, 'ない', euphr: 'しえ'),
	Conjo(posIdToPosEnum[47]!, conjIdToConjEnum[5]!, t, t, 1, 1, 'ません', euphr: 'しえ'),
	Conjo(posIdToPosEnum[47]!, conjIdToConjEnum[6]!, f, f, 1, 1, 'れる', euphr: 'さ'),
	Conjo(posIdToPosEnum[47]!, conjIdToConjEnum[6]!, f, t, 1, 1, 'れます', euphr: 'さ'),
	Conjo(posIdToPosEnum[47]!, conjIdToConjEnum[6]!, t, f, 1, 1, 'れない', euphr: 'さ'),
	Conjo(posIdToPosEnum[47]!, conjIdToConjEnum[6]!, t, t, 1, 1, 'れません', euphr: 'さ'),
	Conjo(posIdToPosEnum[47]!, conjIdToConjEnum[7]!, f, f, 1, 1, 'せる', euphr: 'さ'),
	Conjo(posIdToPosEnum[47]!, conjIdToConjEnum[7]!, f, f, 2, 1, 'す', euphr: 'さ'),
	Conjo(posIdToPosEnum[47]!, conjIdToConjEnum[7]!, f, t, 1, 1, 'せます', euphr: 'さ'),
	Conjo(posIdToPosEnum[47]!, conjIdToConjEnum[7]!, f, t, 2, 1, 'します', euphr: 'さ'),
	Conjo(posIdToPosEnum[47]!, conjIdToConjEnum[7]!, t, f, 1, 1, 'せない', euphr: 'さ'),
	Conjo(posIdToPosEnum[47]!, conjIdToConjEnum[7]!, t, f, 2, 1, 'さない', euphr: 'さ'),
	Conjo(posIdToPosEnum[47]!, conjIdToConjEnum[7]!, t, t, 1, 1, 'せません', euphr: 'さ'),
	Conjo(posIdToPosEnum[47]!, conjIdToConjEnum[7]!, t, t, 2, 1, 'しません', euphr: 'さ'),
	Conjo(posIdToPosEnum[47]!, conjIdToConjEnum[8]!, f, f, 1, 1, 'せられる', euphr: 'さ'),
	Conjo(posIdToPosEnum[47]!, conjIdToConjEnum[8]!, f, t, 1, 1, 'せられます', euphr: 'さ'),
	Conjo(posIdToPosEnum[47]!, conjIdToConjEnum[8]!, t, f, 1, 1, 'せられない', euphr: 'さ'),
	Conjo(posIdToPosEnum[47]!, conjIdToConjEnum[8]!, t, t, 1, 1, 'せられません', euphr: 'さ'),
	Conjo(posIdToPosEnum[47]!, conjIdToConjEnum[9]!, f, f, 1, 1, 'よう', euphr: 'し'),
	Conjo(posIdToPosEnum[47]!, conjIdToConjEnum[9]!, f, t, 1, 1, 'ましょう', euphr: 'し'),
	Conjo(posIdToPosEnum[47]!, conjIdToConjEnum[9]!, t, f, 1, 1, 'るまい', euphr: 'す'),
	Conjo(posIdToPosEnum[47]!, conjIdToConjEnum[9]!, t, t, 1, 1, 'ますまい', euphr: 'し'),
	Conjo(posIdToPosEnum[47]!, conjIdToConjEnum[10]!, f, f, 1, 1, 'ろ', euphr: 'し'),
	Conjo(posIdToPosEnum[47]!, conjIdToConjEnum[10]!, f, f, 2, 1, 'よ', euphr: 'せ'),
	Conjo(posIdToPosEnum[47]!, conjIdToConjEnum[10]!, f, t, 1, 1, 'なさい', euphr: 'し'),
	Conjo(posIdToPosEnum[47]!, conjIdToConjEnum[10]!, t, f, 1, 1, 'るな', euphr: 'す'),
	Conjo(posIdToPosEnum[47]!, conjIdToConjEnum[10]!, t, t, 1, 1, 'なさるな', euphr: 'し'),
	Conjo(posIdToPosEnum[47]!, conjIdToConjEnum[11]!, f, f, 1, 1, 'たら', euphr: 'し'),
	Conjo(posIdToPosEnum[47]!, conjIdToConjEnum[11]!, f, t, 1, 1, 'ましたら', euphr: 'し'),
	Conjo(posIdToPosEnum[47]!, conjIdToConjEnum[11]!, t, f, 1, 1, 'なかったら', euphr: 'さ'),
	Conjo(posIdToPosEnum[47]!, conjIdToConjEnum[11]!, t, t, 1, 1, 'ませんでしたら', euphr: 'し'),
	Conjo(posIdToPosEnum[47]!, conjIdToConjEnum[12]!, f, f, 1, 1, 'たり', euphr: 'し'),
	Conjo(posIdToPosEnum[47]!, conjIdToConjEnum[12]!, f, t, 1, 1, 'ましたり', euphr: 'し'),
	Conjo(posIdToPosEnum[47]!, conjIdToConjEnum[12]!, t, f, 1, 1, 'なかったり', euphr: 'さ'),
	Conjo(posIdToPosEnum[47]!, conjIdToConjEnum[12]!, t, t, 1, 1, 'ませんでしたり', euphr: 'し'),
	Conjo(posIdToPosEnum[47]!, conjIdToConjEnum[13]!, f, f, 1, 1, '""', euphr: 'し'),
	Conjo(posIdToPosEnum[48]!, conjIdToConjEnum[1]!, f, f, 1, 1, 'る', euphr: 'す'),
	Conjo(posIdToPosEnum[48]!, conjIdToConjEnum[1]!, f, t, 1, 1, 'ます', euphr: 'し'),
	Conjo(posIdToPosEnum[48]!, conjIdToConjEnum[1]!, t, f, 1, 1, 'ない', euphr: 'し'),
	Conjo(posIdToPosEnum[48]!, conjIdToConjEnum[1]!, t, t, 1, 1, 'ません', euphr: 'し'),
	Conjo(posIdToPosEnum[48]!, conjIdToConjEnum[2]!, f, f, 1, 1, 'た', euphr: 'し'),
	Conjo(posIdToPosEnum[48]!, conjIdToConjEnum[2]!, f, t, 1, 1, 'ました', euphr: 'し'),
	Conjo(posIdToPosEnum[48]!, conjIdToConjEnum[2]!, t, f, 1, 1, 'なかった', euphr: 'し'),
	Conjo(posIdToPosEnum[48]!, conjIdToConjEnum[2]!, t, t, 1, 1, 'ませんでした', euphr: 'し'),
	Conjo(posIdToPosEnum[48]!, conjIdToConjEnum[3]!, f, f, 1, 1, 'て', euphr: 'し'),
	Conjo(posIdToPosEnum[48]!, conjIdToConjEnum[3]!, f, t, 1, 1, 'まして', euphr: 'し'),
	Conjo(posIdToPosEnum[48]!, conjIdToConjEnum[3]!, t, f, 1, 1, 'なくて', euphr: 'し'),
	Conjo(posIdToPosEnum[48]!, conjIdToConjEnum[3]!, t, f, 2, 1, 'ないで', euphr: 'し'),
	Conjo(posIdToPosEnum[48]!, conjIdToConjEnum[3]!, t, t, 1, 1, 'ませんで', euphr: 'し'),
	Conjo(posIdToPosEnum[48]!, conjIdToConjEnum[4]!, f, f, 1, 1, 'れば', euphr: 'す'),
	Conjo(posIdToPosEnum[48]!, conjIdToConjEnum[4]!, f, t, 1, 1, 'ますなら', euphr: 'し'),
	Conjo(posIdToPosEnum[48]!, conjIdToConjEnum[4]!, f, t, 2, 1, 'ますなれば', euphr: 'し'),
	Conjo(posIdToPosEnum[48]!, conjIdToConjEnum[4]!, t, f, 1, 1, 'なければ', euphr: 'し'),
	Conjo(posIdToPosEnum[48]!, conjIdToConjEnum[4]!, t, t, 1, 1, 'ませんなら', euphr: 'し'),
	Conjo(posIdToPosEnum[48]!, conjIdToConjEnum[4]!, t, t, 2, 1, 'ませんならば', euphr: 'し'),
	Conjo(posIdToPosEnum[48]!, conjIdToConjEnum[5]!, f, f, 1, 1, 'る', euphr: 'でき', euphk: '出来'),
	Conjo(posIdToPosEnum[48]!, conjIdToConjEnum[5]!, f, t, 1, 1, 'ます', euphr: 'でき', euphk: '出来'),
	Conjo(posIdToPosEnum[48]!, conjIdToConjEnum[5]!, t, f, 1, 1, 'ない', euphr: 'でき', euphk: '出来'),
	Conjo(posIdToPosEnum[48]!, conjIdToConjEnum[5]!, t, t, 1, 1, 'ません', euphr: 'でき', euphk: '出来'),
	Conjo(posIdToPosEnum[48]!, conjIdToConjEnum[6]!, f, f, 1, 1, 'れる', euphr: 'さ'),
	Conjo(posIdToPosEnum[48]!, conjIdToConjEnum[6]!, f, t, 1, 1, 'れます', euphr: 'さ'),
	Conjo(posIdToPosEnum[48]!, conjIdToConjEnum[6]!, t, f, 1, 1, 'れない', euphr: 'さ'),
	Conjo(posIdToPosEnum[48]!, conjIdToConjEnum[6]!, t, t, 1, 1, 'れません', euphr: 'さ'),
	Conjo(posIdToPosEnum[48]!, conjIdToConjEnum[7]!, f, f, 1, 1, 'せる', euphr: 'さ'),
	Conjo(posIdToPosEnum[48]!, conjIdToConjEnum[7]!, f, f, 2, 1, 'す', euphr: 'さ'),
	Conjo(posIdToPosEnum[48]!, conjIdToConjEnum[7]!, f, t, 1, 1, 'せます', euphr: 'さ'),
	Conjo(posIdToPosEnum[48]!, conjIdToConjEnum[7]!, f, t, 2, 1, 'します', euphr: 'さ'),
	Conjo(posIdToPosEnum[48]!, conjIdToConjEnum[7]!, t, f, 1, 1, 'せない', euphr: 'さ'),
	Conjo(posIdToPosEnum[48]!, conjIdToConjEnum[7]!, t, f, 2, 1, 'さない', euphr: 'さ'),
	Conjo(posIdToPosEnum[48]!, conjIdToConjEnum[7]!, t, t, 1, 1, 'せません', euphr: 'さ'),
	Conjo(posIdToPosEnum[48]!, conjIdToConjEnum[7]!, t, t, 2, 1, 'しません', euphr: 'さ'),
	Conjo(posIdToPosEnum[48]!, conjIdToConjEnum[8]!, f, f, 1, 1, 'せられる', euphr: 'さ'),
	Conjo(posIdToPosEnum[48]!, conjIdToConjEnum[8]!, f, t, 1, 1, 'せられます', euphr: 'さ'),
	Conjo(posIdToPosEnum[48]!, conjIdToConjEnum[8]!, t, f, 1, 1, 'せられない', euphr: 'さ'),
	Conjo(posIdToPosEnum[48]!, conjIdToConjEnum[8]!, t, t, 1, 1, 'せられません', euphr: 'さ'),
	Conjo(posIdToPosEnum[48]!, conjIdToConjEnum[9]!, f, f, 1, 1, 'よう', euphr: 'し'),
	Conjo(posIdToPosEnum[48]!, conjIdToConjEnum[9]!, f, t, 1, 1, 'ましょう', euphr: 'し'),
	Conjo(posIdToPosEnum[48]!, conjIdToConjEnum[9]!, t, f, 1, 1, 'るまい', euphr: 'す'),
	Conjo(posIdToPosEnum[48]!, conjIdToConjEnum[9]!, t, t, 1, 1, 'ますまい', euphr: 'し'),
	Conjo(posIdToPosEnum[48]!, conjIdToConjEnum[10]!, f, f, 1, 1, 'ろ', euphr: 'し'),
	Conjo(posIdToPosEnum[48]!, conjIdToConjEnum[10]!, f, f, 2, 1, 'よ', euphr: 'せ'),
	Conjo(posIdToPosEnum[48]!, conjIdToConjEnum[10]!, f, t, 1, 1, 'なさい', euphr: 'し'),
	Conjo(posIdToPosEnum[48]!, conjIdToConjEnum[10]!, t, f, 1, 1, 'るな', euphr: 'す'),
	Conjo(posIdToPosEnum[48]!, conjIdToConjEnum[10]!, t, t, 1, 1, 'なさるな', euphr: 'し'),
	Conjo(posIdToPosEnum[48]!, conjIdToConjEnum[11]!, f, f, 1, 1, 'たら', euphr: 'し'),
	Conjo(posIdToPosEnum[48]!, conjIdToConjEnum[11]!, f, t, 1, 1, 'ましたら', euphr: 'し'),
	Conjo(posIdToPosEnum[48]!, conjIdToConjEnum[11]!, t, f, 1, 1, 'なかったら', euphr: 'し'),
	Conjo(posIdToPosEnum[48]!, conjIdToConjEnum[11]!, t, t, 1, 1, 'ませんでしたら', euphr: 'し'),
	Conjo(posIdToPosEnum[48]!, conjIdToConjEnum[12]!, f, f, 1, 1, 'たり', euphr: 'し'),
	Conjo(posIdToPosEnum[48]!, conjIdToConjEnum[12]!, f, t, 1, 1, 'ましたり', euphr: 'し'),
	Conjo(posIdToPosEnum[48]!, conjIdToConjEnum[12]!, t, f, 1, 1, 'なかったり', euphr: 'し'),
	Conjo(posIdToPosEnum[48]!, conjIdToConjEnum[12]!, t, t, 1, 1, 'ませんでしたり', euphr: 'し'),
	Conjo(posIdToPosEnum[48]!, conjIdToConjEnum[13]!, f, f, 1, 1, '""', euphr: 'し'),
];