//based on kwpos.csv which was scraped from
//https://gitlab.com/yamagoya/jmdictdb/-/tree/master/jmdictdb/data



/// An enum containing the pos tags to identify pos elements
enum Pos {
	adj_i,
	adj_na,
	adj_no,
	adj_pn,
	adj_t,
	adv,
	adj_ix,
	adv_to,
	aux,
	aux_adj,
	aux_v,
	conj,
	exp,
	int,
	cop,
	n,
	n_adv,
	n_suf,
	n_pref,
	n_t,
	num,
	pref,
	prt,
	suf,
	v1,
	v1_s,
	v5aru,
	v5b,
	v5g,
	v5k,
	v5k_s,
	v5m,
	v5n,
	v5r,
	v5r_i,
	v5s,
	v5t,
	v5u,
	v5u_s,
	v5uru,
	vi,
	vk,
	vs,
	vs_s,
	vs_i,
	vz,
	vt,
	ctr,
	vn,
	v4r,
	adj_f,
	vr,
	v2a_s,
	v4h,
	pn,
	vs_c,
	adj_kari,
	adj_ku,
	adj_shiku,
	adj_nari,
	n_pr,
	v_unspec,
	v4k,
	v4g,
	v4s,
	v4t,
	v4n,
	v4b,
	v4m,
	v2k_k,
	v2g_k,
	v2t_k,
	v2d_k,
	v2h_k,
	v2b_k,
	v2m_k,
	v2y_k,
	v2r_k,
	v2k_s,
	v2g_s,
	v2s_s,
	v2z_s,
	v2t_s,
	v2d_s,
	v2n_s,
	v2h_s,
	v2b_s,
	v2m_s,
	v2y_s,
	v2r_s,
	v2w_s,
	unc,
}

/// A map from the pos-ids to the matching enum
const Map<int, Pos> posIdToPosEnum = {
	1 : Pos.adj_i,
	2 : Pos.adj_na,
	3 : Pos.adj_no,
	4 : Pos.adj_pn,
	5 : Pos.adj_t,
	6 : Pos.adv,
	7 : Pos.adj_ix,
	8 : Pos.adv_to,
	9 : Pos.aux,
	10 : Pos.aux_adj,
	11 : Pos.aux_v,
	12 : Pos.conj,
	13 : Pos.exp,
	14 : Pos.int,
	15 : Pos.cop,
	17 : Pos.n,
	18 : Pos.n_adv,
	19 : Pos.n_suf,
	20 : Pos.n_pref,
	21 : Pos.n_t,
	24 : Pos.num,
	25 : Pos.pref,
	26 : Pos.prt,
	27 : Pos.suf,
	28 : Pos.v1,
	29 : Pos.v1_s,
	30 : Pos.v5aru,
	31 : Pos.v5b,
	32 : Pos.v5g,
	33 : Pos.v5k,
	34 : Pos.v5k_s,
	35 : Pos.v5m,
	36 : Pos.v5n,
	37 : Pos.v5r,
	38 : Pos.v5r_i,
	39 : Pos.v5s,
	40 : Pos.v5t,
	41 : Pos.v5u,
	42 : Pos.v5u_s,
	43 : Pos.v5uru,
	44 : Pos.vi,
	45 : Pos.vk,
	46 : Pos.vs,
	47 : Pos.vs_s,
	48 : Pos.vs_i,
	49 : Pos.vz,
	50 : Pos.vt,
	51 : Pos.ctr,
	52 : Pos.vn,
	53 : Pos.v4r,
	56 : Pos.adj_f,
	58 : Pos.vr,
	59 : Pos.v2a_s,
	60 : Pos.v4h,
	61 : Pos.pn,
	62 : Pos.vs_c,
	63 : Pos.adj_kari,
	64 : Pos.adj_ku,
	65 : Pos.adj_shiku,
	66 : Pos.adj_nari,
	67 : Pos.n_pr,
	68 : Pos.v_unspec,
	69 : Pos.v4k,
	70 : Pos.v4g,
	71 : Pos.v4s,
	72 : Pos.v4t,
	73 : Pos.v4n,
	74 : Pos.v4b,
	75 : Pos.v4m,
	76 : Pos.v2k_k,
	77 : Pos.v2g_k,
	78 : Pos.v2t_k,
	79 : Pos.v2d_k,
	80 : Pos.v2h_k,
	81 : Pos.v2b_k,
	82 : Pos.v2m_k,
	83 : Pos.v2y_k,
	84 : Pos.v2r_k,
	85 : Pos.v2k_s,
	86 : Pos.v2g_s,
	87 : Pos.v2s_s,
	88 : Pos.v2z_s,
	89 : Pos.v2t_s,
	90 : Pos.v2d_s,
	91 : Pos.v2n_s,
	92 : Pos.v2h_s,
	93 : Pos.v2b_s,
	94 : Pos.v2m_s,
	95 : Pos.v2y_s,
	96 : Pos.v2r_s,
	97 : Pos.v2w_s,
	98 : Pos.unc,
};

/// A map from the pos-enum to the matching pos-ids
const Map<Pos, int> posEnumToPosId = {
	Pos.adj_i : 1,
	Pos.adj_na : 2,
	Pos.adj_no : 3,
	Pos.adj_pn : 4,
	Pos.adj_t : 5,
	Pos.adv : 6,
	Pos.adj_ix : 7,
	Pos.adv_to : 8,
	Pos.aux : 9,
	Pos.aux_adj : 10,
	Pos.aux_v : 11,
	Pos.conj : 12,
	Pos.exp : 13,
	Pos.int : 14,
	Pos.cop : 15,
	Pos.n : 17,
	Pos.n_adv : 18,
	Pos.n_suf : 19,
	Pos.n_pref : 20,
	Pos.n_t : 21,
	Pos.num : 24,
	Pos.pref : 25,
	Pos.prt : 26,
	Pos.suf : 27,
	Pos.v1 : 28,
	Pos.v1_s : 29,
	Pos.v5aru : 30,
	Pos.v5b : 31,
	Pos.v5g : 32,
	Pos.v5k : 33,
	Pos.v5k_s : 34,
	Pos.v5m : 35,
	Pos.v5n : 36,
	Pos.v5r : 37,
	Pos.v5r_i : 38,
	Pos.v5s : 39,
	Pos.v5t : 40,
	Pos.v5u : 41,
	Pos.v5u_s : 42,
	Pos.v5uru : 43,
	Pos.vi : 44,
	Pos.vk : 45,
	Pos.vs : 46,
	Pos.vs_s : 47,
	Pos.vs_i : 48,
	Pos.vz : 49,
	Pos.vt : 50,
	Pos.ctr : 51,
	Pos.vn : 52,
	Pos.v4r : 53,
	Pos.adj_f : 56,
	Pos.vr : 58,
	Pos.v2a_s : 59,
	Pos.v4h : 60,
	Pos.pn : 61,
	Pos.vs_c : 62,
	Pos.adj_kari : 63,
	Pos.adj_ku : 64,
	Pos.adj_shiku : 65,
	Pos.adj_nari : 66,
	Pos.n_pr : 67,
	Pos.v_unspec : 68,
	Pos.v4k : 69,
	Pos.v4g : 70,
	Pos.v4s : 71,
	Pos.v4t : 72,
	Pos.v4n : 73,
	Pos.v4b : 74,
	Pos.v4m : 75,
	Pos.v2k_k : 76,
	Pos.v2g_k : 77,
	Pos.v2t_k : 78,
	Pos.v2d_k : 79,
	Pos.v2h_k : 80,
	Pos.v2b_k : 81,
	Pos.v2m_k : 82,
	Pos.v2y_k : 83,
	Pos.v2r_k : 84,
	Pos.v2k_s : 85,
	Pos.v2g_s : 86,
	Pos.v2s_s : 87,
	Pos.v2z_s : 88,
	Pos.v2t_s : 89,
	Pos.v2d_s : 90,
	Pos.v2n_s : 91,
	Pos.v2h_s : 92,
	Pos.v2b_s : 93,
	Pos.v2m_s : 94,
	Pos.v2y_s : 95,
	Pos.v2r_s : 96,
	Pos.v2w_s : 97,
	Pos.unc : 98,
};

/// A map from the pos-strings to the matching enum
const Map<String, Pos> posStringToPosEnum = {
	'adj-i' : Pos.adj_i,
	'adj-na' : Pos.adj_na,
	'adj-no' : Pos.adj_no,
	'adj-pn' : Pos.adj_pn,
	'adj-t' : Pos.adj_t,
	'adv' : Pos.adv,
	'adj-ix' : Pos.adj_ix,
	'adv-to' : Pos.adv_to,
	'aux' : Pos.aux,
	'aux-adj' : Pos.aux_adj,
	'aux-v' : Pos.aux_v,
	'conj' : Pos.conj,
	'exp' : Pos.exp,
	'int' : Pos.int,
	'cop' : Pos.cop,
	'n' : Pos.n,
	'n-adv' : Pos.n_adv,
	'n-suf' : Pos.n_suf,
	'n-pref' : Pos.n_pref,
	'n-t' : Pos.n_t,
	'num' : Pos.num,
	'pref' : Pos.pref,
	'prt' : Pos.prt,
	'suf' : Pos.suf,
	'v1' : Pos.v1,
	'v1-s' : Pos.v1_s,
	'v5aru' : Pos.v5aru,
	'v5b' : Pos.v5b,
	'v5g' : Pos.v5g,
	'v5k' : Pos.v5k,
	'v5k-s' : Pos.v5k_s,
	'v5m' : Pos.v5m,
	'v5n' : Pos.v5n,
	'v5r' : Pos.v5r,
	'v5r-i' : Pos.v5r_i,
	'v5s' : Pos.v5s,
	'v5t' : Pos.v5t,
	'v5u' : Pos.v5u,
	'v5u-s' : Pos.v5u_s,
	'v5uru' : Pos.v5uru,
	'vi' : Pos.vi,
	'vk' : Pos.vk,
	'vs' : Pos.vs,
	'vs-s' : Pos.vs_s,
	'vs-i' : Pos.vs_i,
	'vz' : Pos.vz,
	'vt' : Pos.vt,
	'ctr' : Pos.ctr,
	'vn' : Pos.vn,
	'v4r' : Pos.v4r,
	'adj-f' : Pos.adj_f,
	'vr' : Pos.vr,
	'v2a-s' : Pos.v2a_s,
	'v4h' : Pos.v4h,
	'pn' : Pos.pn,
	'vs-c' : Pos.vs_c,
	'adj-kari' : Pos.adj_kari,
	'adj-ku' : Pos.adj_ku,
	'adj-shiku' : Pos.adj_shiku,
	'adj-nari' : Pos.adj_nari,
	'n-pr' : Pos.n_pr,
	'v-unspec' : Pos.v_unspec,
	'v4k' : Pos.v4k,
	'v4g' : Pos.v4g,
	'v4s' : Pos.v4s,
	'v4t' : Pos.v4t,
	'v4n' : Pos.v4n,
	'v4b' : Pos.v4b,
	'v4m' : Pos.v4m,
	'v2k-k' : Pos.v2k_k,
	'v2g-k' : Pos.v2g_k,
	'v2t-k' : Pos.v2t_k,
	'v2d-k' : Pos.v2d_k,
	'v2h-k' : Pos.v2h_k,
	'v2b-k' : Pos.v2b_k,
	'v2m-k' : Pos.v2m_k,
	'v2y-k' : Pos.v2y_k,
	'v2r-k' : Pos.v2r_k,
	'v2k-s' : Pos.v2k_s,
	'v2g-s' : Pos.v2g_s,
	'v2s-s' : Pos.v2s_s,
	'v2z-s' : Pos.v2z_s,
	'v2t-s' : Pos.v2t_s,
	'v2d-s' : Pos.v2d_s,
	'v2n-s' : Pos.v2n_s,
	'v2h-s' : Pos.v2h_s,
	'v2b-s' : Pos.v2b_s,
	'v2m-s' : Pos.v2m_s,
	'v2y-s' : Pos.v2y_s,
	'v2r-s' : Pos.v2r_s,
	'v2w-s' : Pos.v2w_s,
	'unc' : Pos.unc,
};

/// A map from the Pos-strings to the matching enum
const Map<String, Pos> posDescriptionToPosEnum = {
	'adjective (keiyoushi)' : Pos.adj_i,
	'adjectival nouns or quasi-adjectives (keiyodoshi)' : Pos.adj_na,
	'nouns which may take the genitive case particle "no"' : Pos.adj_no,
	'pre-noun adjectival (rentaishi)' : Pos.adj_pn,
	'"taru" adjective' : Pos.adj_t,
	'adverb (fukushi)' : Pos.adv,
	'adjective (keiyoushi) - yoi/ii class' : Pos.adj_ix,
	'adverb taking the "to" particle' : Pos.adv_to,
	'auxiliary' : Pos.aux,
	'auxiliary adjective' : Pos.aux_adj,
	'auxiliary verb' : Pos.aux_v,
	'conjunction' : Pos.conj,
	'expressions (phrases, clauses, etc.)' : Pos.exp,
	'interjection (kandoushi)' : Pos.int,
	'copula' : Pos.cop,
	'noun (common) (futsuumeishi)' : Pos.n,
	'adverbial noun (fukushitekimeishi)' : Pos.n_adv,
	'noun, used as a suffix' : Pos.n_suf,
	'noun, used as a prefix' : Pos.n_pref,
	'noun (temporal) (jisoumeishi)' : Pos.n_t,
	'numeric' : Pos.num,
	'prefix' : Pos.pref,
	'particle' : Pos.prt,
	'suffix' : Pos.suf,
	'Ichidan verb' : Pos.v1,
	'Ichidan verb - kureru special class' : Pos.v1_s,
	'Godan verb - -aru special class' : Pos.v5aru,
	'Godan verb with "bu" ending' : Pos.v5b,
	'Godan verb with "gu" ending' : Pos.v5g,
	'Godan verb with "ku" ending' : Pos.v5k,
	'Godan verb - Iku/Yuku special class' : Pos.v5k_s,
	'Godan verb with "mu" ending' : Pos.v5m,
	'Godan verb with "nu" ending' : Pos.v5n,
	'Godan verb with "ru" ending' : Pos.v5r,
	'Godan verb with "ru" ending (irregular verb)' : Pos.v5r_i,
	'Godan verb with "su" ending' : Pos.v5s,
	'Godan verb with "tsu" ending' : Pos.v5t,
	'Godan verb with "u" ending' : Pos.v5u,
	'Godan verb with "u" ending (special class)' : Pos.v5u_s,
	'Godan verb - Uru old class verb (old form of Eru)' : Pos.v5uru,
	'intransitive verb' : Pos.vi,
	'Kuru verb - special class' : Pos.vk,
	'noun or participle which takes the aux. verb suru' : Pos.vs,
	'suru verb - special class' : Pos.vs_s,
	'suru verb - included' : Pos.vs_i,
	'Ichidan verb - zuru verb (alternative form of -jiru verbs)' : Pos.vz,
	'transitive verb' : Pos.vt,
	'counter' : Pos.ctr,
	'irregular nu verb' : Pos.vn,
	'Yodan verb with "ru" ending (archaic)' : Pos.v4r,
	'noun or verb acting prenominally' : Pos.adj_f,
	'irregular ru verb, plain form ends with -ri' : Pos.vr,
	'Nidan verb with "u" ending (archaic)' : Pos.v2a_s,
	'Yodan verb with "hu/fu" ending (archaic)' : Pos.v4h,
	'pronoun' : Pos.pn,
	'su verb - precursor to the modern suru' : Pos.vs_c,
	'"kari" adjective (archaic)' : Pos.adj_kari,
	'"ku" adjective (archaic)' : Pos.adj_ku,
	'"shiku" adjective (archaic)' : Pos.adj_shiku,
	'archaic/formal form of na-adjective' : Pos.adj_nari,
	'proper noun' : Pos.n_pr,
	'verb unspecified' : Pos.v_unspec,
	'Yodan verb with "ku" ending (archaic)' : Pos.v4k,
	'Yodan verb with "gu" ending (archaic)' : Pos.v4g,
	'Yodan verb with "su" ending (archaic)' : Pos.v4s,
	'Yodan verb with "tsu" ending (archaic)' : Pos.v4t,
	'Yodan verb with "nu" ending (archaic)' : Pos.v4n,
	'Yodan verb with "bu" ending (archaic)' : Pos.v4b,
	'Yodan verb with "mu" ending (archaic)' : Pos.v4m,
	'Nidan verb (upper class) with "ku" ending (archaic)' : Pos.v2k_k,
	'Nidan verb (upper class) with "gu" ending (archaic)' : Pos.v2g_k,
	'Nidan verb (upper class) with "tsu" ending (archaic)' : Pos.v2t_k,
	'Nidan verb (upper class) with "dzu" ending (archaic)' : Pos.v2d_k,
	'Nidan verb (upper class) with "hu/fu" ending (archaic)' : Pos.v2h_k,
	'Nidan verb (upper class) with "bu" ending (archaic)' : Pos.v2b_k,
	'Nidan verb (upper class) with "mu" ending (archaic)' : Pos.v2m_k,
	'Nidan verb (upper class) with "yu" ending (archaic)' : Pos.v2y_k,
	'Nidan verb (upper class) with "ru" ending (archaic)' : Pos.v2r_k,
	'Nidan verb (lower class) with "ku" ending (archaic)' : Pos.v2k_s,
	'Nidan verb (lower class) with "gu" ending (archaic)' : Pos.v2g_s,
	'Nidan verb (lower class) with "su" ending (archaic)' : Pos.v2s_s,
	'Nidan verb (lower class) with "zu" ending (archaic)' : Pos.v2z_s,
	'Nidan verb (lower class) with "tsu" ending (archaic)' : Pos.v2t_s,
	'Nidan verb (lower class) with "dzu" ending (archaic)' : Pos.v2d_s,
	'Nidan verb (lower class) with "nu" ending (archaic)' : Pos.v2n_s,
	'Nidan verb (lower class) with "hu/fu" ending (archaic)' : Pos.v2h_s,
	'Nidan verb (lower class) with "bu" ending (archaic)' : Pos.v2b_s,
	'Nidan verb (lower class) with "mu" ending (archaic)' : Pos.v2m_s,
	'Nidan verb (lower class) with "yu" ending (archaic)' : Pos.v2y_s,
	'Nidan verb (lower class) with "ru" ending (archaic)' : Pos.v2r_s,
	'Nidan verb (lower class) with "u" ending and "we" conjugation (archaic)' : Pos.v2w_s,
	'unclassified' : Pos.unc,
};

/// A map from a pos-enum to the pos-strings
const Map<Pos, String> posEnumToPosString = {
	Pos.adj_i : 'adj-i',
	Pos.adj_na : 'adj-na',
	Pos.adj_no : 'adj-no',
	Pos.adj_pn : 'adj-pn',
	Pos.adj_t : 'adj-t',
	Pos.adv : 'adv',
	Pos.adj_ix : 'adj-ix',
	Pos.adv_to : 'adv-to',
	Pos.aux : 'aux',
	Pos.aux_adj : 'aux-adj',
	Pos.aux_v : 'aux-v',
	Pos.conj : 'conj',
	Pos.exp : 'exp',
	Pos.int : 'int',
	Pos.cop : 'cop',
	Pos.n : 'n',
	Pos.n_adv : 'n-adv',
	Pos.n_suf : 'n-suf',
	Pos.n_pref : 'n-pref',
	Pos.n_t : 'n-t',
	Pos.num : 'num',
	Pos.pref : 'pref',
	Pos.prt : 'prt',
	Pos.suf : 'suf',
	Pos.v1 : 'v1',
	Pos.v1_s : 'v1-s',
	Pos.v5aru : 'v5aru',
	Pos.v5b : 'v5b',
	Pos.v5g : 'v5g',
	Pos.v5k : 'v5k',
	Pos.v5k_s : 'v5k-s',
	Pos.v5m : 'v5m',
	Pos.v5n : 'v5n',
	Pos.v5r : 'v5r',
	Pos.v5r_i : 'v5r-i',
	Pos.v5s : 'v5s',
	Pos.v5t : 'v5t',
	Pos.v5u : 'v5u',
	Pos.v5u_s : 'v5u-s',
	Pos.v5uru : 'v5uru',
	Pos.vi : 'vi',
	Pos.vk : 'vk',
	Pos.vs : 'vs',
	Pos.vs_s : 'vs-s',
	Pos.vs_i : 'vs-i',
	Pos.vz : 'vz',
	Pos.vt : 'vt',
	Pos.ctr : 'ctr',
	Pos.vn : 'vn',
	Pos.v4r : 'v4r',
	Pos.adj_f : 'adj-f',
	Pos.vr : 'vr',
	Pos.v2a_s : 'v2a-s',
	Pos.v4h : 'v4h',
	Pos.pn : 'pn',
	Pos.vs_c : 'vs-c',
	Pos.adj_kari : 'adj-kari',
	Pos.adj_ku : 'adj-ku',
	Pos.adj_shiku : 'adj-shiku',
	Pos.adj_nari : 'adj-nari',
	Pos.n_pr : 'n-pr',
	Pos.v_unspec : 'v-unspec',
	Pos.v4k : 'v4k',
	Pos.v4g : 'v4g',
	Pos.v4s : 'v4s',
	Pos.v4t : 'v4t',
	Pos.v4n : 'v4n',
	Pos.v4b : 'v4b',
	Pos.v4m : 'v4m',
	Pos.v2k_k : 'v2k-k',
	Pos.v2g_k : 'v2g-k',
	Pos.v2t_k : 'v2t-k',
	Pos.v2d_k : 'v2d-k',
	Pos.v2h_k : 'v2h-k',
	Pos.v2b_k : 'v2b-k',
	Pos.v2m_k : 'v2m-k',
	Pos.v2y_k : 'v2y-k',
	Pos.v2r_k : 'v2r-k',
	Pos.v2k_s : 'v2k-s',
	Pos.v2g_s : 'v2g-s',
	Pos.v2s_s : 'v2s-s',
	Pos.v2z_s : 'v2z-s',
	Pos.v2t_s : 'v2t-s',
	Pos.v2d_s : 'v2d-s',
	Pos.v2n_s : 'v2n-s',
	Pos.v2h_s : 'v2h-s',
	Pos.v2b_s : 'v2b-s',
	Pos.v2m_s : 'v2m-s',
	Pos.v2y_s : 'v2y-s',
	Pos.v2r_s : 'v2r-s',
	Pos.v2w_s : 'v2w-s',
	Pos.unc : 'unc',
};

/// A map from a Pos-enum to the Pos-description
const Map<Pos, String> posEnumToPosDescription = {
	Pos.adj_i : 'adjective (keiyoushi)',
	Pos.adj_na : 'adjectival nouns or quasi-adjectives (keiyodoshi)',
	Pos.adj_no : 'nouns which may take the genitive case particle "no"',
	Pos.adj_pn : 'pre-noun adjectival (rentaishi)',
	Pos.adj_t : '"taru" adjective',
	Pos.adv : 'adverb (fukushi)',
	Pos.adj_ix : 'adjective (keiyoushi) - yoi/ii class',
	Pos.adv_to : 'adverb taking the "to" particle',
	Pos.aux : 'auxiliary',
	Pos.aux_adj : 'auxiliary adjective',
	Pos.aux_v : 'auxiliary verb',
	Pos.conj : 'conjunction',
	Pos.exp : 'expressions (phrases, clauses, etc.)',
	Pos.int : 'interjection (kandoushi)',
	Pos.cop : 'copula',
	Pos.n : 'noun (common) (futsuumeishi)',
	Pos.n_adv : 'adverbial noun (fukushitekimeishi)',
	Pos.n_suf : 'noun, used as a suffix',
	Pos.n_pref : 'noun, used as a prefix',
	Pos.n_t : 'noun (temporal) (jisoumeishi)',
	Pos.num : 'numeric',
	Pos.pref : 'prefix',
	Pos.prt : 'particle',
	Pos.suf : 'suffix',
	Pos.v1 : 'Ichidan verb',
	Pos.v1_s : 'Ichidan verb - kureru special class',
	Pos.v5aru : 'Godan verb - -aru special class',
	Pos.v5b : 'Godan verb with "bu" ending',
	Pos.v5g : 'Godan verb with "gu" ending',
	Pos.v5k : 'Godan verb with "ku" ending',
	Pos.v5k_s : 'Godan verb - Iku/Yuku special class',
	Pos.v5m : 'Godan verb with "mu" ending',
	Pos.v5n : 'Godan verb with "nu" ending',
	Pos.v5r : 'Godan verb with "ru" ending',
	Pos.v5r_i : 'Godan verb with "ru" ending (irregular verb)',
	Pos.v5s : 'Godan verb with "su" ending',
	Pos.v5t : 'Godan verb with "tsu" ending',
	Pos.v5u : 'Godan verb with "u" ending',
	Pos.v5u_s : 'Godan verb with "u" ending (special class)',
	Pos.v5uru : 'Godan verb - Uru old class verb (old form of Eru)',
	Pos.vi : 'intransitive verb',
	Pos.vk : 'Kuru verb - special class',
	Pos.vs : 'noun or participle which takes the aux. verb suru',
	Pos.vs_s : 'suru verb - special class',
	Pos.vs_i : 'suru verb - included',
	Pos.vz : 'Ichidan verb - zuru verb (alternative form of -jiru verbs)',
	Pos.vt : 'transitive verb',
	Pos.ctr : 'counter',
	Pos.vn : 'irregular nu verb',
	Pos.v4r : 'Yodan verb with "ru" ending (archaic)',
	Pos.adj_f : 'noun or verb acting prenominally',
	Pos.vr : 'irregular ru verb, plain form ends with -ri',
	Pos.v2a_s : 'Nidan verb with "u" ending (archaic)',
	Pos.v4h : 'Yodan verb with "hu/fu" ending (archaic)',
	Pos.pn : 'pronoun',
	Pos.vs_c : 'su verb - precursor to the modern suru',
	Pos.adj_kari : '"kari" adjective (archaic)',
	Pos.adj_ku : '"ku" adjective (archaic)',
	Pos.adj_shiku : '"shiku" adjective (archaic)',
	Pos.adj_nari : 'archaic/formal form of na-adjective',
	Pos.n_pr : 'proper noun',
	Pos.v_unspec : 'verb unspecified',
	Pos.v4k : 'Yodan verb with "ku" ending (archaic)',
	Pos.v4g : 'Yodan verb with "gu" ending (archaic)',
	Pos.v4s : 'Yodan verb with "su" ending (archaic)',
	Pos.v4t : 'Yodan verb with "tsu" ending (archaic)',
	Pos.v4n : 'Yodan verb with "nu" ending (archaic)',
	Pos.v4b : 'Yodan verb with "bu" ending (archaic)',
	Pos.v4m : 'Yodan verb with "mu" ending (archaic)',
	Pos.v2k_k : 'Nidan verb (upper class) with "ku" ending (archaic)',
	Pos.v2g_k : 'Nidan verb (upper class) with "gu" ending (archaic)',
	Pos.v2t_k : 'Nidan verb (upper class) with "tsu" ending (archaic)',
	Pos.v2d_k : 'Nidan verb (upper class) with "dzu" ending (archaic)',
	Pos.v2h_k : 'Nidan verb (upper class) with "hu/fu" ending (archaic)',
	Pos.v2b_k : 'Nidan verb (upper class) with "bu" ending (archaic)',
	Pos.v2m_k : 'Nidan verb (upper class) with "mu" ending (archaic)',
	Pos.v2y_k : 'Nidan verb (upper class) with "yu" ending (archaic)',
	Pos.v2r_k : 'Nidan verb (upper class) with "ru" ending (archaic)',
	Pos.v2k_s : 'Nidan verb (lower class) with "ku" ending (archaic)',
	Pos.v2g_s : 'Nidan verb (lower class) with "gu" ending (archaic)',
	Pos.v2s_s : 'Nidan verb (lower class) with "su" ending (archaic)',
	Pos.v2z_s : 'Nidan verb (lower class) with "zu" ending (archaic)',
	Pos.v2t_s : 'Nidan verb (lower class) with "tsu" ending (archaic)',
	Pos.v2d_s : 'Nidan verb (lower class) with "dzu" ending (archaic)',
	Pos.v2n_s : 'Nidan verb (lower class) with "nu" ending (archaic)',
	Pos.v2h_s : 'Nidan verb (lower class) with "hu/fu" ending (archaic)',
	Pos.v2b_s : 'Nidan verb (lower class) with "bu" ending (archaic)',
	Pos.v2m_s : 'Nidan verb (lower class) with "mu" ending (archaic)',
	Pos.v2y_s : 'Nidan verb (lower class) with "yu" ending (archaic)',
	Pos.v2r_s : 'Nidan verb (lower class) with "ru" ending (archaic)',
	Pos.v2w_s : 'Nidan verb (lower class) with "u" ending and "we" conjugation (archaic)',
	Pos.unc : 'unclassified',
};

