//based on kwpos.csv which was scraped from
//https://gitlab.com/yamagoya/jmdictdb/-/tree/master/jmdictdb/data

import 'pos.dart';



/// An enum containing the pos tags to identify pos elements
enum pos {
	adj_i,
	adj_na,
	adj_no,
	adj_pn,
	adj_t,
	adv,
	adj_ix,
	adv_to,
	aux,
	aux_adj,
	aux_v,
	conj,
	exp,
	int,
	cop,
	n,
	n_adv,
	n_suf,
	n_pref,
	n_t,
	num,
	pref,
	prt,
	suf,
	v1,
	v1_s,
	v5aru,
	v5b,
	v5g,
	v5k,
	v5k_s,
	v5m,
	v5n,
	v5r,
	v5r_i,
	v5s,
	v5t,
	v5u,
	v5u_s,
	v5uru,
	vi,
	vk,
	vs,
	vs_s,
	vs_i,
	vz,
	vt,
	ctr,
	vn,
	v4r,
	adj_f,
	vr,
	v2a_s,
	v4h,
	pn,
	vs_c,
	adj_kari,
	adj_ku,
	adj_shiku,
	adj_nari,
	n_pr,
	v_unspec,
	v4k,
	v4g,
	v4s,
	v4t,
	v4n,
	v4b,
	v4m,
	v2k_k,
	v2g_k,
	v2t_k,
	v2d_k,
	v2h_k,
	v2b_k,
	v2m_k,
	v2y_k,
	v2r_k,
	v2k_s,
	v2g_s,
	v2s_s,
	v2z_s,
	v2t_s,
	v2d_s,
	v2n_s,
	v2h_s,
	v2b_s,
	v2m_s,
	v2y_s,
	v2r_s,
	v2w_s,
	unc,
}

/// A map from the pos-strings to the matching enum
const Map<String, pos> posStringToPosEnum = {
	'adj-i' : pos.adj_i,
	'adj-na' : pos.adj_na,
	'adj-no' : pos.adj_no,
	'adj-pn' : pos.adj_pn,
	'adj-t' : pos.adj_t,
	'adv' : pos.adv,
	'adj-ix' : pos.adj_ix,
	'adv-to' : pos.adv_to,
	'aux' : pos.aux,
	'aux-adj' : pos.aux_adj,
	'aux-v' : pos.aux_v,
	'conj' : pos.conj,
	'exp' : pos.exp,
	'int' : pos.int,
	'cop' : pos.cop,
	'n' : pos.n,
	'n-adv' : pos.n_adv,
	'n-suf' : pos.n_suf,
	'n-pref' : pos.n_pref,
	'n-t' : pos.n_t,
	'num' : pos.num,
	'pref' : pos.pref,
	'prt' : pos.prt,
	'suf' : pos.suf,
	'v1' : pos.v1,
	'v1-s' : pos.v1_s,
	'v5aru' : pos.v5aru,
	'v5b' : pos.v5b,
	'v5g' : pos.v5g,
	'v5k' : pos.v5k,
	'v5k-s' : pos.v5k_s,
	'v5m' : pos.v5m,
	'v5n' : pos.v5n,
	'v5r' : pos.v5r,
	'v5r-i' : pos.v5r_i,
	'v5s' : pos.v5s,
	'v5t' : pos.v5t,
	'v5u' : pos.v5u,
	'v5u-s' : pos.v5u_s,
	'v5uru' : pos.v5uru,
	'vi' : pos.vi,
	'vk' : pos.vk,
	'vs' : pos.vs,
	'vs-s' : pos.vs_s,
	'vs-i' : pos.vs_i,
	'vz' : pos.vz,
	'vt' : pos.vt,
	'ctr' : pos.ctr,
	'vn' : pos.vn,
	'v4r' : pos.v4r,
	'adj-f' : pos.adj_f,
	'vr' : pos.vr,
	'v2a-s' : pos.v2a_s,
	'v4h' : pos.v4h,
	'pn' : pos.pn,
	'vs-c' : pos.vs_c,
	'adj-kari' : pos.adj_kari,
	'adj-ku' : pos.adj_ku,
	'adj-shiku' : pos.adj_shiku,
	'adj-nari' : pos.adj_nari,
	'n-pr' : pos.n_pr,
	'v-unspec' : pos.v_unspec,
	'v4k' : pos.v4k,
	'v4g' : pos.v4g,
	'v4s' : pos.v4s,
	'v4t' : pos.v4t,
	'v4n' : pos.v4n,
	'v4b' : pos.v4b,
	'v4m' : pos.v4m,
	'v2k-k' : pos.v2k_k,
	'v2g-k' : pos.v2g_k,
	'v2t-k' : pos.v2t_k,
	'v2d-k' : pos.v2d_k,
	'v2h-k' : pos.v2h_k,
	'v2b-k' : pos.v2b_k,
	'v2m-k' : pos.v2m_k,
	'v2y-k' : pos.v2y_k,
	'v2r-k' : pos.v2r_k,
	'v2k-s' : pos.v2k_s,
	'v2g-s' : pos.v2g_s,
	'v2s-s' : pos.v2s_s,
	'v2z-s' : pos.v2z_s,
	'v2t-s' : pos.v2t_s,
	'v2d-s' : pos.v2d_s,
	'v2n-s' : pos.v2n_s,
	'v2h-s' : pos.v2h_s,
	'v2b-s' : pos.v2b_s,
	'v2m-s' : pos.v2m_s,
	'v2y-s' : pos.v2y_s,
	'v2r-s' : pos.v2r_s,
	'v2w-s' : pos.v2w_s,
	'unc' : pos.unc,
};

/// A map from the pos-strings to the matching enum
const Map<String, pos> posDescriptionToPosEnum = {
	'adjective (keiyoushi)' : pos.adj_i,
	'adjectival nouns or quasi-adjectives (keiyodoshi)' : pos.adj_na,
	'nouns which may take the genitive case particle "no"' : pos.adj_no,
	'pre-noun adjectival (rentaishi)' : pos.adj_pn,
	'"taru" adjective' : pos.adj_t,
	'adverb (fukushi)' : pos.adv,
	'adjective (keiyoushi) - yoi/ii class' : pos.adj_ix,
	'adverb taking the "to" particle' : pos.adv_to,
	'auxiliary' : pos.aux,
	'auxiliary adjective' : pos.aux_adj,
	'auxiliary verb' : pos.aux_v,
	'conjunction' : pos.conj,
	'expressions (phrases, clauses, etc.)' : pos.exp,
	'interjection (kandoushi)' : pos.int,
	'copula' : pos.cop,
	'noun (common) (futsuumeishi)' : pos.n,
	'adverbial noun (fukushitekimeishi)' : pos.n_adv,
	'noun, used as a suffix' : pos.n_suf,
	'noun, used as a prefix' : pos.n_pref,
	'noun (temporal) (jisoumeishi)' : pos.n_t,
	'numeric' : pos.num,
	'prefix' : pos.pref,
	'particle' : pos.prt,
	'suffix' : pos.suf,
	'Ichidan verb' : pos.v1,
	'Ichidan verb - kureru special class' : pos.v1_s,
	'Godan verb - -aru special class' : pos.v5aru,
	'Godan verb with "bu" ending' : pos.v5b,
	'Godan verb with "gu" ending' : pos.v5g,
	'Godan verb with "ku" ending' : pos.v5k,
	'Godan verb - Iku/Yuku special class' : pos.v5k_s,
	'Godan verb with "mu" ending' : pos.v5m,
	'Godan verb with "nu" ending' : pos.v5n,
	'Godan verb with "ru" ending' : pos.v5r,
	'Godan verb with "ru" ending (irregular verb)' : pos.v5r_i,
	'Godan verb with "su" ending' : pos.v5s,
	'Godan verb with "tsu" ending' : pos.v5t,
	'Godan verb with "u" ending' : pos.v5u,
	'Godan verb with "u" ending (special class)' : pos.v5u_s,
	'Godan verb - Uru old class verb (old form of Eru)' : pos.v5uru,
	'intransitive verb' : pos.vi,
	'Kuru verb - special class' : pos.vk,
	'noun or participle which takes the aux. verb suru' : pos.vs,
	'suru verb - special class' : pos.vs_s,
	'suru verb - included' : pos.vs_i,
	'Ichidan verb - zuru verb (alternative form of -jiru verbs)' : pos.vz,
	'transitive verb' : pos.vt,
	'counter' : pos.ctr,
	'irregular nu verb' : pos.vn,
	'Yodan verb with "ru" ending (archaic)' : pos.v4r,
	'noun or verb acting prenominally' : pos.adj_f,
	'irregular ru verb, plain form ends with -ri' : pos.vr,
	'Nidan verb with "u" ending (archaic)' : pos.v2a_s,
	'Yodan verb with "hu/fu" ending (archaic)' : pos.v4h,
	'pronoun' : pos.pn,
	'su verb - precursor to the modern suru' : pos.vs_c,
	'"kari" adjective (archaic)' : pos.adj_kari,
	'"ku" adjective (archaic)' : pos.adj_ku,
	'"shiku" adjective (archaic)' : pos.adj_shiku,
	'archaic/formal form of na-adjective' : pos.adj_nari,
	'proper noun' : pos.n_pr,
	'verb unspecified' : pos.v_unspec,
	'Yodan verb with "ku" ending (archaic)' : pos.v4k,
	'Yodan verb with "gu" ending (archaic)' : pos.v4g,
	'Yodan verb with "su" ending (archaic)' : pos.v4s,
	'Yodan verb with "tsu" ending (archaic)' : pos.v4t,
	'Yodan verb with "nu" ending (archaic)' : pos.v4n,
	'Yodan verb with "bu" ending (archaic)' : pos.v4b,
	'Yodan verb with "mu" ending (archaic)' : pos.v4m,
	'Nidan verb (upper class) with "ku" ending (archaic)' : pos.v2k_k,
	'Nidan verb (upper class) with "gu" ending (archaic)' : pos.v2g_k,
	'Nidan verb (upper class) with "tsu" ending (archaic)' : pos.v2t_k,
	'Nidan verb (upper class) with "dzu" ending (archaic)' : pos.v2d_k,
	'Nidan verb (upper class) with "hu/fu" ending (archaic)' : pos.v2h_k,
	'Nidan verb (upper class) with "bu" ending (archaic)' : pos.v2b_k,
	'Nidan verb (upper class) with "mu" ending (archaic)' : pos.v2m_k,
	'Nidan verb (upper class) with "yu" ending (archaic)' : pos.v2y_k,
	'Nidan verb (upper class) with "ru" ending (archaic)' : pos.v2r_k,
	'Nidan verb (lower class) with "ku" ending (archaic)' : pos.v2k_s,
	'Nidan verb (lower class) with "gu" ending (archaic)' : pos.v2g_s,
	'Nidan verb (lower class) with "su" ending (archaic)' : pos.v2s_s,
	'Nidan verb (lower class) with "zu" ending (archaic)' : pos.v2z_s,
	'Nidan verb (lower class) with "tsu" ending (archaic)' : pos.v2t_s,
	'Nidan verb (lower class) with "dzu" ending (archaic)' : pos.v2d_s,
	'Nidan verb (lower class) with "nu" ending (archaic)' : pos.v2n_s,
	'Nidan verb (lower class) with "hu/fu" ending (archaic)' : pos.v2h_s,
	'Nidan verb (lower class) with "bu" ending (archaic)' : pos.v2b_s,
	'Nidan verb (lower class) with "mu" ending (archaic)' : pos.v2m_s,
	'Nidan verb (lower class) with "yu" ending (archaic)' : pos.v2y_s,
	'Nidan verb (lower class) with "ru" ending (archaic)' : pos.v2r_s,
	'Nidan verb (lower class) with "u" ending and "we" conjugation (archaic)' : pos.v2w_s,
	'unclassified' : pos.unc,
};

/// A map from a pos-enum to the pos-strings
const Map<pos, String> posEnumToPosString = {
	pos.adj_i : 'adj-i',
	pos.adj_na : 'adj-na',
	pos.adj_no : 'adj-no',
	pos.adj_pn : 'adj-pn',
	pos.adj_t : 'adj-t',
	pos.adv : 'adv',
	pos.adj_ix : 'adj-ix',
	pos.adv_to : 'adv-to',
	pos.aux : 'aux',
	pos.aux_adj : 'aux-adj',
	pos.aux_v : 'aux-v',
	pos.conj : 'conj',
	pos.exp : 'exp',
	pos.int : 'int',
	pos.cop : 'cop',
	pos.n : 'n',
	pos.n_adv : 'n-adv',
	pos.n_suf : 'n-suf',
	pos.n_pref : 'n-pref',
	pos.n_t : 'n-t',
	pos.num : 'num',
	pos.pref : 'pref',
	pos.prt : 'prt',
	pos.suf : 'suf',
	pos.v1 : 'v1',
	pos.v1_s : 'v1-s',
	pos.v5aru : 'v5aru',
	pos.v5b : 'v5b',
	pos.v5g : 'v5g',
	pos.v5k : 'v5k',
	pos.v5k_s : 'v5k-s',
	pos.v5m : 'v5m',
	pos.v5n : 'v5n',
	pos.v5r : 'v5r',
	pos.v5r_i : 'v5r-i',
	pos.v5s : 'v5s',
	pos.v5t : 'v5t',
	pos.v5u : 'v5u',
	pos.v5u_s : 'v5u-s',
	pos.v5uru : 'v5uru',
	pos.vi : 'vi',
	pos.vk : 'vk',
	pos.vs : 'vs',
	pos.vs_s : 'vs-s',
	pos.vs_i : 'vs-i',
	pos.vz : 'vz',
	pos.vt : 'vt',
	pos.ctr : 'ctr',
	pos.vn : 'vn',
	pos.v4r : 'v4r',
	pos.adj_f : 'adj-f',
	pos.vr : 'vr',
	pos.v2a_s : 'v2a-s',
	pos.v4h : 'v4h',
	pos.pn : 'pn',
	pos.vs_c : 'vs-c',
	pos.adj_kari : 'adj-kari',
	pos.adj_ku : 'adj-ku',
	pos.adj_shiku : 'adj-shiku',
	pos.adj_nari : 'adj-nari',
	pos.n_pr : 'n-pr',
	pos.v_unspec : 'v-unspec',
	pos.v4k : 'v4k',
	pos.v4g : 'v4g',
	pos.v4s : 'v4s',
	pos.v4t : 'v4t',
	pos.v4n : 'v4n',
	pos.v4b : 'v4b',
	pos.v4m : 'v4m',
	pos.v2k_k : 'v2k-k',
	pos.v2g_k : 'v2g-k',
	pos.v2t_k : 'v2t-k',
	pos.v2d_k : 'v2d-k',
	pos.v2h_k : 'v2h-k',
	pos.v2b_k : 'v2b-k',
	pos.v2m_k : 'v2m-k',
	pos.v2y_k : 'v2y-k',
	pos.v2r_k : 'v2r-k',
	pos.v2k_s : 'v2k-s',
	pos.v2g_s : 'v2g-s',
	pos.v2s_s : 'v2s-s',
	pos.v2z_s : 'v2z-s',
	pos.v2t_s : 'v2t-s',
	pos.v2d_s : 'v2d-s',
	pos.v2n_s : 'v2n-s',
	pos.v2h_s : 'v2h-s',
	pos.v2b_s : 'v2b-s',
	pos.v2m_s : 'v2m-s',
	pos.v2y_s : 'v2y-s',
	pos.v2r_s : 'v2r-s',
	pos.v2w_s : 'v2w-s',
	pos.unc : 'unc',
};

/// A map from a pos-enum to the pos-description
const Map<pos, String> posEnumToPosDescription = {
	pos.adj_i : 'adjective (keiyoushi)',
	pos.adj_na : 'adjectival nouns or quasi-adjectives (keiyodoshi)',
	pos.adj_no : 'nouns which may take the genitive case particle "no"',
	pos.adj_pn : 'pre-noun adjectival (rentaishi)',
	pos.adj_t : '"taru" adjective',
	pos.adv : 'adverb (fukushi)',
	pos.adj_ix : 'adjective (keiyoushi) - yoi/ii class',
	pos.adv_to : 'adverb taking the "to" particle',
	pos.aux : 'auxiliary',
	pos.aux_adj : 'auxiliary adjective',
	pos.aux_v : 'auxiliary verb',
	pos.conj : 'conjunction',
	pos.exp : 'expressions (phrases, clauses, etc.)',
	pos.int : 'interjection (kandoushi)',
	pos.cop : 'copula',
	pos.n : 'noun (common) (futsuumeishi)',
	pos.n_adv : 'adverbial noun (fukushitekimeishi)',
	pos.n_suf : 'noun, used as a suffix',
	pos.n_pref : 'noun, used as a prefix',
	pos.n_t : 'noun (temporal) (jisoumeishi)',
	pos.num : 'numeric',
	pos.pref : 'prefix',
	pos.prt : 'particle',
	pos.suf : 'suffix',
	pos.v1 : 'Ichidan verb',
	pos.v1_s : 'Ichidan verb - kureru special class',
	pos.v5aru : 'Godan verb - -aru special class',
	pos.v5b : 'Godan verb with "bu" ending',
	pos.v5g : 'Godan verb with "gu" ending',
	pos.v5k : 'Godan verb with "ku" ending',
	pos.v5k_s : 'Godan verb - Iku/Yuku special class',
	pos.v5m : 'Godan verb with "mu" ending',
	pos.v5n : 'Godan verb with "nu" ending',
	pos.v5r : 'Godan verb with "ru" ending',
	pos.v5r_i : 'Godan verb with "ru" ending (irregular verb)',
	pos.v5s : 'Godan verb with "su" ending',
	pos.v5t : 'Godan verb with "tsu" ending',
	pos.v5u : 'Godan verb with "u" ending',
	pos.v5u_s : 'Godan verb with "u" ending (special class)',
	pos.v5uru : 'Godan verb - Uru old class verb (old form of Eru)',
	pos.vi : 'intransitive verb',
	pos.vk : 'Kuru verb - special class',
	pos.vs : 'noun or participle which takes the aux. verb suru',
	pos.vs_s : 'suru verb - special class',
	pos.vs_i : 'suru verb - included',
	pos.vz : 'Ichidan verb - zuru verb (alternative form of -jiru verbs)',
	pos.vt : 'transitive verb',
	pos.ctr : 'counter',
	pos.vn : 'irregular nu verb',
	pos.v4r : 'Yodan verb with "ru" ending (archaic)',
	pos.adj_f : 'noun or verb acting prenominally',
	pos.vr : 'irregular ru verb, plain form ends with -ri',
	pos.v2a_s : 'Nidan verb with "u" ending (archaic)',
	pos.v4h : 'Yodan verb with "hu/fu" ending (archaic)',
	pos.pn : 'pronoun',
	pos.vs_c : 'su verb - precursor to the modern suru',
	pos.adj_kari : '"kari" adjective (archaic)',
	pos.adj_ku : '"ku" adjective (archaic)',
	pos.adj_shiku : '"shiku" adjective (archaic)',
	pos.adj_nari : 'archaic/formal form of na-adjective',
	pos.n_pr : 'proper noun',
	pos.v_unspec : 'verb unspecified',
	pos.v4k : 'Yodan verb with "ku" ending (archaic)',
	pos.v4g : 'Yodan verb with "gu" ending (archaic)',
	pos.v4s : 'Yodan verb with "su" ending (archaic)',
	pos.v4t : 'Yodan verb with "tsu" ending (archaic)',
	pos.v4n : 'Yodan verb with "nu" ending (archaic)',
	pos.v4b : 'Yodan verb with "bu" ending (archaic)',
	pos.v4m : 'Yodan verb with "mu" ending (archaic)',
	pos.v2k_k : 'Nidan verb (upper class) with "ku" ending (archaic)',
	pos.v2g_k : 'Nidan verb (upper class) with "gu" ending (archaic)',
	pos.v2t_k : 'Nidan verb (upper class) with "tsu" ending (archaic)',
	pos.v2d_k : 'Nidan verb (upper class) with "dzu" ending (archaic)',
	pos.v2h_k : 'Nidan verb (upper class) with "hu/fu" ending (archaic)',
	pos.v2b_k : 'Nidan verb (upper class) with "bu" ending (archaic)',
	pos.v2m_k : 'Nidan verb (upper class) with "mu" ending (archaic)',
	pos.v2y_k : 'Nidan verb (upper class) with "yu" ending (archaic)',
	pos.v2r_k : 'Nidan verb (upper class) with "ru" ending (archaic)',
	pos.v2k_s : 'Nidan verb (lower class) with "ku" ending (archaic)',
	pos.v2g_s : 'Nidan verb (lower class) with "gu" ending (archaic)',
	pos.v2s_s : 'Nidan verb (lower class) with "su" ending (archaic)',
	pos.v2z_s : 'Nidan verb (lower class) with "zu" ending (archaic)',
	pos.v2t_s : 'Nidan verb (lower class) with "tsu" ending (archaic)',
	pos.v2d_s : 'Nidan verb (lower class) with "dzu" ending (archaic)',
	pos.v2n_s : 'Nidan verb (lower class) with "nu" ending (archaic)',
	pos.v2h_s : 'Nidan verb (lower class) with "hu/fu" ending (archaic)',
	pos.v2b_s : 'Nidan verb (lower class) with "bu" ending (archaic)',
	pos.v2m_s : 'Nidan verb (lower class) with "mu" ending (archaic)',
	pos.v2y_s : 'Nidan verb (lower class) with "yu" ending (archaic)',
	pos.v2r_s : 'Nidan verb (lower class) with "ru" ending (archaic)',
	pos.v2w_s : 'Nidan verb (lower class) with "u" ending and "we" conjugation (archaic)',
	pos.unc : 'unclassified',
};

