//based on kwpos.csv which was scraped from
//https://gitlab.com/yamagoya/jmdictdb/-/tree/master/jmdictdb/data

import 'pos.dart';



/// A map from the id to the pos description
const Map<int, Pos> conj = {
	1 : Pos('adj-i', 'adjective (keiyoushi)'),
	2 : Pos('adj-na', 'adjectival nouns or quasi-adjectives (keiyodoshi)'),
	3 : Pos('adj-no', 'nouns which may take the genitive case particle "no"'),
	4 : Pos('adj-pn', 'pre-noun adjectival (rentaishi)'),
	5 : Pos('adj-t', '"taru" adjective'),
	6 : Pos('adv', 'adverb (fukushi)'),
	7 : Pos('adj-ix', 'adjective (keiyoushi) - yoi/ii class'),
	8 : Pos('adv-to', 'adverb taking the "to" particle'),
	9 : Pos('aux', 'auxiliary'),
	10 : Pos('aux-adj', 'auxiliary adjective'),
	11 : Pos('aux-v', 'auxiliary verb'),
	12 : Pos('conj', 'conjunction'),
	13 : Pos('exp', 'expressions (phrases, clauses, etc.)'),
	14 : Pos('int', 'interjection (kandoushi)'),
	15 : Pos('cop', 'copula'),
	17 : Pos('n', 'noun (common) (futsuumeishi)'),
	18 : Pos('n-adv', 'adverbial noun (fukushitekimeishi)'),
	19 : Pos('n-suf', 'noun, used as a suffix'),
	20 : Pos('n-pref', 'noun, used as a prefix'),
	21 : Pos('n-t', 'noun (temporal) (jisoumeishi)'),
	24 : Pos('num', 'numeric'),
	25 : Pos('pref', 'prefix'),
	26 : Pos('prt', 'particle'),
	27 : Pos('suf', 'suffix'),
	28 : Pos('v1', 'Ichidan verb'),
	29 : Pos('v1-s', 'Ichidan verb - kureru special class'),
	30 : Pos('v5aru', 'Godan verb - -aru special class'),
	31 : Pos('v5b', 'Godan verb with "bu" ending'),
	32 : Pos('v5g', 'Godan verb with "gu" ending'),
	33 : Pos('v5k', 'Godan verb with "ku" ending'),
	34 : Pos('v5k-s', 'Godan verb - Iku/Yuku special class'),
	35 : Pos('v5m', 'Godan verb with "mu" ending'),
	36 : Pos('v5n', 'Godan verb with "nu" ending'),
	37 : Pos('v5r', 'Godan verb with "ru" ending'),
	38 : Pos('v5r-i', 'Godan verb with "ru" ending (irregular verb)'),
	39 : Pos('v5s', 'Godan verb with "su" ending'),
	40 : Pos('v5t', 'Godan verb with "tsu" ending'),
	41 : Pos('v5u', 'Godan verb with "u" ending'),
	42 : Pos('v5u-s', 'Godan verb with "u" ending (special class)'),
	43 : Pos('v5uru', 'Godan verb - Uru old class verb (old form of Eru)'),
	44 : Pos('vi', 'intransitive verb'),
	45 : Pos('vk', 'Kuru verb - special class'),
	46 : Pos('vs', 'noun or participle which takes the aux. verb suru'),
	47 : Pos('vs-s', 'suru verb - special class'),
	48 : Pos('vs-i', 'suru verb - included'),
	49 : Pos('vz', 'Ichidan verb - zuru verb (alternative form of -jiru verbs)'),
	50 : Pos('vt', 'transitive verb'),
	51 : Pos('ctr', 'counter'),
	52 : Pos('vn', 'irregular nu verb'),
	53 : Pos('v4r', 'Yodan verb with "ru" ending (archaic)'),
	56 : Pos('adj-f', 'noun or verb acting prenominally'),
	58 : Pos('vr', 'irregular ru verb, plain form ends with -ri'),
	59 : Pos('v2a-s', 'Nidan verb with "u" ending (archaic)'),
	60 : Pos('v4h', 'Yodan verb with "hu/fu" ending (archaic)'),
	61 : Pos('pn', 'pronoun'),
	62 : Pos('vs-c', 'su verb - precursor to the modern suru'),
	63 : Pos('adj-kari', '"kari" adjective (archaic)'),
	64 : Pos('adj-ku', '"ku" adjective (archaic)'),
	65 : Pos('adj-shiku', '"shiku" adjective (archaic)'),
	66 : Pos('adj-nari', 'archaic/formal form of na-adjective'),
	67 : Pos('n-pr', 'proper noun'),
	68 : Pos('v-unspec', 'verb unspecified'),
	69 : Pos('v4k', 'Yodan verb with "ku" ending (archaic)'),
	70 : Pos('v4g', 'Yodan verb with "gu" ending (archaic)'),
	71 : Pos('v4s', 'Yodan verb with "su" ending (archaic)'),
	72 : Pos('v4t', 'Yodan verb with "tsu" ending (archaic)'),
	73 : Pos('v4n', 'Yodan verb with "nu" ending (archaic)'),
	74 : Pos('v4b', 'Yodan verb with "bu" ending (archaic)'),
	75 : Pos('v4m', 'Yodan verb with "mu" ending (archaic)'),
	76 : Pos('v2k-k', 'Nidan verb (upper class) with "ku" ending (archaic)'),
	77 : Pos('v2g-k', 'Nidan verb (upper class) with "gu" ending (archaic)'),
	78 : Pos('v2t-k', 'Nidan verb (upper class) with "tsu" ending (archaic)'),
	79 : Pos('v2d-k', 'Nidan verb (upper class) with "dzu" ending (archaic)'),
	80 : Pos('v2h-k', 'Nidan verb (upper class) with "hu/fu" ending (archaic)'),
	81 : Pos('v2b-k', 'Nidan verb (upper class) with "bu" ending (archaic)'),
	82 : Pos('v2m-k', 'Nidan verb (upper class) with "mu" ending (archaic)'),
	83 : Pos('v2y-k', 'Nidan verb (upper class) with "yu" ending (archaic)'),
	84 : Pos('v2r-k', 'Nidan verb (upper class) with "ru" ending (archaic)'),
	85 : Pos('v2k-s', 'Nidan verb (lower class) with "ku" ending (archaic)'),
	86 : Pos('v2g-s', 'Nidan verb (lower class) with "gu" ending (archaic)'),
	87 : Pos('v2s-s', 'Nidan verb (lower class) with "su" ending (archaic)'),
	88 : Pos('v2z-s', 'Nidan verb (lower class) with "zu" ending (archaic)'),
	89 : Pos('v2t-s', 'Nidan verb (lower class) with "tsu" ending (archaic)'),
	90 : Pos('v2d-s', 'Nidan verb (lower class) with "dzu" ending (archaic)'),
	91 : Pos('v2n-s', 'Nidan verb (lower class) with "nu" ending (archaic)'),
	92 : Pos('v2h-s', 'Nidan verb (lower class) with "hu/fu" ending (archaic)'),
	93 : Pos('v2b-s', 'Nidan verb (lower class) with "bu" ending (archaic)'),
	94 : Pos('v2m-s', 'Nidan verb (lower class) with "mu" ending (archaic)'),
	95 : Pos('v2y-s', 'Nidan verb (lower class) with "yu" ending (archaic)'),
	96 : Pos('v2r-s', 'Nidan verb (lower class) with "ru" ending (archaic)'),
	97 : Pos('v2w-s', 'Nidan verb (lower class) with "u" ending and "we" conjugation (archaic)'),
	98 : Pos('unc', 'unclassified'),
};