name: dakanji_db_ui
description: Project to provide a user interface for DaKanjiDB
publish_to: 'none'
resolution: workspace
version: 1.0.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_widget_from_html: ^0.17.0
  dakanji_db_core:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
