// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return macos;
      case TargetPlatform.linux:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHQO6DF7CkJNq3zvOYslkD0Tz5Edl3FNE',
    appId: '1:732385011595:android:30bd603e8993920771f18e',
    messagingSenderId: '732385011595',
    projectId: 'dakanji-app',
    storageBucket: 'dakanji-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk6sw6Z6D3JW4Otl_mGvMh5EhHnzvYIv4',
    appId: '1:732385011595:ios:957e69a0bce1a8f071f18e',
    messagingSenderId: '732385011595',
    projectId: 'dakanji-app',
    storageBucket: 'dakanji-app.appspot.com',
    iosBundleId: 'com.DaAppLab.daKanji',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDk6sw6Z6D3JW4Otl_mGvMh5EhHnzvYIv4',
    appId: '1:732385011595:ios:957e69a0bce1a8f071f18e',
    messagingSenderId: '732385011595',
    projectId: 'dakanji-app',
    storageBucket: 'dakanji-app.appspot.com',
    iosBundleId: 'com.DaAppLab.daKanji',
  );
}
