name: dakanji_db_shared
description: Some utilities for the DaKanji database shared across its packages
version: 1.0.0
resolution: workspace

environment:
  sdk: ^3.9.0

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  universal_io: ^2.2.2

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
