// ignore_for_file: non_constant_identifier_names, constant_identifier_names

// THIS FILE IS AUTOMATICALLY GENERATED
// DO NOT EDIT MANUALLY

const double c_AUDIOS_SIZE_MB = 138.9;
const double c_CNN_SINGLE_CHAR_SIZE_MB = 20.1;
const double c_DICTIONARY_SIZE_MB = 66.5;
const double c_EXAMPLES_SIZE_MB = 46.1;
const double c_KRAD_SIZE_MB = 0.8;
const double c_MECAB_DICT_SIZE_MB = 42.5;
const double c_RADK_SIZE_MB = 0.5;

const List<double> g_DaKanjiAssetSizes = [
	c_CNN_SINGLE_CHAR_SIZE_MB,
	c_DICTIONARY_SIZE_MB,
	c_EXAMPLES_SIZE_MB,
	c_KRAD_SIZE_MB,
	c_MECAB_DICT_SIZE_MB,
	c_RADK_SIZE_MB
];

/// Total size of all assets in MB
final double c_INITIAL_DOWNLOAD_SIZE = g_DaKanjiAssetSizes.reduce((v1, v2) => v1 + v2);
