name: util
description: "Package that contains utility widgets and functions for all packages related to DaKanji."
version: 0.0.1
resolution: workspace

environment:
  sdk: ^3.10.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

