name: dakanji_db_ui_example
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
resolution: workspace

environment:
  sdk: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  path: ^1.9.1
  dakanji_db_ui:
  dakanji_db_shared:
  dakanji_db_core:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
