// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Inlines CSS from style/link tags into style attributes.
/// Returns the resulting HTML as a String.
Future<String> inlineCss({required String html}) =>
    RustLib.instance.api.crateApiSimpleInlineCss(html: html);

/// Synchornous version of inline_css
String inlineCssSync({required String html}) =>
    RustLib.instance.api.crateApiSimpleInlineCssSync(html: html);

/// Inlines a specific CSS string into an HTML fragment.
/// Useful for partial templates where you provide the CSS separately.
Future<String> inlineFragment({required String html, required String css}) =>
    RustLib.instance.api.crateApiSimpleInlineFragment(html: html, css: css);

/// Synchronous version of inline_fragment
String inlineFragmentSync({required String html, required String css}) =>
    RustLib.instance.api.crateApiSimpleInlineFragmentSync(html: html, css: css);
