# referenc: https://github.com/ubuntu-flutter-community/software/blob/main/snap/snapcraft.yaml

name: dakanji
adopt-info: dakanji
summary: You are learning Japanese? Then you need to give "DaKanji" a try!
description: You are learning Japanese? Then you need to give "DaKanji" a try! Lookup words, find unknow Kanji, analyze texts and more!
issues: https://github.com/CaptainDario/DaKanji/issues
source-code: https://github.com/CaptainDario/DaKanji

confinement: strict
base: core24
grade: stable
platforms:
  amd64:
  arm64:
assumes:
  - snapd2.60.3

slots:
  dbus-dakanji:
    interface: dbus
    bus: session
    name: com.DaAppLab.DaKanji
    
apps:
  dakanji:
    command: bin/DaKanji
    extensions: [gnome]
    plugs:
      - network
      - home
      - desktop
    slots:
      - dbus-dakanji
    environment:
      GTK_USE_PORTAL: 1

parts:

  flutter-git:
    source: https://github.com/flutter/flutter.git
    source-tag: "3.29.1"
    plugin: nil
    override-build: |
      set -eux
      mkdir -p $CRAFT_PART_INSTALL/usr/bin
      mkdir -p $CRAFT_PART_INSTALL/usr/libexec
      cp -r $CRAFT_PART_SRC $CRAFT_PART_INSTALL/usr/libexec/flutter
      ln -sf $CRAFT_PART_INSTALL/usr/libexec/flutter/bin/flutter $CRAFT_PART_INSTALL/usr/bin/flutter
      export PATH="$CRAFT_PART_INSTALL/usr/bin:$PATH"
      flutter doctor
    build-packages:
      - clang
      - cmake
      - curl
      - ninja-build
      - unzip
    override-prime: ''

  zenity:
    plugin: nil
    stage-packages:
      - zenity

  dakanji:
    after:
      - flutter-git
      - zenity
    source: .
    plugin: nil
    build-packages:
      - jq
    override-build: |
      set -eux
      flutter pub get || true
      flutter build linux --release -v
      craftctl set version="$(jq -r '.version' build/flutter_assets/version.json)"
      mkdir -p $CRAFT_PART_INSTALL/bin
      cp -r build/linux/*/release/bundle/* $CRAFT_PART_INSTALL/bin/

  # Find files provided by the base and platform snap and ensure they aren't
  # duplicated in this snap
  #cleanup:
  #  after: [dakanji]  # Make this part run last; list all your other parts here
  #  plugin: nil
  #  build-snaps: [gnome-42-2204]  # List all content-snaps you're using here
  #  override-prime: |
  #    set -eux
  #    for snap in "gnome-42-2204"; do  # List all content-snaps you're using here
  #      cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$CRAFT_PRIME/{}" "$CRAFT_PRIME/usr/{}" \;
  #    done
  #    for CRUFT in bug lintian man; do
  #      rm -rf $CRAFT_PRIME/usr/share/$CRUFT
  #    done
  #    find $CRAFT_PRIME/usr/share/doc/ -type f -not -name 'copyright' -delete
  #    find $CRAFT_PRIME/usr/share -type d -empty -delete