name: dakanji
version: 3.1.0
summary: You are learning Japanese? Then you need to give "DaKanji" a try!
description: You are learning Japanese? Then you need to give "DaKanji" a try! Lookup words, find unknow Kanji, analyze texts and more!

confinement: strict
base: core18
grade: stable

slots:
  dbus-dakanji:
    interface: dbus
    bus: session
    name: org.daapplab.dakanji
    
apps:
  dakanji:
    command: da_kanji_mobile
    extensions: [flutter-stable]
    plugs:
    - network
    slots:
      - dbus-dakanji
    environment:
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/blas:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/lapack

parts:

  copy-tf-lite:
    plugin: dump
    source: ./blobs
    stage:
    - bin/blobs/libtensorflowlite_c-linux.so
    organize:
      libtensorflowlite_c-linux.so: bin/blobs/libtensorflowlite_c-linux.so

  dakanji:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
    build-packages:
      - libmpv-dev
    stage-packages:
      - libmpv1
      - libblas3