name: All - Test and build

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  windows-test-and-build:
    uses: ./.github/workflows/windows_test_and_build.yml
