name: All - Deploy

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  windows-test-and-build:
    uses: ./.github/workflows/windows_test_and_build.yml
    secrets:
      DA_KANJI_ML_RELEASES_TOKEN: ${{ secrets.DA_KANJI_ML_RELEASES_TOKEN }}
    
  android-test-and-build:
    uses: ./.github/workflows/android_test_and_build.yml
    secrets:
      DA_KANJI_ML_RELEASES_TOKEN: ${{ secrets.DA_KANJI_ML_RELEASES_TOKEN }}
      KEY_PROPERTIES_KEY_PASSWORD: ${{ secrets.KEY_PROPERTIES_KEY_PASSWORD }}
      KEY_PROPERTIES_STORE_PASSWORD: ${{ secrets.KEY_PROPERTIES_STORE_PASSWORD }}
      KEY_PROPERTIES_KEY_ALIAS: ${{ secrets.KEY_PROPERTIES_KEY_ALIAS }}
      KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
      

  upload-releases-to-github:
    # upload to github releases after everything is build
    needs: [windows-test-and-build, android-test-and-build]

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: testing
        run: |
          echo "test"


  deploy:
    # send discord notifications after everything is uploaded to github releases
    needs: upload-releases-to-github

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Get latest changes and set LATEST_CHANGES
        run: |
          python .github/workflows/get_latest_changes.py

          echo 'LATEST_CHANGES<<EOF' >> $GITHUB_ENV
          cat latest_changes.txt >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - name: Get deploy message and set DEPLOY_MESSAGE
        run: |
          python .github/workflows/get_latest_changes.py

          echo 'DEPLOY_MESSAGE<<EOF' >> $GITHUB_ENV
          cat deploy_message.txt >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WORKFLOW_TEST_WEBHOOK }}
          STORE_URL: https://www.microsoft.com/p/dakanji/9n08051t2xtv?rtc=1#activetab=pivot:overviewtab
        uses: Ilshidur/action-discord@0.3.2
        with:
          args: "{{ DEPLOY_MESSAGE }}"
