name: All - Test and build

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  windows-test-and-build:
    uses: ./.github/workflows/windows_test_and_build.yml
    #secrets:

  linux-test-and-build:
    uses: ./.github/workflows/linux_test_and_build.yml
    #secrets:

  macos-test-and-build:
    uses: ./.github/workflows/macos_test_and_build.yml
    #secrets:

  android-test-and-build:
    uses: ./.github/workflows/android_test_and_build.yml
    #secrets:

  ios-test-and-build:
    uses: ./.github/workflows/ios_test_and_build.yml
    #secrets:
