name: All - Test and build

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  static_checks:
    uses: ./.github/workflows/static_checks.yml

  cache_assets:
    needs:
      - static_checks
    uses: ./.github/workflows/get_dakanji_assets.yml
  
  android-test-and-build:
    uses: ./.github/workflows/android_test_and_build.yml
    needs:
      - cache_assets
    secrets:
      KEY_PROPERTIES_KEY_PASSWORD: ${{ secrets.KEY_PROPERTIES_KEY_PASSWORD }}
      KEY_PROPERTIES_STORE_PASSWORD: ${{ secrets.KEY_PROPERTIES_STORE_PASSWORD }}
      KEY_PROPERTIES_KEY_ALIAS: ${{ secrets.KEY_PROPERTIES_KEY_ALIAS }}
      KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}

  #ios-test-and-build:
  #  needs:
  #    - cache_assets
  #  uses: ./.github/workflows/ios_test_and_build.yml

  linux-test-and-build:
    needs:
      - cache_assets
    uses: ./.github/workflows/linux_test_and_build.yml
  macos-test-and-build:
    needs:
      - cache_assets
    uses: ./.github/workflows/macos_test_and_build.yml
  windows-test-and-build:
    needs:
      - cache_assets
    secrets:
      SELF_SIGN_MSIX_PFX: ${{secrets.SELF_SIGN_MSIX_PFX}}
      SELF_SIGN_MSIX_PWD: ${{secrets.SELF_SIGN_MSIX_PWD}}
    uses: ./.github/workflows/windows_test_and_build.yml
