


name: Deploy windows test version 

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # env variable to store the latest changes
    env:
      Greeting: Hello

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Get latest changes
        run: |
          python get_latest_changes.py
          export LATEST_CHANGES=$(cat latest_changes.txt)
          printenv LATEST_CHANGES

      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WINDOWS_TEST_WEBHOOK }}
        uses: Ilshidur/action-discord@0.3.2
        with:
          args: 'Ignore this, this is just a test. \n\n\n {{ LATEST_CHANGES }}'