# This is a basic workflow to help you get started with Actions

name: Download binary from private repo

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: download TF Lite files from DaKanji-ML
        run: curl --output CNN_single_char.tflite https://github.com/CaptainDario/DaKanji-ML/releases/latest/CNN_single_char.tflite
