# This is a basic workflow to help you get started with Actions

name: Download binary from private repo

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      - name: Download release asset
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          file: CNN_single_char.tflite
          target: CNN_single_char.tflite
          token: ${{ secrets.DEPLOY_TOKEN }}



