# This is a basic workflow to help you get started with Actions

name: Linux - Test and Build

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  # allows that other workflows can run this one
  workflow_call:
    #secrets:

#env:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_test:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # get versions from pubspec
      - name: set env variables
        run: |
          python3 ./.github/workflows/building.py set_env_flutter_version
          python3 ./.github/workflows/building.py set_env_dakanji_version

      - name: Install and set Flutter version
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{env.FLUTTER_VERSION}}
          channel: stable
          
      - name: Restore packages
        run: flutter pub get
        
      # # download all files necessary to run dakanji
      - name: setup dakanji
        run: python3 setup.py
        
      - name: install build packages
        run: |
          sudo apt-get install clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev libmpv-dev mpv

      - name: Run integration tests
        run: python3 ./integration_test/run_tests.py

      # build portable linux
      - name: build linux executable
        run: |
          flutter build linux --release
          zip -r DaKanji_${{env.DAKANJI_VERSION}}_ubuntu_22_04.zip build/linux/x64/release/bundle
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: DaKanji_${{env.DAKANJI_VERSION}}_ubuntu_22_04.zip
          path: DaKanji_${{env.DAKANJI_VERSION}}_ubuntu_22_04.zip

      # TODO build flatpak


      # build SNAP
      - name: prepare snap building
        run: |
          python3 ./.github/workflows/building.py update_snapcraft_yaml
          flutter clean
          flutter pub get
      - name: Install Snapcraft and build snap
        uses: snapcore/action-build@v1
        id: snapcraft
      - name: Rename snap
        run: |
          mv ${{ steps.snapcraft.outputs.snap }} DaKanji_${{env.DAKANJI_VERSION}}.snap
      - name: Upload snap as artifact
        uses: actions/upload-artifact@v3
        with:
          name: DaKanji_${{env.DAKANJI_VERSION}}.snap
          path: DaKanji_${{env.DAKANJI_VERSION}}.snap
