# This is a basic workflow to help you get started with Actions

name: MacOS - Test and Build

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # allows that other workflows can run this one
  workflow_call:
    secrets:
      SENTRY_DSN:
        required: true
      POSTHOG_API_KEY_DEV:
        required: true
      POSTHOG_API_KEY_REL:
        required: true

#env:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-15

    env:
      MACOS_APP_RELEASE_PATH: build/macos/Build/Products/Release

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      # get versions from pubspec
      - name: set env variables
        run: |
          python3 ./.github/workflows/building.py set_env_flutter_version
          python3 ./.github/workflows/building.py set_env_dakanji_version

      - name: Install and set Flutter version
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{env.FLUTTER_VERSION}}
          channel: stable
          
      - name: Restore packages
        run: flutter pub get

      - name: Setup DaKanji env.dart
        env:
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }} 
          POSTHOG_API_KEY_REL: ${{ secrets.POSTHOG_API_KEY_REL }} 
          POSTHOG_API_KEY_DEV: ${{ secrets.POSTHOG_API_KEY_DEV }} 
        run: |
          python3 ./.github/workflows/create_dakanji_env.py
          flutter pub run build_runner build --delete-conflicting-outputs
        
      # get / set dakanji assets from cache
      - name: Check dakanji assets in cache
        id: cache-dakanji-assets-restore
        uses: actions/cache/restore@v3
        with:
          path: tmp
          key: dakanji-assets
      - name: Download DaKanji assets if necessary
        if: steps.cache-dakanji-assets-restore.outputs.cache-hit != 'true'
        run: |
          python3 setup.py --download-all --no-delete
      - name: Move DaKanji assets if in cache
        if: steps.cache-dakanji-assets-restore.outputs.cache-hit == 'true'
        run: |
          python3 setup.py --no-download 
      - name: Save dakanji assets to cache if not saved
        if: steps.cache-dakanji-assets-restore.outputs.cache-hit != 'true'
        id: cache-dakanji-assets-save
        uses: actions/cache/save@v3
        with:
          path: tmp
          key: dakanji-assets

      - name: enable macos
        run: flutter config --enable-macos-desktop

      #- name: Run integration tests
      #  run: |
      #    pod --version
      #    python3 ./integration_test/run_tests.py

      - name: build macos executable
        run: |

          flutter build macos --release -v
          ditto -c -k --sequesterRsrc --keepParent ${{env.MACOS_APP_RELEASE_PATH}}/DaKanji.app/ DaKanji_${{env.DAKANJI_VERSION}}_app.zip
      - name: setup signing
        run: |
          echo ${{secrets.MACOS_CERT}} | base64 --decode > certificate.p12
          echo "Create Keychain"
          security create-keychain -p ${{secrets.MACOS_KEYCHAIN_PWD}} build.keychain
          echo "Assign to Login Keychain"
          security default-keychain -s build.keychain
          echo "Unlock the Login Keychain"
          security unlock-keychain -p ${{secrets.MACOS_KEYCHAIN_PWD}} build.keychain
          echo "Import certificate"
          security import certificate.p12 -k build.keychain -P ${{secrets.MACOS_CERT_PWD}} -T /usr/bin/codesign
          echo "Set Key Partition"
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k ${{secrets.MACOS_KEYCHAIN_PWD}} build.keychain
          echo "Find Identity"
          security find-identity
          echo "Sign the app"
          /usr/bin/codesign --force --deep -s ${{ secrets.MACOS_IDENTITY }} ./${{env.MACOS_APP_RELEASE_PATH}}/<YOUR-APP-NAME>.app

      - name: Create DMG
        run: |
          brew install create-dmg
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: DaKanji_${{env.DAKANJI_VERSION}}_app.zip
          path: DaKanji_${{env.DAKANJI_VERSION}}_app.zip

