name: test


# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:  
  STORE_URL: 'https://www.microsoft.com/p/dakanji/9n08051t2xtv?rtc=1#activetab=pivot:overviewtab'
  RETENTION: 2

jobs:

  create-mock-build:
  
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Create mock production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: test.txt
          path: .github/workflows/deploy_message.txt
          retention-days: "${{ env.RETENTION }}"

  upload-releases-to-github:
    # upload to github releases after everything is build
    needs: [create-mock-build]

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:

      - uses: actions/download-artifact@v3
        with:
          path: artifacts/

      - name: list current dir
        run: ls -a

      - name: Upload to github releases
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file:  "${{ env.GITHUB_WORKSPACE }}/artifacts/*"
          file_glob: true
          tag: beta
          prerelease: true
          overwrite: true
          body: |
            IMPORTANT: this is a pre-release, you should expect some bugs 

            Changelog:
            ${{ env.LATEST_CHANGES }}
