name: test


# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:  
  STORE_URL: 'https://www.microsoft.com/p/dakanji/9n08051t2xtv?rtc=1#activetab=pivot:overviewtab'

jobs:

  create-mock-build:
  
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Create mock production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: test.txt
          path: .github/workflows/deploy_message.txt

  upload-releases-to-github:
    # upload to github releases after everything is build
    needs: [create-mock-build]

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v3
        with:
          path: artifacts/

      - name: list current dir
        run: |

          ls artifacts/
          echo "$GITHUB_WORKSPACE/artifacts/*"

          python .github/workflows/latest_changes.py
          touch artifacts/test_2.txt
          echo "testest" > artifacts/test_2.txt
          touch artifacts/test_3.txt
          echo "testest" > artifacts/test_3.txt

      - name: Upload files to github release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # artifacts/*.apk artifacts/*.aab artifacts/*.msix artifacts/*.zip 
        run: |
          cd artifacts
          gh release create \
            beta \
            $(ls -p | grep -v / | tr '\n' ' ') \
            -F latest_changes.txt \
            -p \
            -t "$(head -n 1 latest_changes.txt)" \
