name: test


# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  create-mock-build:
  
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: test.txt
          path: .github/workflows/deploy_message.txt

  upload-releases-to-github:
    # upload to github releases after everything is build
    needs: [create-mock-build]

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:

      - uses: actions/download-artifact@v3
        with:
          name: test.txt
          
      - name: Display structure of downloaded files
        run: ls -R
          
      - name: Upload to github releases
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: test.txt
          tag: ${{ github.ref }}
          prerelease: true
          overwrite: true
          body: |
            DaKanji v2.0 - beta



  deploy:
    # send discord notifications after everything is uploaded to github releases
    needs: upload-releases-to-github

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Get latest changes
        run: |
          python .github/workflows/get_latest_changes.py
          echo 'LATEST_CHANGES<<EOF' >> $GITHUB_ENV
          cat latest_changes.txt >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WORKFLOW_TEST_WEBHOOK }}
        uses: Ilshidur/action-discord@0.3.2
        with:
          args: |
            Hello DaKanji-testers,
            a new release of DaKanji is coming soon and you can try the beta version now.
            The most important changes are:
            
            {{ LATEST_CHANGES }}
            As always you can get the release from (usually it takes some time till it is available):
            
            https://www.microsoft.com/p/dakanji/9n08051t2xtv?rtc=1#activetab=pivot:overviewtab
            or
            https://www.github.com/CaptainDario/DaKanji-Mobile/releases
            If you are not yet registered as a tester or have a different problem, please send me message.
            
            Thank you so much for taking the time to test DaKanji. 
            You rock <3
