
# This is a basic workflow to help you get started with Actions

name: Windows - Deploy

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # allows that other workflows can run this one
  workflow_call:
    #secrets:

#env:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2022

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # get versions from pubspec
      - name: set env variables
        run: |
          python3 ./.github/workflows/building.py set_env_flutter_version
          python3 ./.github/workflows/building.py set_env_dakanji_version

      # get msix GH and exe artifact and upload it to GH
      - name: get exe build artifacts
        uses: actions/download-artifact@v3
        if: ${{github.event.inputs.upload_to_gh == 'true'}}
        with:
          name: DaKanji_${{env.DAKANJI_VERSION}}_gh.msix
      - name: get exe build artifacts
        uses: actions/download-artifact@v3
        if: ${{github.event.inputs.upload_to_gh == 'true'}}
        with:
          name: DaKanji_${{env.DAKANJI_VERSION}}_gh.msix

      # get msix store artifact and upload it to MS store
      - name: get build artifacts for snap
        uses: actions/download-artifact@v3
        if: ${{github.event.inputs.upload_to_stores == 'beta'}}
        with:
          name: DaKanji_${{env.DAKANJI_VERSION}}_store.msix
