# This is a basic workflow to help you get started with Actions

name: Windows - Test and Build

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # allows that other workflows can run this one
  workflow_call:
    secrets:
      DA_KANJI_ML_RELEASES_TOKEN: 
        required: true

#env:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2022

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # get versions from pubspec
      - name: set env variables
        run: |
          python3 ./.github/workflows/building.py set_env_flutter_version
          python3 ./.github/workflows/building.py set_env_dakanji_version

      - name: Install and set Flutter version
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{env.FLUTTER_VERSION}}
          channel: stable
          
      - name: Restore packages
        run: flutter pub get
        
      # download all files necessary to run dakanji
      - name: setup dakanji
        run: python3 setup.py

      # TESTS  
      #- name: Analyze
      #  run: flutter analyze
      
      #- name: Run integration tests
      #  run: python ./integration_test/run_tests.py

      - name: build exe
        run: flutter build windows --release

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: DaKanji_${{env.DAKANJI_VERSION}}_exe.zip
          path: build/windows/runner/Release/

      - name: build MSIX
        run: flutter pub run msix:create --build-windows=false --store
     
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: DaKanji_${{env.DAKANJI_VERSION}}.msix
          path: build\windows\runner\Release\da_kanji_mobile.msix
