name: dakanji_db_example
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1
resolution: workspace

environment:
  sdk: ^3.10.0-162.1.beta


dependencies:
  flutter:
    sdk: flutter

  dakanji_db_core:
  path_provider: ^2.1.5
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - ../../tmp/dakanji.db