name: dakanji_db_example
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1
resolution: workspace

environment:
  sdk: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter

  dakanji_db_core:
  language_processing:

  csslib: ^1.0.2
  provider: ^6.1.5+1
  path_provider: ^2.1.5
  flutter_widget_from_html_core: ^0.17.0
  cupertino_icons: ^1.0.8
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/dakanji.db